//This file is automatically generated.
//The original file is lv_example_png.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_png.h"

//The original function is: lv_example_png_1.
void safe_lv_example_png_1(void)
{
    GhostLV_Lock();
    lv_example_png_1();
    GhostLV_Unlock();
}

