//This file is automatically generated.
//The original file is lv_example_get_started.h
#include "lv_example_get_started.h"

//The original function is: lv_example_get_started_1.
void safe_lv_example_get_started_1(void);

//The original function is: lv_example_get_started_2.
void safe_lv_example_get_started_2(void);

//The original function is: lv_example_get_started_3.
void safe_lv_example_get_started_3(void);

