//This file is automatically generated.
//The original file is lv_led.h
#include "GhostSafeLVGL.h"
#include "safe_lv_led.h"

//The original function is: lv_led_create.
lv_obj_t * safe_lv_led_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_led_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_led_set_color.
void safe_lv_led_set_color(lv_obj_t * led, lv_color_t color)
{
    GhostLV_Lock();
    lv_led_set_color(led, color);
    GhostLV_Unlock();
}

//The original function is: lv_led_set_brightness.
void safe_lv_led_set_brightness(lv_obj_t * led, uint8_t bright)
{
    GhostLV_Lock();
    lv_led_set_brightness(led, bright);
    GhostLV_Unlock();
}

//The original function is: lv_led_on.
void safe_lv_led_on(lv_obj_t * led)
{
    GhostLV_Lock();
    lv_led_on(led);
    GhostLV_Unlock();
}

//The original function is: lv_led_off.
void safe_lv_led_off(lv_obj_t * led)
{
    GhostLV_Lock();
    lv_led_off(led);
    GhostLV_Unlock();
}

//The original function is: lv_led_toggle.
void safe_lv_led_toggle(lv_obj_t * led)
{
    GhostLV_Lock();
    lv_led_toggle(led);
    GhostLV_Unlock();
}

//The original function is: lv_led_get_brightness.
uint8_t safe_lv_led_get_brightness(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint8_t ret = lv_led_get_brightness(obj);
    GhostLV_Unlock();
    return ret;
}

