//This file is automatically generated.
//The original file is lv_bmp.h
#include "GhostSafeLVGL.h"
#include "safe_lv_bmp.h"

//The original function is: lv_bmp_init.
void safe_lv_bmp_init(void)
{
    GhostLV_Lock();
    lv_bmp_init();
    GhostLV_Unlock();
}

