//This file is automatically generated.
//The original file is lv_tileview.h
#include "GhostSafeLVGL.h"
#include "safe_lv_tileview.h"

//The original function is: lv_tileview_create.
lv_obj_t * safe_lv_tileview_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tileview_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_set_tile.
void safe_lv_obj_set_tile(lv_obj_t * tv, lv_obj_t * tile_obj, lv_anim_enable_t anim_en)
{
    GhostLV_Lock();
    lv_obj_set_tile(tv, tile_obj, anim_en);
    GhostLV_Unlock();
}

//The original function is: lv_tileview_get_tile_act.
lv_obj_t * safe_lv_tileview_get_tile_act(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tileview_get_tile_act(obj);
    GhostLV_Unlock();
    return ret;
}

