//This file is automatically generated.
//The original file is lv_tileview.h
#include "lvgl.h"

//The original function is: lv_tileview_create.
lv_obj_t * safe_lv_tileview_create(lv_obj_t * parent);

//The original function is: lv_obj_set_tile.
void safe_lv_obj_set_tile(lv_obj_t * tv, lv_obj_t * tile_obj, lv_anim_enable_t anim_en);

//The original function is: lv_tileview_get_tile_act.
lv_obj_t * safe_lv_tileview_get_tile_act(lv_obj_t * obj);

