//This file is automatically generated.
//The original file is lv_demo_stress.h
#include "GhostSafeLVGL.h"
#include "safe_lv_demo_stress.h"

//The original function is: lv_demo_stress.
void safe_lv_demo_stress(void)
{
    GhostLV_Lock();
    lv_demo_stress();
    GhostLV_Unlock();
}

