//This file is automatically generated.
//The original file is lv_calendar_header_dropdown.h
#include "GhostSafeLVGL.h"
#include "safe_lv_calendar_header_dropdown.h"

//The original function is: lv_calendar_header_dropdown_create.
lv_obj_t * safe_lv_calendar_header_dropdown_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_calendar_header_dropdown_create(parent);
    GhostLV_Unlock();
    return ret;
}

