//This file is automatically generated.
//The original file is lv_calendar_header_dropdown.h
#include "lvgl.h"

//The original function is: lv_calendar_header_dropdown_create.
lv_obj_t * safe_lv_calendar_header_dropdown_create(lv_obj_t * parent);

