//This file is automatically generated.
//The original file is lv_calendar.h
#include "lv_calendar.h"

//The original function is: lv_calendar_create.
lv_obj_t * safe_lv_calendar_create(lv_obj_t * parent);

//The original function is: lv_calendar_set_today_date.
void safe_lv_calendar_set_today_date(lv_obj_t * obj, uint32_t year, uint32_t month, uint32_t day);

//The original function is: lv_calendar_set_showed_date.
void safe_lv_calendar_set_showed_date(lv_obj_t * obj, uint32_t year, uint32_t month);

//The original function is: lv_calendar_set_highlighted_dates.
void safe_lv_calendar_set_highlighted_dates(lv_obj_t * obj, lv_calendar_date_t highlighted[], uint16_t date_num);

//The original function is: lv_calendar_set_day_names.
void safe_lv_calendar_set_day_names(lv_obj_t * obj, const char ** day_names);

//The original function is: lv_calendar_get_btnmatrix.
lv_obj_t * safe_lv_calendar_get_btnmatrix(const lv_obj_t * obj);

//The original function is: lv_calendar_get_today_date.
const lv_calendar_date_t * safe_lv_calendar_get_today_date(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_showed_date.
const lv_calendar_date_t * safe_lv_calendar_get_showed_date(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_highlighted_dates.
lv_calendar_date_t * safe_lv_calendar_get_highlighted_dates(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_highlighted_dates_num.
uint16_t safe_lv_calendar_get_highlighted_dates_num(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_pressed_date.
lv_res_t safe_lv_calendar_get_pressed_date(const lv_obj_t * calendar, lv_calendar_date_t * date);

