//This file is automatically generated.
//The original file is lv_calendar.h
#include "lvgl.h"

//The original function is: lv_calendar_create.
lv_obj_t * safe_lv_calendar_create(lv_obj_t * parent);

//The original function is: lv_calendar_set_day_names.
void safe_lv_calendar_set_day_names(lv_obj_t * obj, const char ** day_names);

//The original function is: lv_calendar_get_btnmatrix.
lv_obj_t * safe_lv_calendar_get_btnmatrix(const lv_obj_t * obj);

//The original function is: lv_calendar_get_today_date.
const lv_calendar_date_t * safe_lv_calendar_get_today_date(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_showed_date.
const lv_calendar_date_t * safe_lv_calendar_get_showed_date(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_highlighted_dates.
lv_calendar_date_t * safe_lv_calendar_get_highlighted_dates(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_highlighted_dates_num.
uint16_t safe_lv_calendar_get_highlighted_dates_num(const lv_obj_t * calendar);

//The original function is: lv_calendar_get_pressed_date.
lv_res_t safe_lv_calendar_get_pressed_date(const lv_obj_t * calendar, lv_calendar_date_t * date);

