//This file is automatically generated.
//The original file is lv_gpu_arm2d.h
#include "lvgl.h"

//The original function is: lv_draw_arm2d_ctx_init.
void safe_lv_draw_arm2d_ctx_init(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_draw_arm2d_ctx_deinit.
void safe_lv_draw_arm2d_ctx_deinit(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx);

