//This file is automatically generated.
//The original file is lv_ffmpeg.h
#include "lv_ffmpeg.h"

//The original function is: lv_ffmpeg_init.
void safe_lv_ffmpeg_init(void);

//The original function is: lv_ffmpeg_get_frame_num.
int safe_lv_ffmpeg_get_frame_num(const char * path);

//The original function is: lv_ffmpeg_player_create.
lv_obj_t * safe_lv_ffmpeg_player_create(lv_obj_t * parent);

//The original function is: lv_ffmpeg_player_set_src.
lv_res_t safe_lv_ffmpeg_player_set_src(lv_obj_t * obj, const char * path);

//The original function is: lv_ffmpeg_player_set_cmd.
void safe_lv_ffmpeg_player_set_cmd(lv_obj_t * obj, lv_ffmpeg_player_cmd_t cmd);

//The original function is: lv_ffmpeg_player_set_auto_restart.
void safe_lv_ffmpeg_player_set_auto_restart(lv_obj_t * obj, bool en);

