//This file is automatically generated.
//The original file is lv_imgbtn.h
#include "lvgl.h"

//The original function is: lv_imgbtn_create.
lv_obj_t * safe_lv_imgbtn_create(lv_obj_t * parent);

//The original function is: lv_imgbtn_set_state.
void safe_lv_imgbtn_set_state(lv_obj_t * imgbtn, lv_imgbtn_state_t state);

//The original function is: lv_imgbtn_get_src_left.
const void * safe_lv_imgbtn_get_src_left(lv_obj_t * imgbtn, lv_imgbtn_state_t state);

//The original function is: lv_imgbtn_get_src_middle.
const void * safe_lv_imgbtn_get_src_middle(lv_obj_t * imgbtn, lv_imgbtn_state_t state);

//The original function is: lv_imgbtn_get_src_right.
const void * safe_lv_imgbtn_get_src_right(lv_obj_t * imgbtn, lv_imgbtn_state_t state);

