//This file is automatically generated.
//The original file is lv_example_anim.h
#include "lv_example_anim.h"

//The original function is: lv_example_anim_1.
void safe_lv_example_anim_1(void);

//The original function is: lv_example_anim_2.
void safe_lv_example_anim_2(void);

//The original function is: lv_example_anim_3.
void safe_lv_example_anim_3(void);

//The original function is: lv_example_anim_timeline_1.
void safe_lv_example_anim_timeline_1(void);

