//This file is automatically generated.
//The original file is lv_colorwheel.h
#include "lv_colorwheel.h"

//The original function is: lv_colorwheel_create.
lv_obj_t * safe_lv_colorwheel_create(lv_obj_t * parent, bool knob_recolor);

//The original function is: lv_colorwheel_set_hsv.
bool safe_lv_colorwheel_set_hsv(lv_obj_t * obj, lv_color_hsv_t hsv);

//The original function is: lv_colorwheel_set_rgb.
bool safe_lv_colorwheel_set_rgb(lv_obj_t * obj, lv_color_t color);

//The original function is: lv_colorwheel_set_mode.
void safe_lv_colorwheel_set_mode(lv_obj_t * obj, lv_colorwheel_mode_t mode);

//The original function is: lv_colorwheel_set_mode_fixed.
void safe_lv_colorwheel_set_mode_fixed(lv_obj_t * obj, bool fixed);

//The original function is: lv_colorwheel_get_hsv.
lv_color_hsv_t safe_lv_colorwheel_get_hsv(lv_obj_t * obj);

//The original function is: lv_colorwheel_get_rgb.
lv_color_t safe_lv_colorwheel_get_rgb(lv_obj_t * obj);

//The original function is: lv_colorwheel_get_color_mode.
lv_colorwheel_mode_t safe_lv_colorwheel_get_color_mode(lv_obj_t * obj);

//The original function is: lv_colorwheel_get_color_mode_fixed.
bool safe_lv_colorwheel_get_color_mode_fixed(lv_obj_t * obj);

