//This file is automatically generated.
//The original file is lv_colorwheel.h
#include "GhostSafeLVGL.h"
#include "safe_lv_colorwheel.h"

//The original function is: lv_colorwheel_create.
lv_obj_t * safe_lv_colorwheel_create(lv_obj_t * parent, bool knob_recolor)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_colorwheel_create(parent, knob_recolor);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_set_hsv.
bool safe_lv_colorwheel_set_hsv(lv_obj_t * obj, lv_color_hsv_t hsv)
{
    GhostLV_Lock();
    bool ret = lv_colorwheel_set_hsv(obj, hsv);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_set_rgb.
bool safe_lv_colorwheel_set_rgb(lv_obj_t * obj, lv_color_t color)
{
    GhostLV_Lock();
    bool ret = lv_colorwheel_set_rgb(obj, color);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_set_mode.
void safe_lv_colorwheel_set_mode(lv_obj_t * obj, lv_colorwheel_mode_t mode)
{
    GhostLV_Lock();
    lv_colorwheel_set_mode(obj, mode);
    GhostLV_Unlock();
}

//The original function is: lv_colorwheel_set_mode_fixed.
void safe_lv_colorwheel_set_mode_fixed(lv_obj_t * obj, bool fixed)
{
    GhostLV_Lock();
    lv_colorwheel_set_mode_fixed(obj, fixed);
    GhostLV_Unlock();
}

//The original function is: lv_colorwheel_get_hsv.
lv_color_hsv_t safe_lv_colorwheel_get_hsv(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_color_hsv_t ret = lv_colorwheel_get_hsv(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_get_rgb.
lv_color_t safe_lv_colorwheel_get_rgb(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_color_t ret = lv_colorwheel_get_rgb(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_get_color_mode.
lv_colorwheel_mode_t safe_lv_colorwheel_get_color_mode(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_colorwheel_mode_t ret = lv_colorwheel_get_color_mode(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_colorwheel_get_color_mode_fixed.
bool safe_lv_colorwheel_get_color_mode_fixed(lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_colorwheel_get_color_mode_fixed(obj);
    GhostLV_Unlock();
    return ret;
}

