//This file is automatically generated.
//The original file is lv_meter.h
#include "lvgl.h"

//The original function is: lv_meter_create.
lv_obj_t * safe_lv_meter_create(lv_obj_t * parent);

//The original function is: lv_meter_add_scale.
lv_meter_scale_t * safe_lv_meter_add_scale(lv_obj_t * obj);

