//This file is automatically generated.
//The original file is lv_meter.h
#include "lv_meter.h"

//The original function is: lv_meter_create.
lv_obj_t * safe_lv_meter_create(lv_obj_t * parent);

//The original function is: lv_meter_add_scale.
lv_meter_scale_t * safe_lv_meter_add_scale(lv_obj_t * obj);

//The original function is: lv_meter_set_indicator_value.
void safe_lv_meter_set_indicator_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value);

//The original function is: lv_meter_set_indicator_start_value.
void safe_lv_meter_set_indicator_start_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value);

//The original function is: lv_meter_set_indicator_end_value.
void safe_lv_meter_set_indicator_end_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value);

