//This file is automatically generated.
//The original file is lv_meter.h
#include "GhostSafeLVGL.h"
#include "safe_lv_meter.h"

//The original function is: lv_meter_create.
lv_obj_t * safe_lv_meter_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_meter_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_meter_add_scale.
lv_meter_scale_t * safe_lv_meter_add_scale(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_meter_scale_t * ret = lv_meter_add_scale(obj);
    GhostLV_Unlock();
    return ret;
}

