//This file is automatically generated.
//The original file is lv_meter.h
#include "GhostSafeLVGL.h"
#include "safe_lv_meter.h"

//The original function is: lv_meter_create.
lv_obj_t * safe_lv_meter_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_meter_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_meter_add_scale.
lv_meter_scale_t * safe_lv_meter_add_scale(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_meter_scale_t * ret = lv_meter_add_scale(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_meter_set_indicator_value.
void safe_lv_meter_set_indicator_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value)
{
    GhostLV_Lock();
    lv_meter_set_indicator_value(obj, indic, value);
    GhostLV_Unlock();
}

//The original function is: lv_meter_set_indicator_start_value.
void safe_lv_meter_set_indicator_start_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value)
{
    GhostLV_Lock();
    lv_meter_set_indicator_start_value(obj, indic, value);
    GhostLV_Unlock();
}

//The original function is: lv_meter_set_indicator_end_value.
void safe_lv_meter_set_indicator_end_value(lv_obj_t * obj, lv_meter_indicator_t * indic, int32_t value)
{
    GhostLV_Lock();
    lv_meter_set_indicator_end_value(obj, indic, value);
    GhostLV_Unlock();
}

