//This file is automatically generated.
//The original file is lv_draw_sdl_mask.h
#include "lv_draw_sdl_mask.h"

//The original function is: lv_draw_sdl_mask_dump_opa.
lv_opa_t * safe_lv_draw_sdl_mask_dump_opa(const lv_area_t * coords, const int16_t * ids, int16_t ids_count);

