//This file is automatically generated.
//The original file is lv_draw_sdl_rect.h
#include "lv_draw_sdl_rect.h"

//The original function is: lv_draw_sdl_rect_bg_frag_obtain.
SDL_Texture * safe_lv_draw_sdl_rect_bg_frag_obtain(lv_draw_sdl_ctx_t * ctx, lv_coord_t radius);

