//This file is automatically generated.
//The original file is lv_draw_sdl.h
#include "lv_draw_sdl.h"

//The original function is: lv_draw_sdl_init_ctx.
void safe_lv_draw_sdl_init_ctx(lv_disp_drv_t * disp_drv, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_draw_sdl_deinit_ctx.
void safe_lv_draw_sdl_deinit_ctx(lv_disp_drv_t * disp_drv, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_draw_sdl_create_screen_texture.
SDL_Texture * safe_lv_draw_sdl_create_screen_texture(SDL_Renderer * renderer, lv_coord_t hor, lv_coord_t ver);

