//This file is automatically generated.
//The original file is lv_draw_sdl_texture_cache.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sdl_texture_cache.h"

//The original function is: lv_draw_sdl_texture_cache_init.
void safe_lv_draw_sdl_texture_cache_init(lv_draw_sdl_ctx_t * ctx)
{
    GhostLV_Lock();
    lv_draw_sdl_texture_cache_init(ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sdl_texture_cache_deinit.
void safe_lv_draw_sdl_texture_cache_deinit(lv_draw_sdl_ctx_t * ctx)
{
    GhostLV_Lock();
    lv_draw_sdl_texture_cache_deinit(ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sdl_texture_cache_get.
SDL_Texture * safe_lv_draw_sdl_texture_cache_get(lv_draw_sdl_ctx_t * ctx, const void * key, size_t key_length, bool * found)
{
    GhostLV_Lock();
    SDL_Texture * ret = lv_draw_sdl_texture_cache_get(ctx, key, key_length, found);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_sdl_texture_cache_put.
void safe_lv_draw_sdl_texture_cache_put(lv_draw_sdl_ctx_t * ctx, const void * key, size_t key_length, SDL_Texture * texture)
{
    GhostLV_Lock();
    lv_draw_sdl_texture_cache_put(ctx, key, key_length, texture);
    GhostLV_Unlock();
}

