//This file is automatically generated.
//The original file is lv_draw_sdl_texture_cache.h
#include "lv_draw_sdl_texture_cache.h"

//The original function is: lv_draw_sdl_texture_cache_init.
void safe_lv_draw_sdl_texture_cache_init(lv_draw_sdl_ctx_t * ctx);

//The original function is: lv_draw_sdl_texture_cache_deinit.
void safe_lv_draw_sdl_texture_cache_deinit(lv_draw_sdl_ctx_t * ctx);

//The original function is: lv_draw_sdl_texture_cache_get.
SDL_Texture * safe_lv_draw_sdl_texture_cache_get(lv_draw_sdl_ctx_t * ctx, const void * key, size_t key_length, bool * found);

//The original function is: lv_draw_sdl_texture_cache_put.
void safe_lv_draw_sdl_texture_cache_put(lv_draw_sdl_ctx_t * ctx, const void * key, size_t key_length, SDL_Texture * texture);

