//This file is automatically generated.
//The original file is lv_draw_sdl_stack_blur.h
#include "lv_draw_sdl_stack_blur.h"

//The original function is: lv_stack_blur_grayscale.
void safe_lv_stack_blur_grayscale(lv_opa_t * buf, uint16_t w, uint16_t h, uint16_t r);

