//This file is automatically generated.
//The original file is lv_draw_sdl_composite.h
#include "lv_draw_sdl_composite.h"

//The original function is: lv_draw_sdl_composite_end.
void safe_lv_draw_sdl_composite_end(lv_draw_sdl_ctx_t * ctx, const lv_area_t * apply_area, lv_blend_mode_t blend_mode);

