//This file is automatically generated.
//The original file is lv_draw_sdl.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sdl.h"

//The original function is: lv_draw_sdl_init_ctx.
void safe_lv_draw_sdl_init_ctx(lv_disp_drv_t * disp_drv, lv_draw_ctx_t * draw_ctx)
{
    GhostLV_Lock();
    lv_draw_sdl_init_ctx(disp_drv, draw_ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sdl_deinit_ctx.
void safe_lv_draw_sdl_deinit_ctx(lv_disp_drv_t * disp_drv, lv_draw_ctx_t * draw_ctx)
{
    GhostLV_Lock();
    lv_draw_sdl_deinit_ctx(disp_drv, draw_ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sdl_create_screen_texture.
SDL_Texture * safe_lv_draw_sdl_create_screen_texture(SDL_Renderer * renderer, lv_coord_t hor, lv_coord_t ver)
{
    GhostLV_Lock();
    SDL_Texture * ret = lv_draw_sdl_create_screen_texture(renderer, hor, ver);
    GhostLV_Unlock();
    return ret;
}

