//This file is automatically generated.
//The original file is lv_draw_sdl_composite.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sdl_composite.h"

//The original function is: lv_draw_sdl_composite_end.
void safe_lv_draw_sdl_composite_end(lv_draw_sdl_ctx_t * ctx, const lv_area_t * apply_area, lv_blend_mode_t blend_mode)
{
    GhostLV_Lock();
    lv_draw_sdl_composite_end(ctx, apply_area, blend_mode);
    GhostLV_Unlock();
}

