//This file is automatically generated.
//The original file is lv_draw_sdl_utils.h
#include "lv_draw_sdl_utils.h"

//The original function is: lv_area_to_sdl_rect.
void safe_lv_area_to_sdl_rect(const lv_area_t * in, SDL_Rect * out);

//The original function is: lv_color_to_sdl_color.
void safe_lv_color_to_sdl_color(const lv_color_t * in, SDL_Color * out);

//The original function is: lv_area_zoom_to_sdl_rect.
void safe_lv_area_zoom_to_sdl_rect(const lv_area_t * in, SDL_Rect * out, uint16_t zoom, const lv_point_t * pivot);

//The original function is: lv_sdl_alloc_palette_for_bpp.
SDL_Palette * safe_lv_sdl_alloc_palette_for_bpp(const uint8_t * mapping, uint8_t bpp);

//The original function is: lv_sdl_create_opa_surface.
SDL_Surface * safe_lv_sdl_create_opa_surface(lv_opa_t * opa, lv_coord_t width, lv_coord_t height, lv_coord_t stride);

//The original function is: lv_sdl_to_8bpp.
void safe_lv_sdl_to_8bpp(uint8_t * dest, const uint8_t * src, int width, int height, int stride, uint8_t bpp);

