//This file is automatically generated.
//The original file is lv_example_monkey.h
#include "lv_example_monkey.h"

//The original function is: lv_example_monkey_1.
void safe_lv_example_monkey_1(void);

//The original function is: lv_example_monkey_2.
void safe_lv_example_monkey_2(void);

//The original function is: lv_example_monkey_3.
void safe_lv_example_monkey_3(void);

