//This file is automatically generated.
//The original file is lv_test_indev.h
#include "lv_test_indev.h"

//The original function is: lv_test_mouse_read_cb.
void safe_lv_test_mouse_read_cb(lv_indev_drv_t * drv, lv_indev_data_t * data);

//The original function is: lv_test_mouse_move_to.
void safe_lv_test_mouse_move_to(lv_coord_t x, lv_coord_t y);

//The original function is: lv_test_mouse_move_by.
void safe_lv_test_mouse_move_by(lv_coord_t x, lv_coord_t y);

//The original function is: lv_test_mouse_press.
void safe_lv_test_mouse_press(void);

//The original function is: lv_test_mouse_release.
void safe_lv_test_mouse_release(void);

//The original function is: lv_test_mouse_click_at.
void safe_lv_test_mouse_click_at(lv_coord_t x, lv_coord_t y);

//The original function is: lv_test_keypad_read_cb.
void safe_lv_test_keypad_read_cb(lv_indev_drv_t * drv, lv_indev_data_t * data);

//The original function is: lv_test_key_press.
void safe_lv_test_key_press(uint32_t k);

//The original function is: lv_test_key_release.
void safe_lv_test_key_release(void);

//The original function is: lv_test_key_hit.
void safe_lv_test_key_hit(uint32_t k);

//The original function is: lv_test_encoder_add_diff.
void safe_lv_test_encoder_add_diff(int32_t d);

//The original function is: lv_test_encoder_turn.
void safe_lv_test_encoder_turn(int32_t d);

//The original function is: lv_test_encoder_press.
void safe_lv_test_encoder_press(void);

//The original function is: lv_test_encoder_release.
void safe_lv_test_encoder_release(void);

//The original function is: lv_test_encoder_click.
void safe_lv_test_encoder_click(void);

//The original function is: lv_test_indev_wait.
void safe_lv_test_indev_wait(uint32_t ms);

