//This file is automatically generated.
//The original file is lv_freetype.h
#include "lv_freetype.h"

//The original function is: lv_freetype_init.
bool safe_lv_freetype_init(uint16_t max_faces, uint16_t max_sizes, uint32_t max_bytes);

//The original function is: lv_freetype_destroy.
void safe_lv_freetype_destroy(void);

//The original function is: lv_ft_font_init.
bool safe_lv_ft_font_init(lv_ft_info_t * info);

//The original function is: lv_ft_font_destroy.
void safe_lv_ft_font_destroy(lv_font_t * font);

