//This file is automatically generated.
//The original file is lv_font_loader.h
#include "lvgl.h"

//The original function is: lv_font_load.
lv_font_t * safe_lv_font_load(const char * fontName);

//The original function is: lv_font_free.
void safe_lv_font_free(lv_font_t * font);

