//This file is automatically generated.
//The original file is lv_hal_disp.h
#include "GhostSafeLVGL.h"
#include "safe_lv_hal_disp.h"

//The original function is: lv_disp_drv_init.
void safe_lv_disp_drv_init(lv_disp_drv_t * driver)
{
    GhostLV_Lock();
    lv_disp_drv_init(driver);
    GhostLV_Unlock();
}

//The original function is: lv_disp_draw_buf_init.
void safe_lv_disp_draw_buf_init(lv_disp_draw_buf_t * draw_buf, void * buf1, void * buf2, uint32_t size_in_px_cnt)
{
    GhostLV_Lock();
    lv_disp_draw_buf_init(draw_buf, buf1, buf2, size_in_px_cnt);
    GhostLV_Unlock();
}

//The original function is: lv_disp_drv_register.
lv_disp_t * safe_lv_disp_drv_register(lv_disp_drv_t * driver)
{
    GhostLV_Lock();
    lv_disp_t * ret = lv_disp_drv_register(driver);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_drv_update.
void safe_lv_disp_drv_update(lv_disp_t * disp, lv_disp_drv_t * new_drv)
{
    GhostLV_Lock();
    lv_disp_drv_update(disp, new_drv);
    GhostLV_Unlock();
}

//The original function is: lv_disp_remove.
void safe_lv_disp_remove(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_remove(disp);
    GhostLV_Unlock();
}

//The original function is: lv_disp_set_default.
void safe_lv_disp_set_default(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_set_default(disp);
    GhostLV_Unlock();
}

//The original function is: lv_disp_get_default.
lv_disp_t * safe_lv_disp_get_default(void)
{
    GhostLV_Lock();
    lv_disp_t * ret = lv_disp_get_default();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_hor_res.
lv_coord_t safe_lv_disp_get_hor_res(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_hor_res(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_ver_res.
lv_coord_t safe_lv_disp_get_ver_res(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_ver_res(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_physical_hor_res.
lv_coord_t safe_lv_disp_get_physical_hor_res(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_physical_hor_res(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_physical_ver_res.
lv_coord_t safe_lv_disp_get_physical_ver_res(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_physical_ver_res(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_offset_x.
lv_coord_t safe_lv_disp_get_offset_x(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_offset_x(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_offset_y.
lv_coord_t safe_lv_disp_get_offset_y(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_offset_y(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_antialiasing.
bool safe_lv_disp_get_antialiasing(lv_disp_t * disp)
{
    GhostLV_Lock();
    bool ret = lv_disp_get_antialiasing(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_dpi.
lv_coord_t safe_lv_disp_get_dpi(const lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_disp_get_dpi(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_set_rotation.
void safe_lv_disp_set_rotation(lv_disp_t * disp, lv_disp_rot_t rotation)
{
    GhostLV_Lock();
    lv_disp_set_rotation(disp, rotation);
    GhostLV_Unlock();
}

//The original function is: lv_disp_get_rotation.
lv_disp_rot_t safe_lv_disp_get_rotation(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_rot_t ret = lv_disp_get_rotation(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_flush_ready.
LV_ATTRIBUTE_FLUSH_READY void safe_lv_disp_flush_ready(lv_disp_drv_t * disp_drv)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FLUSH_READY void ret = lv_disp_flush_ready(disp_drv);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_flush_is_last.
LV_ATTRIBUTE_FLUSH_READY bool safe_lv_disp_flush_is_last(lv_disp_drv_t * disp_drv)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FLUSH_READY bool ret = lv_disp_flush_is_last(disp_drv);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_next.
lv_disp_t * safe_lv_disp_get_next(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_t * ret = lv_disp_get_next(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_draw_buf.
lv_disp_draw_buf_t * safe_lv_disp_get_draw_buf(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_draw_buf_t * ret = lv_disp_get_draw_buf(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_drv_use_generic_set_px_cb.
void safe_lv_disp_drv_use_generic_set_px_cb(lv_disp_drv_t * disp_drv, lv_img_cf_t cf)
{
    GhostLV_Lock();
    lv_disp_drv_use_generic_set_px_cb(disp_drv, cf);
    GhostLV_Unlock();
}

