//This file is automatically generated.
//The original file is lv_hal_tick.h
#include "GhostSafeLVGL.h"
#include "safe_lv_hal_tick.h"

//The original function is: lv_tick_get.
uint32_t safe_lv_tick_get(void)
{
    GhostLV_Lock();
    uint32_t ret = lv_tick_get();
    GhostLV_Unlock();
    return ret;
}

