//This file is automatically generated.
//The original file is lv_hal_disp.h
#include "lvgl.h"

//The original function is: lv_disp_drv_init.
void safe_lv_disp_drv_init(lv_disp_drv_t * driver);

//The original function is: lv_disp_drv_register.
lv_disp_t * safe_lv_disp_drv_register(lv_disp_drv_t * driver);

//The original function is: lv_disp_drv_update.
void safe_lv_disp_drv_update(lv_disp_t * disp, lv_disp_drv_t * new_drv);

//The original function is: lv_disp_remove.
void safe_lv_disp_remove(lv_disp_t * disp);

//The original function is: lv_disp_set_default.
void safe_lv_disp_set_default(lv_disp_t * disp);

//The original function is: lv_disp_get_default.
lv_disp_t * safe_lv_disp_get_default(void);

//The original function is: lv_disp_get_hor_res.
lv_coord_t safe_lv_disp_get_hor_res(lv_disp_t * disp);

//The original function is: lv_disp_get_ver_res.
lv_coord_t safe_lv_disp_get_ver_res(lv_disp_t * disp);

//The original function is: lv_disp_get_physical_hor_res.
lv_coord_t safe_lv_disp_get_physical_hor_res(lv_disp_t * disp);

//The original function is: lv_disp_get_physical_ver_res.
lv_coord_t safe_lv_disp_get_physical_ver_res(lv_disp_t * disp);

//The original function is: lv_disp_get_offset_x.
lv_coord_t safe_lv_disp_get_offset_x(lv_disp_t * disp);

//The original function is: lv_disp_get_offset_y.
lv_coord_t safe_lv_disp_get_offset_y(lv_disp_t * disp);

//The original function is: lv_disp_get_antialiasing.
bool safe_lv_disp_get_antialiasing(lv_disp_t * disp);

//The original function is: lv_disp_get_dpi.
lv_coord_t safe_lv_disp_get_dpi(const lv_disp_t * disp);

//The original function is: lv_disp_set_rotation.
void safe_lv_disp_set_rotation(lv_disp_t * disp, lv_disp_rot_t rotation);

//The original function is: lv_disp_get_rotation.
lv_disp_rot_t safe_lv_disp_get_rotation(lv_disp_t * disp);

//The original function is: lv_disp_flush_ready.
void safe_lv_disp_flush_ready(lv_disp_drv_t * disp_drv);

//The original function is: lv_disp_flush_is_last.
LV_ATTRIBUTE_FLUSH_READY bool safe_lv_disp_flush_is_last(lv_disp_drv_t * disp_drv);

//The original function is: lv_disp_get_next.
lv_disp_t * safe_lv_disp_get_next(lv_disp_t * disp);

//The original function is: lv_disp_get_draw_buf.
lv_disp_draw_buf_t * safe_lv_disp_get_draw_buf(lv_disp_t * disp);

//The original function is: lv_disp_drv_use_generic_set_px_cb.
void safe_lv_disp_drv_use_generic_set_px_cb(lv_disp_drv_t * disp_drv, lv_img_cf_t cf);

