//This file is automatically generated.
//The original file is lv_hal_tick.h
#include "lv_hal_tick.h"

//The original function is: lv_tick_inc.
LV_ATTRIBUTE_TICK_INC void safe_lv_tick_inc(uint32_t tick_period);

//The original function is: lv_tick_get.
uint32_t safe_lv_tick_get(void);

//The original function is: lv_tick_elaps.
uint32_t safe_lv_tick_elaps(uint32_t prev_tick);

