//This file is automatically generated.
//The original file is lv_hal_indev.h
#include "lvgl.h"

//The original function is: lv_indev_drv_init.
void safe_lv_indev_drv_init(struct _lv_indev_drv_t * driver);

//The original function is: lv_indev_drv_register.
lv_indev_t * safe_lv_indev_drv_register(struct _lv_indev_drv_t * driver);

//The original function is: lv_indev_drv_update.
void safe_lv_indev_drv_update(lv_indev_t * indev, struct _lv_indev_drv_t * new_drv);

//The original function is: lv_indev_delete.
void safe_lv_indev_delete(lv_indev_t * indev);

//The original function is: lv_indev_get_next.
lv_indev_t * safe_lv_indev_get_next(lv_indev_t * indev);

