//This file is automatically generated.
//The original file is lv_rlottie.h
#include "lv_rlottie.h"

//The original function is: lv_rlottie_create_from_file.
lv_obj_t * safe_lv_rlottie_create_from_file(lv_obj_t * parent, lv_coord_t width, lv_coord_t height, const char * path);

//The original function is: lv_rlottie_set_play_mode.
void safe_lv_rlottie_set_play_mode(lv_obj_t * rlottie, const lv_rlottie_ctrl_t ctrl);

//The original function is: lv_rlottie_set_current_frame.
void safe_lv_rlottie_set_current_frame(lv_obj_t * rlottie, const size_t goto_frame);

