//This file is automatically generated.
//The original file is lv_example_gridnav.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_gridnav.h"

//The original function is: lv_example_gridnav_1.
void safe_lv_example_gridnav_1(void)
{
    GhostLV_Lock();
    lv_example_gridnav_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_gridnav_2.
void safe_lv_example_gridnav_2(void)
{
    GhostLV_Lock();
    lv_example_gridnav_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_gridnav_3.
void safe_lv_example_gridnav_3(void)
{
    GhostLV_Lock();
    lv_example_gridnav_3();
    GhostLV_Unlock();
}

