//This file is automatically generated.
//The original file is lv_example_gridnav.h
#include "lv_example_gridnav.h"

//The original function is: lv_example_gridnav_1.
void safe_lv_example_gridnav_1(void);

//The original function is: lv_example_gridnav_2.
void safe_lv_example_gridnav_2(void);

//The original function is: lv_example_gridnav_3.
void safe_lv_example_gridnav_3(void);

