//This file is automatically generated.
//The original file is lv_example_grid.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_grid.h"

//The original function is: lv_example_grid_1.
void safe_lv_example_grid_1(void)
{
    GhostLV_Lock();
    lv_example_grid_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_grid_2.
void safe_lv_example_grid_2(void)
{
    GhostLV_Lock();
    lv_example_grid_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_grid_3.
void safe_lv_example_grid_3(void)
{
    GhostLV_Lock();
    lv_example_grid_3();
    GhostLV_Unlock();
}

//The original function is: lv_example_grid_4.
void safe_lv_example_grid_4(void)
{
    GhostLV_Lock();
    lv_example_grid_4();
    GhostLV_Unlock();
}

//The original function is: lv_example_grid_5.
void safe_lv_example_grid_5(void)
{
    GhostLV_Lock();
    lv_example_grid_5();
    GhostLV_Unlock();
}

//The original function is: lv_example_grid_6.
void safe_lv_example_grid_6(void)
{
    GhostLV_Lock();
    lv_example_grid_6();
    GhostLV_Unlock();
}

