//This file is automatically generated.
//The original file is lv_example_grid.h
#include "lv_example_grid.h"

//The original function is: lv_example_grid_1.
void safe_lv_example_grid_1(void);

//The original function is: lv_example_grid_2.
void safe_lv_example_grid_2(void);

//The original function is: lv_example_grid_3.
void safe_lv_example_grid_3(void);

//The original function is: lv_example_grid_4.
void safe_lv_example_grid_4(void);

//The original function is: lv_example_grid_5.
void safe_lv_example_grid_5(void);

//The original function is: lv_example_grid_6.
void safe_lv_example_grid_6(void);

