//This file is automatically generated.
//The original file is lv_example_ffmpeg.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_ffmpeg.h"

//The original function is: lv_example_ffmpeg_1.
void safe_lv_example_ffmpeg_1(void)
{
    GhostLV_Lock();
    lv_example_ffmpeg_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_ffmpeg_2.
void safe_lv_example_ffmpeg_2(void)
{
    GhostLV_Lock();
    lv_example_ffmpeg_2();
    GhostLV_Unlock();
}

