//This file is automatically generated.
//The original file is lv_tabview.h
#include "lvgl.h"

//The original function is: lv_tabview_create.
lv_obj_t * safe_lv_tabview_create(lv_obj_t * parent, lv_dir_t tab_pos, lv_coord_t tab_size);

//The original function is: lv_tabview_add_tab.
lv_obj_t * safe_lv_tabview_add_tab(lv_obj_t * tv, const char * name);

//The original function is: lv_tabview_get_content.
lv_obj_t * safe_lv_tabview_get_content(lv_obj_t * tv);

//The original function is: lv_tabview_get_tab_btns.
lv_obj_t * safe_lv_tabview_get_tab_btns(lv_obj_t * tv);

//The original function is: lv_tabview_get_tab_act.
uint16_t safe_lv_tabview_get_tab_act(lv_obj_t * tv);

