//This file is automatically generated.
//The original file is lv_tabview.h
#include "GhostSafeLVGL.h"
#include "safe_lv_tabview.h"

//The original function is: lv_tabview_create.
lv_obj_t * safe_lv_tabview_create(lv_obj_t * parent, lv_dir_t tab_pos, lv_coord_t tab_size)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tabview_create(parent, tab_pos, tab_size);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tabview_add_tab.
lv_obj_t * safe_lv_tabview_add_tab(lv_obj_t * tv, const char * name)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tabview_add_tab(tv, name);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tabview_get_content.
lv_obj_t * safe_lv_tabview_get_content(lv_obj_t * tv)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tabview_get_content(tv);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tabview_get_tab_btns.
lv_obj_t * safe_lv_tabview_get_tab_btns(lv_obj_t * tv)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_tabview_get_tab_btns(tv);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tabview_get_tab_act.
uint16_t safe_lv_tabview_get_tab_act(lv_obj_t * tv)
{
    GhostLV_Lock();
    uint16_t ret = lv_tabview_get_tab_act(tv);
    GhostLV_Unlock();
    return ret;
}

