//This file is automatically generated.
//The original file is lv_theme_mono.h
#include "lv_theme_mono.h"

//The original function is: lv_theme_mono_init.
lv_theme_t * safe_lv_theme_mono_init(lv_disp_t * disp, bool dark_bg, const lv_font_t * font);

//The original function is: lv_theme_mono_is_inited.
bool safe_lv_theme_mono_is_inited(void);

