//This file is automatically generated.
//The original file is lv_theme_mono.h
#include "GhostSafeLVGL.h"
#include "safe_lv_theme_mono.h"

//The original function is: lv_theme_mono_init.
lv_theme_t * safe_lv_theme_mono_init(lv_disp_t * disp, bool dark_bg, const lv_font_t * font)
{
    GhostLV_Lock();
    lv_theme_t * ret = lv_theme_mono_init(disp, dark_bg, font);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_mono_is_inited.
bool safe_lv_theme_mono_is_inited(void)
{
    GhostLV_Lock();
    bool ret = lv_theme_mono_is_inited();
    GhostLV_Unlock();
    return ret;
}

