//This file is automatically generated.
//The original file is lv_draw_sw_dither.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sw_dither.h"

//The original function is: lv_dither_none.
LV_ATTRIBUTE_FAST_MEM void safe_lv_dither_none(struct _lv_gradient_cache_t * grad, lv_coord_t x, lv_coord_t y, lv_coord_t w)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM void ret = lv_dither_none(grad, x, y, w);
    GhostLV_Unlock();
    return ret;
}

