//This file is automatically generated.
//The original file is lv_draw_sw_gradient.h
#include "lv_draw_sw_gradient.h"

//The original function is: lv_gradient_set_cache_size.
void safe_lv_gradient_set_cache_size(size_t max_bytes);

//The original function is: lv_gradient_free_cache.
void safe_lv_gradient_free_cache(void);

//The original function is: lv_gradient_get.
lv_grad_t * safe_lv_gradient_get(const lv_grad_dsc_t * gradient, lv_coord_t w, lv_coord_t h);

//The original function is: lv_gradient_cleanup.
void safe_lv_gradient_cleanup(lv_grad_t * grad);

