//This file is automatically generated.
//The original file is lv_draw_sw_gradient.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sw_gradient.h"

//The original function is: lv_gradient_set_cache_size.
void safe_lv_gradient_set_cache_size(size_t max_bytes)
{
    GhostLV_Lock();
    lv_gradient_set_cache_size(max_bytes);
    GhostLV_Unlock();
}

//The original function is: lv_gradient_free_cache.
void safe_lv_gradient_free_cache(void)
{
    GhostLV_Lock();
    lv_gradient_free_cache();
    GhostLV_Unlock();
}

//The original function is: lv_gradient_get.
lv_grad_t * safe_lv_gradient_get(const lv_grad_dsc_t * gradient, lv_coord_t w, lv_coord_t h)
{
    GhostLV_Lock();
    lv_grad_t * ret = lv_gradient_get(gradient, w, h);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_gradient_cleanup.
void safe_lv_gradient_cleanup(lv_grad_t * grad)
{
    GhostLV_Lock();
    lv_gradient_cleanup(grad);
    GhostLV_Unlock();
}

