//This file is automatically generated.
//The original file is lv_draw_sw_blend.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sw_blend.h"

//The original function is: lv_draw_sw_blend.
void safe_lv_draw_sw_blend(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_sw_blend_dsc_t * dsc)
{
    GhostLV_Lock();
    lv_draw_sw_blend(draw_ctx, dsc);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sw_blend_basic.
LV_ATTRIBUTE_FAST_MEM void safe_lv_draw_sw_blend_basic(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_sw_blend_dsc_t * dsc)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM void ret = lv_draw_sw_blend_basic(draw_ctx, dsc);
    GhostLV_Unlock();
    return ret;
}

