//This file is automatically generated.
//The original file is lv_draw_sw.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_sw.h"

//The original function is: lv_draw_sw_init_ctx.
void safe_lv_draw_sw_init_ctx(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx)
{
    GhostLV_Lock();
    lv_draw_sw_init_ctx(drv, draw_ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sw_deinit_ctx.
void safe_lv_draw_sw_deinit_ctx(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx)
{
    GhostLV_Lock();
    lv_draw_sw_deinit_ctx(drv, draw_ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sw_wait_for_finish.
void safe_lv_draw_sw_wait_for_finish(lv_draw_ctx_t * draw_ctx)
{
    GhostLV_Lock();
    lv_draw_sw_wait_for_finish(draw_ctx);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sw_rect.
void safe_lv_draw_sw_rect(lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * dsc, const lv_area_t * coords)
{
    GhostLV_Lock();
    lv_draw_sw_rect(draw_ctx, dsc, coords);
    GhostLV_Unlock();
}

//The original function is: lv_draw_sw_bg.
void safe_lv_draw_sw_bg(lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * dsc, const lv_area_t * coords)
{
    GhostLV_Lock();
    lv_draw_sw_bg(draw_ctx, dsc, coords);
    GhostLV_Unlock();
}

