//This file is automatically generated.
//The original file is lv_msgbox.h
#include "lvgl.h"

//The original function is: lv_msgbox_get_title.
lv_obj_t * safe_lv_msgbox_get_title(lv_obj_t * obj);

//The original function is: lv_msgbox_get_close_btn.
lv_obj_t * safe_lv_msgbox_get_close_btn(lv_obj_t * obj);

//The original function is: lv_msgbox_get_text.
lv_obj_t * safe_lv_msgbox_get_text(lv_obj_t * obj);

//The original function is: lv_msgbox_get_content.
lv_obj_t * safe_lv_msgbox_get_content(lv_obj_t * obj);

//The original function is: lv_msgbox_get_btns.
lv_obj_t * safe_lv_msgbox_get_btns(lv_obj_t * obj);

//The original function is: lv_msgbox_get_active_btn.
uint16_t safe_lv_msgbox_get_active_btn(lv_obj_t * mbox);

//The original function is: lv_msgbox_get_active_btn_text.
const char * safe_lv_msgbox_get_active_btn_text(lv_obj_t * mbox);

//The original function is: lv_msgbox_close.
void safe_lv_msgbox_close(lv_obj_t * mbox);

//The original function is: lv_msgbox_close_async.
void safe_lv_msgbox_close_async(lv_obj_t * mbox);

