//This file is automatically generated.
//The original file is lv_gpu_stm32_dma2d.h
#include "lv_gpu_stm32_dma2d.h"

//The original function is: lv_draw_stm32_dma2d_init.
void safe_lv_draw_stm32_dma2d_init(void);

//The original function is: lv_draw_stm32_dma2d_ctx_init.
void safe_lv_draw_stm32_dma2d_ctx_init(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_draw_stm32_dma2d_ctx_deinit.
void safe_lv_draw_stm32_dma2d_ctx_deinit(struct _lv_disp_drv_t * drv, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_draw_stm32_dma2d_blend.
void safe_lv_draw_stm32_dma2d_blend(lv_draw_ctx_t * draw_ctx, const lv_draw_sw_blend_dsc_t * dsc);

//The original function is: lv_gpu_stm32_dma2d_wait_cb.
void safe_lv_gpu_stm32_dma2d_wait_cb(lv_draw_ctx_t * draw_ctx);

