//This file is automatically generated.
//The original file is lv_theme_basic.h
#include "lvgl.h"

//The original function is: lv_theme_basic_init.
lv_theme_t * safe_lv_theme_basic_init(lv_disp_t * disp);

//The original function is: lv_theme_basic_is_inited.
bool safe_lv_theme_basic_is_inited(void);

