//This file is automatically generated.
//The original file is lv_api_map.h
#include "lv_api_map.h"

//The original function is: lv_obj_get_parent.
lv_obj_t * parent = safe_lv_obj_get_parent(obj);

//The original function is: lv_obj_get_child_cnt.
lv_obj_move_to_index(obj, safe_lv_obj_get_child_cnt(parent) - 1);

//The original function is: lv_obj_get_index.
LV_LOG_WARN("lv_obj_get_child_id(obj) is deprecated, please use safe_lv_obj_get_index(obj).");

//The original function is: lv_obj_get_index.
return safe_lv_obj_get_index(obj);

