//This file is automatically generated.
//The original file is lv_animimg.h
#include "lv_animimg.h"

//The original function is: lv_animimg_create.
lv_obj_t * safe_lv_animimg_create(lv_obj_t * parent);

//The original function is: lv_animimg_set_src.
void safe_lv_animimg_set_src(lv_obj_t * img,  lv_img_dsc_t * dsc[], uint8_t num);

//The original function is: lv_animimg_start.
void safe_lv_animimg_start(lv_obj_t * obj);

//The original function is: lv_animimg_set_duration.
void safe_lv_animimg_set_duration(lv_obj_t * img, uint32_t duration);

//The original function is: lv_animimg_set_repeat_count.
void safe_lv_animimg_set_repeat_count(lv_obj_t * img, uint16_t count);

