//This file is automatically generated.
//The original file is lv_animimg.h
#include "lvgl.h"

//The original function is: lv_animimg_create.
lv_obj_t * safe_lv_animimg_create(lv_obj_t * parent);

//The original function is: lv_animimg_start.
void safe_lv_animimg_start(lv_obj_t * obj);

