//This file is automatically generated.
//The original file is lv_animimg.h
#include "GhostSafeLVGL.h"
#include "safe_lv_animimg.h"

//The original function is: lv_animimg_create.
lv_obj_t * safe_lv_animimg_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_animimg_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_animimg_start.
void safe_lv_animimg_start(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_animimg_start(obj);
    GhostLV_Unlock();
}

