//This file is automatically generated.
//The original file is lv_win.h
#include "GhostSafeLVGL.h"
#include "safe_lv_win.h"

//The original function is: lv_win_create.
lv_obj_t * safe_lv_win_create(lv_obj_t * parent, lv_coord_t header_height)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_win_create(parent, header_height);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_win_add_title.
lv_obj_t * safe_lv_win_add_title(lv_obj_t * win, const char * txt)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_win_add_title(win, txt);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_win_add_btn.
lv_obj_t * safe_lv_win_add_btn(lv_obj_t * win, const void * icon, lv_coord_t btn_w)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_win_add_btn(win, icon, btn_w);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_win_get_header.
lv_obj_t * safe_lv_win_get_header(lv_obj_t * win)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_win_get_header(win);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_win_get_content.
lv_obj_t * safe_lv_win_get_content(lv_obj_t * win)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_win_get_content(win);
    GhostLV_Unlock();
    return ret;
}

