//This file is automatically generated.
//The original file is lv_win.h
#include "lv_win.h"

//The original function is: lv_win_create.
lv_obj_t * safe_lv_win_create(lv_obj_t * parent, lv_coord_t header_height);

//The original function is: lv_win_add_title.
lv_obj_t * safe_lv_win_add_title(lv_obj_t * win, const char * txt);

//The original function is: lv_win_add_btn.
lv_obj_t * safe_lv_win_add_btn(lv_obj_t * win, const void * icon, lv_coord_t btn_w);

//The original function is: lv_win_get_header.
lv_obj_t * safe_lv_win_get_header(lv_obj_t * win);

//The original function is: lv_win_get_content.
lv_obj_t * safe_lv_win_get_content(lv_obj_t * win);

