//This file is automatically generated.
//The original file is lv_example_flex.h
#include "lv_example_flex.h"

//The original function is: lv_example_flex_1.
void safe_lv_example_flex_1(void);

//The original function is: lv_example_flex_2.
void safe_lv_example_flex_2(void);

//The original function is: lv_example_flex_3.
void safe_lv_example_flex_3(void);

//The original function is: lv_example_flex_4.
void safe_lv_example_flex_4(void);

//The original function is: lv_example_flex_5.
void safe_lv_example_flex_5(void);

//The original function is: lv_example_flex_6.
void safe_lv_example_flex_6(void);

