//This file is automatically generated.
//The original file is lv_example_flex.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_flex.h"

//The original function is: lv_example_flex_1.
void safe_lv_example_flex_1(void)
{
    GhostLV_Lock();
    lv_example_flex_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_flex_2.
void safe_lv_example_flex_2(void)
{
    GhostLV_Lock();
    lv_example_flex_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_flex_3.
void safe_lv_example_flex_3(void)
{
    GhostLV_Lock();
    lv_example_flex_3();
    GhostLV_Unlock();
}

//The original function is: lv_example_flex_4.
void safe_lv_example_flex_4(void)
{
    GhostLV_Lock();
    lv_example_flex_4();
    GhostLV_Unlock();
}

//The original function is: lv_example_flex_5.
void safe_lv_example_flex_5(void)
{
    GhostLV_Lock();
    lv_example_flex_5();
    GhostLV_Unlock();
}

//The original function is: lv_example_flex_6.
void safe_lv_example_flex_6(void)
{
    GhostLV_Lock();
    lv_example_flex_6();
    GhostLV_Unlock();
}

