//This file is automatically generated.
//The original file is lv_img_cache.h
#include "GhostSafeLVGL.h"
#include "safe_lv_img_cache.h"

//The original function is: lv_img_cache_invalidate_src.
void safe_lv_img_cache_invalidate_src(const void * src)
{
    GhostLV_Lock();
    lv_img_cache_invalidate_src(src);
    GhostLV_Unlock();
}

