//This file is automatically generated.
//The original file is lv_img_cache.h
#include "lv_img_cache.h"

//The original function is: lv_img_cache_set_size.
void safe_lv_img_cache_set_size(uint16_t new_slot_num);

//The original function is: lv_img_cache_invalidate_src.
void safe_lv_img_cache_invalidate_src(const void * src);

