//This file is automatically generated.
//The original file is lv_draw_img.h
#include "lv_draw_img.h"

//The original function is: lv_draw_img_dsc_init.
void safe_lv_draw_img_dsc_init(lv_draw_img_dsc_t * dsc);

//The original function is: lv_img_src_get_type.
lv_img_src_t safe_lv_img_src_get_type(const void * src);

//The original function is: lv_img_cf_get_px_size.
uint8_t safe_lv_img_cf_get_px_size(lv_img_cf_t cf);

//The original function is: lv_img_cf_is_chroma_keyed.
bool safe_lv_img_cf_is_chroma_keyed(lv_img_cf_t cf);

//The original function is: lv_img_cf_has_alpha.
bool safe_lv_img_cf_has_alpha(lv_img_cf_t cf);

