//This file is automatically generated.
//The original file is lv_draw_mask.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_mask.h"

//The original function is: lv_draw_mask_add.
int16_t safe_lv_draw_mask_add(void * param, void * custom_id)
{
    GhostLV_Lock();
    int16_t ret = lv_draw_mask_add(param, custom_id);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_mask_remove_id.
void * safe_lv_draw_mask_remove_id(int16_t id)
{
    GhostLV_Lock();
    void * ret = lv_draw_mask_remove_id(id);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_mask_remove_custom.
void * safe_lv_draw_mask_remove_custom(void * custom_id)
{
    GhostLV_Lock();
    void * ret = lv_draw_mask_remove_custom(custom_id);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_mask_free_param.
void safe_lv_draw_mask_free_param(void * p)
{
    GhostLV_Lock();
    lv_draw_mask_free_param(p);
    GhostLV_Unlock();
}

//The original function is: lv_draw_mask_get_cnt.
LV_ATTRIBUTE_FAST_MEM uint8_t safe_lv_draw_mask_get_cnt(void)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM uint8_t ret = lv_draw_mask_get_cnt();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_mask_is_any.
bool safe_lv_draw_mask_is_any(const lv_area_t * a)
{
    GhostLV_Lock();
    bool ret = lv_draw_mask_is_any(a);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_mask_radius_init.
void safe_lv_draw_mask_radius_init(lv_draw_mask_radius_param_t * param, const lv_area_t * rect, lv_coord_t radius, bool inv)
{
    GhostLV_Lock();
    lv_draw_mask_radius_init(param, rect, radius, inv);
    GhostLV_Unlock();
}

//The original function is: lv_draw_mask_map_init.
void safe_lv_draw_mask_map_init(lv_draw_mask_map_param_t * param, const lv_area_t * coords, const lv_opa_t * map)
{
    GhostLV_Lock();
    lv_draw_mask_map_init(param, coords, map);
    GhostLV_Unlock();
}

//The original function is: lv_draw_mask_polygon_init.
void safe_lv_draw_mask_polygon_init(lv_draw_mask_polygon_param_t * param, const lv_point_t * points, uint16_t point_cnt)
{
    GhostLV_Lock();
    lv_draw_mask_polygon_init(param, points, point_cnt);
    GhostLV_Unlock();
}

