//This file is automatically generated.
//The original file is lv_draw.h
#include "lvgl.h"

//The original function is: lv_draw_init.
void safe_lv_draw_init(void);

//The original function is: lv_draw_wait_for_finish.
void safe_lv_draw_wait_for_finish(lv_draw_ctx_t * draw_ctx);

