//This file is automatically generated.
//The original file is lv_draw_layer.h
#include "lvgl.h"

//The original function is: lv_draw_layer_destroy.
void safe_lv_draw_layer_destroy(struct _lv_draw_ctx_t * draw_ctx, struct _lv_draw_layer_ctx_t * layer_ctx);

