//This file is automatically generated.
//The original file is lv_draw_img.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_img.h"

//The original function is: lv_draw_img_dsc_init.
void safe_lv_draw_img_dsc_init(lv_draw_img_dsc_t * dsc)
{
    GhostLV_Lock();
    lv_draw_img_dsc_init(dsc);
    GhostLV_Unlock();
}

//The original function is: lv_img_src_get_type.
lv_img_src_t safe_lv_img_src_get_type(const void * src)
{
    GhostLV_Lock();
    lv_img_src_t ret = lv_img_src_get_type(src);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_img_cf_get_px_size.
uint8_t safe_lv_img_cf_get_px_size(lv_img_cf_t cf)
{
    GhostLV_Lock();
    uint8_t ret = lv_img_cf_get_px_size(cf);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_img_cf_is_chroma_keyed.
bool safe_lv_img_cf_is_chroma_keyed(lv_img_cf_t cf)
{
    GhostLV_Lock();
    bool ret = lv_img_cf_is_chroma_keyed(cf);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_img_cf_has_alpha.
bool safe_lv_img_cf_has_alpha(lv_img_cf_t cf)
{
    GhostLV_Lock();
    bool ret = lv_img_cf_has_alpha(cf);
    GhostLV_Unlock();
    return ret;
}

