//This file is automatically generated.
//The original file is lv_draw_label.h
#include "lvgl.h"

//The original function is: lv_draw_label_dsc_init.
void safe_lv_draw_label_dsc_init(lv_draw_label_dsc_t * dsc);

