//This file is automatically generated.
//The original file is lv_img_buf.h
#include "lv_img_buf.h"

//The original function is: lv_img_buf_alloc.
lv_img_dsc_t * safe_lv_img_buf_alloc(lv_coord_t w, lv_coord_t h, lv_img_cf_t cf);

//The original function is: lv_img_buf_get_px_color.
lv_color_t safe_lv_img_buf_get_px_color(lv_img_dsc_t * dsc, lv_coord_t x, lv_coord_t y, lv_color_t color);

//The original function is: lv_img_buf_get_px_alpha.
lv_opa_t safe_lv_img_buf_get_px_alpha(lv_img_dsc_t * dsc, lv_coord_t x, lv_coord_t y);

//The original function is: lv_img_buf_set_px_color.
void safe_lv_img_buf_set_px_color(lv_img_dsc_t * dsc, lv_coord_t x, lv_coord_t y, lv_color_t c);

//The original function is: lv_img_buf_set_px_alpha.
void safe_lv_img_buf_set_px_alpha(lv_img_dsc_t * dsc, lv_coord_t x, lv_coord_t y, lv_opa_t opa);

//The original function is: lv_img_buf_set_palette.
void safe_lv_img_buf_set_palette(lv_img_dsc_t * dsc, uint8_t id, lv_color_t c);

//The original function is: lv_img_buf_free.
void safe_lv_img_buf_free(lv_img_dsc_t * dsc);

//The original function is: lv_img_buf_get_img_size.
uint32_t safe_lv_img_buf_get_img_size(lv_coord_t w, lv_coord_t h, lv_img_cf_t cf);

