//This file is automatically generated.
//The original file is lv_draw.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw.h"

//The original function is: lv_draw_init.
void safe_lv_draw_init(void)
{
    GhostLV_Lock();
    lv_draw_init();
    GhostLV_Unlock();
}

