//This file is automatically generated.
//The original file is lv_draw_label.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_label.h"

//The original function is: lv_draw_label_dsc_init.
LV_ATTRIBUTE_FAST_MEM void safe_lv_draw_label_dsc_init(lv_draw_label_dsc_t * dsc)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM void ret = lv_draw_label_dsc_init(dsc);
    GhostLV_Unlock();
    return ret;
}

