//This file is automatically generated.
//The original file is lv_draw_arc.h
#include "lv_draw_arc.h"

//The original function is: lv_draw_arc_dsc_init.
void safe_lv_draw_arc_dsc_init(lv_draw_arc_dsc_t * dsc);

