//This file is automatically generated.
//The original file is lv_draw_line.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_line.h"

//The original function is: lv_draw_line_dsc_init.
void safe_lv_draw_line_dsc_init(lv_draw_line_dsc_t * dsc)
{
    GhostLV_Lock();
    lv_draw_line_dsc_init(dsc);
    GhostLV_Unlock();
}

