//This file is automatically generated.
//The original file is lv_draw_line.h
#include "lv_draw_line.h"

//The original function is: lv_draw_line_dsc_init.
LV_ATTRIBUTE_FAST_MEM void safe_lv_draw_line_dsc_init(lv_draw_line_dsc_t * dsc);

