//This file is automatically generated.
//The original file is lv_draw_rect.h
#include "lvgl.h"

//The original function is: lv_draw_rect_dsc_init.
void safe_lv_draw_rect_dsc_init(lv_draw_rect_dsc_t * dsc);

//The original function is: lv_draw_rect.
void safe_lv_draw_rect(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * dsc, const lv_area_t * coords);

