//This file is automatically generated.
//The original file is lv_draw_rect.h
#include "GhostSafeLVGL.h"
#include "safe_lv_draw_rect.h"

//The original function is: lv_draw_rect_dsc_init.
LV_ATTRIBUTE_FAST_MEM void safe_lv_draw_rect_dsc_init(lv_draw_rect_dsc_t * dsc)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM void ret = lv_draw_rect_dsc_init(dsc);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_draw_rect.
void safe_lv_draw_rect(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * dsc, const lv_area_t * coords)
{
    GhostLV_Lock();
    lv_draw_rect(draw_ctx, dsc, coords);
    GhostLV_Unlock();
}

