//This file is automatically generated.
//The original file is lv_draw_mask.h
#include "lvgl.h"

//The original function is: lv_draw_mask_add.
int16_t safe_lv_draw_mask_add(void * param, void * custom_id);

//The original function is: lv_draw_mask_remove_custom.
void * safe_lv_draw_mask_remove_custom(void * custom_id);

//The original function is: lv_draw_mask_free_param.
void safe_lv_draw_mask_free_param(void * p);

//The original function is: lv_draw_mask_get_cnt.
LV_ATTRIBUTE_FAST_MEM uint8_t safe_lv_draw_mask_get_cnt(void);

//The original function is: lv_draw_mask_is_any.
bool safe_lv_draw_mask_is_any(const lv_area_t * a);

//The original function is: lv_draw_mask_radius_init.
void safe_lv_draw_mask_radius_init(lv_draw_mask_radius_param_t * param, const lv_area_t * rect, lv_coord_t radius, bool inv);

//The original function is: lv_draw_mask_map_init.
void safe_lv_draw_mask_map_init(lv_draw_mask_map_param_t * param, const lv_area_t * coords, const lv_opa_t * map);

