//This file is automatically generated.
//The original file is lv_gif.h
#include "lvgl.h"

//The original function is: lv_gif_create.
lv_obj_t * safe_lv_gif_create(lv_obj_t * parent);

//The original function is: lv_gif_set_src.
void safe_lv_gif_set_src(lv_obj_t * obj, const void * src);

//The original function is: lv_gif_restart.
void safe_lv_gif_restart(lv_obj_t * gif);

