//This file is automatically generated.
//The original file is lv_gif.h
#include "GhostSafeLVGL.h"
#include "safe_lv_gif.h"

//The original function is: lv_gif_create.
lv_obj_t * safe_lv_gif_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_gif_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_gif_set_src.
void safe_lv_gif_set_src(lv_obj_t * obj, const void * src)
{
    GhostLV_Lock();
    lv_gif_set_src(obj, src);
    GhostLV_Unlock();
}

//The original function is: lv_gif_restart.
void safe_lv_gif_restart(lv_obj_t * gif)
{
    GhostLV_Lock();
    lv_gif_restart(gif);
    GhostLV_Unlock();
}

