//This file is automatically generated.
//The original file is lv_grid.h
#include "lvgl.h"

//The original function is: lv_grid_init.
void safe_lv_grid_init(void);

//The original function is: lv_obj_set_grid_align.
void safe_lv_obj_set_grid_align(lv_obj_t * obj, lv_grid_align_t column_align, lv_grid_align_t row_align);

//The original function is: lv_style_set_grid_row_align.
void safe_lv_style_set_grid_row_align(lv_style_t * style, lv_grid_align_t value);

//The original function is: lv_style_set_grid_column_align.
void safe_lv_style_set_grid_column_align(lv_style_t * style, lv_grid_align_t value);

//The original function is: lv_style_set_grid_cell_column_pos.
void safe_lv_style_set_grid_cell_column_pos(lv_style_t * style, lv_coord_t value);

//The original function is: lv_style_set_grid_cell_column_span.
void safe_lv_style_set_grid_cell_column_span(lv_style_t * style, lv_coord_t value);

//The original function is: lv_style_set_grid_cell_row_pos.
void safe_lv_style_set_grid_cell_row_pos(lv_style_t * style, lv_coord_t value);

//The original function is: lv_style_set_grid_cell_row_span.
void safe_lv_style_set_grid_cell_row_span(lv_style_t * style, lv_coord_t value);

//The original function is: lv_style_set_grid_cell_x_align.
void safe_lv_style_set_grid_cell_x_align(lv_style_t * style, lv_coord_t value);

//The original function is: lv_style_set_grid_cell_y_align.
void safe_lv_style_set_grid_cell_y_align(lv_style_t * style, lv_coord_t value);

//The original function is: lv_obj_set_style_grid_row_align.
void safe_lv_obj_set_style_grid_row_align(lv_obj_t * obj, lv_grid_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_column_align.
void safe_lv_obj_set_style_grid_column_align(lv_obj_t * obj, lv_grid_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_column_pos.
void safe_lv_obj_set_style_grid_cell_column_pos(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_column_span.
void safe_lv_obj_set_style_grid_cell_column_span(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_row_pos.
void safe_lv_obj_set_style_grid_cell_row_pos(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_row_span.
void safe_lv_obj_set_style_grid_cell_row_span(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_x_align.
void safe_lv_obj_set_style_grid_cell_x_align(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_grid_cell_y_align.
void safe_lv_obj_set_style_grid_cell_y_align(lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

