//This file is automatically generated.
//The original file is lv_obj_tree.h
#include "GhostSafeLVGL.h"
#include "safe_lv_obj_tree.h"

//The original function is: lv_obj_tree_walk_res_t (*lv_obj_tree_walk_cb_t).
typedef safe_lv_obj_tree_walk_res_t (*lv_obj_tree_walk_cb_t)(struct _lv_obj_t *, void *)
{
    GhostLV_Lock();
    typedef ret = lv_obj_tree_walk_res_t (*lv_obj_tree_walk_cb_t)(*, *);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_del.
void safe_lv_obj_del(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_del(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_clean.
void safe_lv_obj_clean(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_clean(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_del_delayed.
void safe_lv_obj_del_delayed(struct _lv_obj_t * obj, uint32_t delay_ms)
{
    GhostLV_Lock();
    lv_obj_del_delayed(obj, delay_ms);
    GhostLV_Unlock();
}

//The original function is: lv_obj_del_anim_ready_cb.
void safe_lv_obj_del_anim_ready_cb(lv_anim_t * a)
{
    GhostLV_Lock();
    lv_obj_del_anim_ready_cb(a);
    GhostLV_Unlock();
}

//The original function is: lv_obj_del_async.
void safe_lv_obj_del_async(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_del_async(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_parent.
void safe_lv_obj_set_parent(struct _lv_obj_t * obj, struct _lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_set_parent(obj, parent);
    GhostLV_Unlock();
}

//The original function is: lv_obj_swap.
void safe_lv_obj_swap(struct _lv_obj_t * obj1, struct _lv_obj_t * obj2)
{
    GhostLV_Lock();
    lv_obj_swap(obj1, obj2);
    GhostLV_Unlock();
}

//The original function is: lv_obj_move_to_index.
void safe_lv_obj_move_to_index(struct _lv_obj_t * obj, int32_t index)
{
    GhostLV_Lock();
    lv_obj_move_to_index(obj, index);
    GhostLV_Unlock();
}

//The original function is: lv_obj_get_screen.
struct _lv_obj_t * safe_lv_obj_get_screen(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    struct _lv_obj_t * ret = lv_obj_get_screen(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_disp.
lv_disp_t * safe_lv_obj_get_disp(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_disp_t * ret = lv_obj_get_disp(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_parent.
struct _lv_obj_t * safe_lv_obj_get_parent(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    struct _lv_obj_t * ret = lv_obj_get_parent(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_child.
struct _lv_obj_t * safe_lv_obj_get_child(const struct _lv_obj_t * obj, int32_t id)
{
    GhostLV_Lock();
    struct _lv_obj_t * ret = lv_obj_get_child(obj, id);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_child_cnt.
uint32_t safe_lv_obj_get_child_cnt(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    uint32_t ret = lv_obj_get_child_cnt(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_index.
uint32_t safe_lv_obj_get_index(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    uint32_t ret = lv_obj_get_index(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_tree_walk.
void safe_lv_obj_tree_walk(struct _lv_obj_t * start_obj, lv_obj_tree_walk_cb_t cb, void * user_data)
{
    GhostLV_Lock();
    lv_obj_tree_walk(start_obj, cb, user_data);
    GhostLV_Unlock();
}

