//This file is automatically generated.
//The original file is lv_theme.h
#include "GhostSafeLVGL.h"
#include "safe_lv_theme.h"

//The original function is: lv_theme_get_from_obj.
lv_theme_t  * safe_lv_theme_get_from_obj(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_theme_t  * ret = lv_theme_get_from_obj(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_apply.
void safe_lv_theme_apply(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_theme_apply(obj);
    GhostLV_Unlock();
}

//The original function is: lv_theme_set_parent.
void safe_lv_theme_set_parent(lv_theme_t * new_theme, lv_theme_t * parent)
{
    GhostLV_Lock();
    lv_theme_set_parent(new_theme, parent);
    GhostLV_Unlock();
}

//The original function is: lv_theme_set_apply_cb.
void safe_lv_theme_set_apply_cb(lv_theme_t * theme, lv_theme_apply_cb_t apply_cb)
{
    GhostLV_Lock();
    lv_theme_set_apply_cb(theme, apply_cb);
    GhostLV_Unlock();
}

//The original function is: lv_theme_get_font_small.
const lv_font_t * safe_lv_theme_get_font_small(lv_obj_t * obj)
{
    GhostLV_Lock();
    const lv_font_t * ret = lv_theme_get_font_small(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_get_font_normal.
const lv_font_t * safe_lv_theme_get_font_normal(lv_obj_t * obj)
{
    GhostLV_Lock();
    const lv_font_t * ret = lv_theme_get_font_normal(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_get_font_large.
const lv_font_t * safe_lv_theme_get_font_large(lv_obj_t * obj)
{
    GhostLV_Lock();
    const lv_font_t * ret = lv_theme_get_font_large(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_get_color_primary.
lv_color_t safe_lv_theme_get_color_primary(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_color_t ret = lv_theme_get_color_primary(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_get_color_secondary.
lv_color_t safe_lv_theme_get_color_secondary(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_color_t ret = lv_theme_get_color_secondary(obj);
    GhostLV_Unlock();
    return ret;
}

