//This file is automatically generated.
//The original file is lv_refr.h
#include "GhostSafeLVGL.h"
#include "safe_lv_refr.h"

//The original function is: lv_refr_now.
void safe_lv_refr_now(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_refr_now(disp);
    GhostLV_Unlock();
}

//The original function is: lv_obj_redraw.
void safe_lv_obj_redraw(lv_draw_ctx_t * draw_ctx, lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_redraw(draw_ctx, obj);
    GhostLV_Unlock();
}

//The original function is: lv_refr_reset_fps_counter.
void safe_lv_refr_reset_fps_counter(void)
{
    GhostLV_Lock();
    lv_refr_reset_fps_counter();
    GhostLV_Unlock();
}

//The original function is: lv_refr_get_fps_avg.
uint32_t safe_lv_refr_get_fps_avg(void)
{
    GhostLV_Lock();
    uint32_t ret = lv_refr_get_fps_avg();
    GhostLV_Unlock();
    return ret;
}

