//This file is automatically generated.
//The original file is lv_indev_scroll.h
#include "GhostSafeLVGL.h"
#include "safe_lv_indev_scroll.h"

//The original function is: lv_indev_scroll_throw_predict.
lv_coord_t safe_lv_indev_scroll_throw_predict(lv_indev_t * indev, lv_dir_t dir)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_indev_scroll_throw_predict(indev, dir);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_indev_scroll_get_snap_dist.
void safe_lv_indev_scroll_get_snap_dist(lv_obj_t * obj, lv_point_t * p)
{
    GhostLV_Lock();
    lv_indev_scroll_get_snap_dist(obj, p);
    GhostLV_Unlock();
}

