//This file is automatically generated.
//The original file is lv_obj_style_gen.h
#include "lvgl.h"

//The original function is: lv_obj_set_style_width.
void safe_lv_obj_set_style_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_min_width.
void safe_lv_obj_set_style_min_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_max_width.
void safe_lv_obj_set_style_max_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_height.
void safe_lv_obj_set_style_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_min_height.
void safe_lv_obj_set_style_min_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_max_height.
void safe_lv_obj_set_style_max_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_x.
void safe_lv_obj_set_style_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_y.
void safe_lv_obj_set_style_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_align.
void safe_lv_obj_set_style_align(struct _lv_obj_t * obj, lv_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_width.
void safe_lv_obj_set_style_transform_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_height.
void safe_lv_obj_set_style_transform_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_translate_x.
void safe_lv_obj_set_style_translate_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_translate_y.
void safe_lv_obj_set_style_translate_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_zoom.
void safe_lv_obj_set_style_transform_zoom(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_angle.
void safe_lv_obj_set_style_transform_angle(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_pivot_x.
void safe_lv_obj_set_style_transform_pivot_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transform_pivot_y.
void safe_lv_obj_set_style_transform_pivot_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_top.
void safe_lv_obj_set_style_pad_top(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_bottom.
void safe_lv_obj_set_style_pad_bottom(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_left.
void safe_lv_obj_set_style_pad_left(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_right.
void safe_lv_obj_set_style_pad_right(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_row.
void safe_lv_obj_set_style_pad_row(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_pad_column.
void safe_lv_obj_set_style_pad_column(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_color.
void safe_lv_obj_set_style_bg_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_opa.
void safe_lv_obj_set_style_bg_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_grad_color.
void safe_lv_obj_set_style_bg_grad_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_grad_dir.
void safe_lv_obj_set_style_bg_grad_dir(struct _lv_obj_t * obj, lv_grad_dir_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_main_stop.
void safe_lv_obj_set_style_bg_main_stop(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_grad_stop.
void safe_lv_obj_set_style_bg_grad_stop(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_grad.
void safe_lv_obj_set_style_bg_grad(struct _lv_obj_t * obj, const lv_grad_dsc_t * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_dither_mode.
void safe_lv_obj_set_style_bg_dither_mode(struct _lv_obj_t * obj, lv_dither_mode_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_img_src.
void safe_lv_obj_set_style_bg_img_src(struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_img_opa.
void safe_lv_obj_set_style_bg_img_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_img_recolor.
void safe_lv_obj_set_style_bg_img_recolor(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_img_recolor_opa.
void safe_lv_obj_set_style_bg_img_recolor_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_bg_img_tiled.
void safe_lv_obj_set_style_bg_img_tiled(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_border_color.
void safe_lv_obj_set_style_border_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_border_opa.
void safe_lv_obj_set_style_border_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_border_width.
void safe_lv_obj_set_style_border_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_border_side.
void safe_lv_obj_set_style_border_side(struct _lv_obj_t * obj, lv_border_side_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_border_post.
void safe_lv_obj_set_style_border_post(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_outline_width.
void safe_lv_obj_set_style_outline_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_outline_color.
void safe_lv_obj_set_style_outline_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_outline_opa.
void safe_lv_obj_set_style_outline_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_outline_pad.
void safe_lv_obj_set_style_outline_pad(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_width.
void safe_lv_obj_set_style_shadow_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_ofs_x.
void safe_lv_obj_set_style_shadow_ofs_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_ofs_y.
void safe_lv_obj_set_style_shadow_ofs_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_spread.
void safe_lv_obj_set_style_shadow_spread(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_color.
void safe_lv_obj_set_style_shadow_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_shadow_opa.
void safe_lv_obj_set_style_shadow_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_img_opa.
void safe_lv_obj_set_style_img_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_img_recolor.
void safe_lv_obj_set_style_img_recolor(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_img_recolor_opa.
void safe_lv_obj_set_style_img_recolor_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_width.
void safe_lv_obj_set_style_line_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_dash_width.
void safe_lv_obj_set_style_line_dash_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_dash_gap.
void safe_lv_obj_set_style_line_dash_gap(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_rounded.
void safe_lv_obj_set_style_line_rounded(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_color.
void safe_lv_obj_set_style_line_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_line_opa.
void safe_lv_obj_set_style_line_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_arc_width.
void safe_lv_obj_set_style_arc_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_arc_rounded.
void safe_lv_obj_set_style_arc_rounded(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_arc_color.
void safe_lv_obj_set_style_arc_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_arc_opa.
void safe_lv_obj_set_style_arc_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_arc_img_src.
void safe_lv_obj_set_style_arc_img_src(struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_color.
void safe_lv_obj_set_style_text_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_opa.
void safe_lv_obj_set_style_text_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_font.
void safe_lv_obj_set_style_text_font(struct _lv_obj_t * obj, const lv_font_t * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_letter_space.
void safe_lv_obj_set_style_text_letter_space(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_line_space.
void safe_lv_obj_set_style_text_line_space(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_decor.
void safe_lv_obj_set_style_text_decor(struct _lv_obj_t * obj, lv_text_decor_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_text_align.
void safe_lv_obj_set_style_text_align(struct _lv_obj_t * obj, lv_text_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_radius.
void safe_lv_obj_set_style_radius(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_clip_corner.
void safe_lv_obj_set_style_clip_corner(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_opa.
void safe_lv_obj_set_style_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_color_filter_dsc.
void safe_lv_obj_set_style_color_filter_dsc(struct _lv_obj_t * obj, const lv_color_filter_dsc_t * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_color_filter_opa.
void safe_lv_obj_set_style_color_filter_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_anim.
void safe_lv_obj_set_style_anim(struct _lv_obj_t * obj, const lv_anim_t * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_transition.
void safe_lv_obj_set_style_transition(struct _lv_obj_t * obj, const lv_style_transition_dsc_t * value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_blend_mode.
void safe_lv_obj_set_style_blend_mode(struct _lv_obj_t * obj, lv_blend_mode_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_base_dir.
void safe_lv_obj_set_style_base_dir(struct _lv_obj_t * obj, lv_base_dir_t value, lv_style_selector_t selector);

