//This file is automatically generated.
//The original file is lv_theme.h
#include "lvgl.h"

//The original function is: lv_theme_get_from_obj.
lv_theme_t  * safe_lv_theme_get_from_obj(lv_obj_t * obj);

//The original function is: lv_theme_apply.
void safe_lv_theme_apply(lv_obj_t * obj);

//The original function is: lv_theme_set_parent.
void safe_lv_theme_set_parent(lv_theme_t * new_theme, lv_theme_t * parent);

//The original function is: lv_theme_set_apply_cb.
void safe_lv_theme_set_apply_cb(lv_theme_t * theme, lv_theme_apply_cb_t apply_cb);

//The original function is: lv_theme_get_font_small.
const lv_font_t * safe_lv_theme_get_font_small(lv_obj_t * obj);

//The original function is: lv_theme_get_font_normal.
const lv_font_t * safe_lv_theme_get_font_normal(lv_obj_t * obj);

//The original function is: lv_theme_get_font_large.
const lv_font_t * safe_lv_theme_get_font_large(lv_obj_t * obj);

//The original function is: lv_theme_get_color_primary.
lv_color_t safe_lv_theme_get_color_primary(lv_obj_t * obj);

//The original function is: lv_theme_get_color_secondary.
lv_color_t safe_lv_theme_get_color_secondary(lv_obj_t * obj);

