//This file is automatically generated.
//The original file is lv_disp.h
#include "GhostSafeLVGL.h"
#include "safe_lv_disp.h"

//The original function is: lv_disp_get_scr_act.
lv_obj_t * safe_lv_disp_get_scr_act(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_disp_get_scr_act(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_scr_prev.
lv_obj_t * safe_lv_disp_get_scr_prev(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_disp_get_scr_prev(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_load_scr.
void safe_lv_disp_load_scr(lv_obj_t * scr)
{
    GhostLV_Lock();
    lv_disp_load_scr(scr);
    GhostLV_Unlock();
}

//The original function is: lv_disp_get_layer_top.
lv_obj_t * safe_lv_disp_get_layer_top(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_disp_get_layer_top(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_get_layer_sys.
lv_obj_t * safe_lv_disp_get_layer_sys(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_disp_get_layer_sys(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_set_theme.
void safe_lv_disp_set_theme(lv_disp_t * disp, lv_theme_t * th)
{
    GhostLV_Lock();
    lv_disp_set_theme(disp, th);
    GhostLV_Unlock();
}

//The original function is: lv_disp_get_theme.
lv_theme_t * safe_lv_disp_get_theme(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_theme_t * ret = lv_disp_get_theme(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_set_bg_color.
void safe_lv_disp_set_bg_color(lv_disp_t * disp, lv_color_t color)
{
    GhostLV_Lock();
    lv_disp_set_bg_color(disp, color);
    GhostLV_Unlock();
}

//The original function is: lv_disp_set_bg_image.
void safe_lv_disp_set_bg_image(lv_disp_t * disp, const void  * img_src)
{
    GhostLV_Lock();
    lv_disp_set_bg_image(disp, img_src);
    GhostLV_Unlock();
}

//The original function is: lv_disp_set_bg_opa.
void safe_lv_disp_set_bg_opa(lv_disp_t * disp, lv_opa_t opa)
{
    GhostLV_Lock();
    lv_disp_set_bg_opa(disp, opa);
    GhostLV_Unlock();
}

//The original function is: lv_disp_get_inactive_time.
uint32_t safe_lv_disp_get_inactive_time(const lv_disp_t * disp)
{
    GhostLV_Lock();
    uint32_t ret = lv_disp_get_inactive_time(disp);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_disp_trig_activity.
void safe_lv_disp_trig_activity(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_trig_activity(disp);
    GhostLV_Unlock();
}

//The original function is: lv_disp_clean_dcache.
void safe_lv_disp_clean_dcache(lv_disp_t * disp)
{
    GhostLV_Lock();
    lv_disp_clean_dcache(disp);
    GhostLV_Unlock();
}

