//This file is automatically generated.
//The original file is lv_obj_class.h
#include "GhostSafeLVGL.h"
#include "safe_lv_obj_class.h"

//The original function is: lv_obj_class_create_obj.
struct _lv_obj_t * safe_lv_obj_class_create_obj(const struct _lv_obj_class_t * class_p, struct _lv_obj_t * parent)
{
    GhostLV_Lock();
    struct _lv_obj_t * ret = lv_obj_class_create_obj(class_p, parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_class_init_obj.
void safe_lv_obj_class_init_obj(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_class_init_obj(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_is_editable.
bool safe_lv_obj_is_editable(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_is_editable(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_is_group_def.
bool safe_lv_obj_is_group_def(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_is_group_def(obj);
    GhostLV_Unlock();
    return ret;
}

