//This file is automatically generated.
//The original file is lv_obj.h
#include "GhostSafeLVGL.h"
#include "safe_lv_obj.h"

//The original function is: lv_init.
void safe_lv_init(void)
{
    GhostLV_Lock();
    lv_init();
    GhostLV_Unlock();
}

//The original function is: lv_deinit.
void safe_lv_deinit(void)
{
    GhostLV_Lock();
    lv_deinit();
    GhostLV_Unlock();
}

//The original function is: lv_is_initialized.
bool safe_lv_is_initialized(void)
{
    GhostLV_Lock();
    bool ret = lv_is_initialized();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_create.
lv_obj_t * safe_lv_obj_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_obj_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_add_flag.
void safe_lv_obj_add_flag(lv_obj_t * obj, lv_obj_flag_t f)
{
    GhostLV_Lock();
    lv_obj_add_flag(obj, f);
    GhostLV_Unlock();
}

//The original function is: lv_obj_clear_flag.
void safe_lv_obj_clear_flag(lv_obj_t * obj, lv_obj_flag_t f)
{
    GhostLV_Lock();
    lv_obj_clear_flag(obj, f);
    GhostLV_Unlock();
}

//The original function is: lv_obj_add_state.
void safe_lv_obj_add_state(lv_obj_t * obj, lv_state_t state)
{
    GhostLV_Lock();
    lv_obj_add_state(obj, state);
    GhostLV_Unlock();
}

//The original function is: lv_obj_clear_state.
void safe_lv_obj_clear_state(lv_obj_t * obj, lv_state_t state)
{
    GhostLV_Lock();
    lv_obj_clear_state(obj, state);
    GhostLV_Unlock();
}

//The original function is: lv_obj_has_flag.
bool safe_lv_obj_has_flag(const lv_obj_t * obj, lv_obj_flag_t f)
{
    GhostLV_Lock();
    bool ret = lv_obj_has_flag(obj, f);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_has_flag_any.
bool safe_lv_obj_has_flag_any(const lv_obj_t * obj, lv_obj_flag_t f)
{
    GhostLV_Lock();
    bool ret = lv_obj_has_flag_any(obj, f);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_state.
lv_state_t safe_lv_obj_get_state(const lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_state_t ret = lv_obj_get_state(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_has_state.
bool safe_lv_obj_has_state(const lv_obj_t * obj, lv_state_t state)
{
    GhostLV_Lock();
    bool ret = lv_obj_has_state(obj, state);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_group.
void * safe_lv_obj_get_group(const lv_obj_t * obj)
{
    GhostLV_Lock();
    void * ret = lv_obj_get_group(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_allocate_spec_attr.
void safe_lv_obj_allocate_spec_attr(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_allocate_spec_attr(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_check_type.
bool safe_lv_obj_check_type(const lv_obj_t * obj, const lv_obj_class_t * class_p)
{
    GhostLV_Lock();
    bool ret = lv_obj_check_type(obj, class_p);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_has_class.
bool safe_lv_obj_has_class(const lv_obj_t * obj, const lv_obj_class_t * class_p)
{
    GhostLV_Lock();
    bool ret = lv_obj_has_class(obj, class_p);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_class.
const lv_obj_class_t * safe_lv_obj_get_class(const lv_obj_t * obj)
{
    GhostLV_Lock();
    const lv_obj_class_t * ret = lv_obj_get_class(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_is_valid.
bool safe_lv_obj_is_valid(const lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_is_valid(obj);
    GhostLV_Unlock();
    return ret;
}

