//This file is automatically generated.
//The original file is lv_obj_pos.h
#include "GhostSafeLVGL.h"
#include "safe_lv_obj_pos.h"

//The original function is: lv_obj_set_pos.
void safe_lv_obj_set_pos(struct _lv_obj_t * obj, lv_coord_t x, lv_coord_t y)
{
    GhostLV_Lock();
    lv_obj_set_pos(obj, x, y);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_x.
void safe_lv_obj_set_x(struct _lv_obj_t * obj, lv_coord_t x)
{
    GhostLV_Lock();
    lv_obj_set_x(obj, x);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_y.
void safe_lv_obj_set_y(struct _lv_obj_t * obj, lv_coord_t y)
{
    GhostLV_Lock();
    lv_obj_set_y(obj, y);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_size.
void safe_lv_obj_set_size(struct _lv_obj_t * obj, lv_coord_t w, lv_coord_t h)
{
    GhostLV_Lock();
    lv_obj_set_size(obj, w, h);
    GhostLV_Unlock();
}

//The original function is: lv_obj_refr_size.
bool safe_lv_obj_refr_size(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_refr_size(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_set_width.
void safe_lv_obj_set_width(struct _lv_obj_t * obj, lv_coord_t w)
{
    GhostLV_Lock();
    lv_obj_set_width(obj, w);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_height.
void safe_lv_obj_set_height(struct _lv_obj_t * obj, lv_coord_t h)
{
    GhostLV_Lock();
    lv_obj_set_height(obj, h);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_content_width.
void safe_lv_obj_set_content_width(struct _lv_obj_t * obj, lv_coord_t w)
{
    GhostLV_Lock();
    lv_obj_set_content_width(obj, w);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_content_height.
void safe_lv_obj_set_content_height(struct _lv_obj_t * obj, lv_coord_t h)
{
    GhostLV_Lock();
    lv_obj_set_content_height(obj, h);
    GhostLV_Unlock();
}

//The original function is: lv_obj_is_layout_positioned.
bool safe_lv_obj_is_layout_positioned(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_is_layout_positioned(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_mark_layout_as_dirty.
void safe_lv_obj_mark_layout_as_dirty(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_mark_layout_as_dirty(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_update_layout.
void safe_lv_obj_update_layout(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_update_layout(obj);
    GhostLV_Unlock();
}

//The original function is: lv_layout_register.
uint32_t safe_lv_layout_register(lv_layout_update_cb_t cb, void * user_data)
{
    GhostLV_Lock();
    uint32_t ret = lv_layout_register(cb, user_data);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_set_align.
void safe_lv_obj_set_align(struct _lv_obj_t * obj, lv_align_t align)
{
    GhostLV_Lock();
    lv_obj_set_align(obj, align);
    GhostLV_Unlock();
}

//The original function is: lv_obj_align.
void safe_lv_obj_align(struct _lv_obj_t * obj, lv_align_t align, lv_coord_t x_ofs, lv_coord_t y_ofs)
{
    GhostLV_Lock();
    lv_obj_align(obj, align, x_ofs, y_ofs);
    GhostLV_Unlock();
}

//The original function is: lv_obj_get_coords.
void safe_lv_obj_get_coords(const struct _lv_obj_t * obj, lv_area_t * coords)
{
    GhostLV_Lock();
    lv_obj_get_coords(obj, coords);
    GhostLV_Unlock();
}

//The original function is: lv_obj_get_x.
lv_coord_t safe_lv_obj_get_x(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_x(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_x2.
lv_coord_t safe_lv_obj_get_x2(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_x2(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_y.
lv_coord_t safe_lv_obj_get_y(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_y(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_y2.
lv_coord_t safe_lv_obj_get_y2(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_y2(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_x_aligned.
lv_coord_t safe_lv_obj_get_x_aligned(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_x_aligned(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_y_aligned.
lv_coord_t safe_lv_obj_get_y_aligned(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_y_aligned(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_width.
lv_coord_t safe_lv_obj_get_width(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_width(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_height.
lv_coord_t safe_lv_obj_get_height(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_height(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_content_width.
lv_coord_t safe_lv_obj_get_content_width(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_content_width(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_content_height.
lv_coord_t safe_lv_obj_get_content_height(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_content_height(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_content_coords.
void safe_lv_obj_get_content_coords(const struct _lv_obj_t * obj, lv_area_t * area)
{
    GhostLV_Lock();
    lv_obj_get_content_coords(obj, area);
    GhostLV_Unlock();
}

//The original function is: lv_obj_get_self_width.
lv_coord_t safe_lv_obj_get_self_width(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_self_width(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_self_height.
lv_coord_t safe_lv_obj_get_self_height(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_obj_get_self_height(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_refresh_self_size.
bool safe_lv_obj_refresh_self_size(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_refresh_self_size(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_refr_pos.
void safe_lv_obj_refr_pos(struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_refr_pos(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_move_to.
void safe_lv_obj_move_to(struct _lv_obj_t * obj, lv_coord_t x, lv_coord_t y)
{
    GhostLV_Lock();
    lv_obj_move_to(obj, x, y);
    GhostLV_Unlock();
}

//The original function is: lv_obj_move_children_by.
void safe_lv_obj_move_children_by(struct _lv_obj_t * obj, lv_coord_t x_diff, lv_coord_t y_diff, bool ignore_floating)
{
    GhostLV_Lock();
    lv_obj_move_children_by(obj, x_diff, y_diff, ignore_floating);
    GhostLV_Unlock();
}

//The original function is: lv_obj_invalidate_area.
void safe_lv_obj_invalidate_area(const struct _lv_obj_t * obj, const lv_area_t * area)
{
    GhostLV_Lock();
    lv_obj_invalidate_area(obj, area);
    GhostLV_Unlock();
}

//The original function is: lv_obj_invalidate.
void safe_lv_obj_invalidate(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_invalidate(obj);
    GhostLV_Unlock();
}

//The original function is: lv_obj_area_is_visible.
bool safe_lv_obj_area_is_visible(const struct _lv_obj_t * obj, lv_area_t * area)
{
    GhostLV_Lock();
    bool ret = lv_obj_area_is_visible(obj, area);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_is_visible.
bool safe_lv_obj_is_visible(const struct _lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_obj_is_visible(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_set_ext_click_area.
void safe_lv_obj_set_ext_click_area(struct _lv_obj_t * obj, lv_coord_t size)
{
    GhostLV_Lock();
    lv_obj_set_ext_click_area(obj, size);
    GhostLV_Unlock();
}

//The original function is: lv_obj_get_click_area.
void safe_lv_obj_get_click_area(const struct _lv_obj_t * obj, lv_area_t * area)
{
    GhostLV_Lock();
    lv_obj_get_click_area(obj, area);
    GhostLV_Unlock();
}

//The original function is: lv_obj_hit_test.
bool safe_lv_obj_hit_test(struct _lv_obj_t * obj, const lv_point_t * point)
{
    GhostLV_Lock();
    bool ret = lv_obj_hit_test(obj, point);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_clamp_width.
lv_coord_t safe_lv_clamp_width(lv_coord_t width, lv_coord_t min_width, lv_coord_t max_width, lv_coord_t ref_width)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_clamp_width(width, min_width, max_width, ref_width);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_clamp_height.
lv_coord_t safe_lv_clamp_height(lv_coord_t height, lv_coord_t min_height, lv_coord_t max_height, lv_coord_t ref_height)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_clamp_height(height, min_height, max_height, ref_height);
    GhostLV_Unlock();
    return ret;
}

