//This file is automatically generated.
//The original file is lv_refr.h
#include "lv_refr.h"

//The original function is: lv_refr_now.
void safe_lv_refr_now(lv_disp_t * disp);

//The original function is: lv_refr_obj.
void safe_lv_refr_obj(lv_draw_ctx_t * draw_ctx, lv_obj_t * obj);

//The original function is: lv_refr_reset_fps_counter.
void safe_lv_refr_reset_fps_counter(void);

//The original function is: lv_refr_get_fps_avg.
uint32_t safe_lv_refr_get_fps_avg(void);

