//This file is automatically generated.
//The original file is lv_disp.h
#include "lvgl.h"

//The original function is: lv_disp_get_scr_act.
lv_obj_t * safe_lv_disp_get_scr_act(lv_disp_t * disp);

//The original function is: lv_disp_get_scr_prev.
lv_obj_t * safe_lv_disp_get_scr_prev(lv_disp_t * disp);

//The original function is: lv_disp_load_scr.
void safe_lv_disp_load_scr(lv_obj_t * scr);

//The original function is: lv_disp_get_layer_top.
lv_obj_t * safe_lv_disp_get_layer_top(lv_disp_t * disp);

//The original function is: lv_disp_get_layer_sys.
lv_obj_t * safe_lv_disp_get_layer_sys(lv_disp_t * disp);

//The original function is: lv_disp_set_theme.
void safe_lv_disp_set_theme(lv_disp_t * disp, lv_theme_t * th);

//The original function is: lv_disp_get_theme.
lv_theme_t * safe_lv_disp_get_theme(lv_disp_t * disp);

//The original function is: lv_disp_set_bg_color.
void safe_lv_disp_set_bg_color(lv_disp_t * disp, lv_color_t color);

//The original function is: lv_disp_set_bg_image.
void safe_lv_disp_set_bg_image(lv_disp_t * disp, const void  * img_src);

//The original function is: lv_disp_set_bg_opa.
void safe_lv_disp_set_bg_opa(lv_disp_t * disp, lv_opa_t opa);

//The original function is: lv_disp_get_inactive_time.
uint32_t safe_lv_disp_get_inactive_time(const lv_disp_t * disp);

//The original function is: lv_disp_trig_activity.
void safe_lv_disp_trig_activity(lv_disp_t * disp);

//The original function is: lv_disp_clean_dcache.
void safe_lv_disp_clean_dcache(lv_disp_t * disp);

//The original function is: lv_disp_enable_invalidation.
void safe_lv_disp_enable_invalidation(lv_disp_t * disp, bool en);

//The original function is: lv_disp_is_invalidation_enabled.
bool safe_lv_disp_is_invalidation_enabled(lv_disp_t * disp);

