//This file is automatically generated.
//The original file is lv_obj_style_gen.h
#include "GhostSafeLVGL.h"
#include "safe_lv_obj_style_gen.h"

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_HEIGHT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_HEIGHT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_HEIGHT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_HEIGHT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_HEIGHT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_HEIGHT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_X)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_X);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_Y)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_Y);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ALIGN)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ALIGN);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_HEIGHT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_HEIGHT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_X)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_X);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_Y)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_Y);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ZOOM)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ZOOM);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ANGLE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ANGLE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_TOP)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_TOP);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_BOTTOM)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_BOTTOM);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_LEFT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_LEFT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_RIGHT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_RIGHT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_ROW)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_ROW);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_COLUMN)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_COLUMN);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_DIR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_DIR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_MAIN_STOP)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_MAIN_STOP);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_STOP)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_STOP);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_DITHER_MODE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_DITHER_MODE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_SRC)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_SRC);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_TILED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_TILED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_SIDE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_SIDE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_POST)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_POST);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_PAD)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_PAD);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_X)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_X);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_Y)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_Y);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_SPREAD)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_SPREAD);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_GAP)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_GAP);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_ROUNDED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_ROUNDED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_WIDTH)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_WIDTH);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_ROUNDED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_ROUNDED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_IMG_SRC)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_IMG_SRC);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR_FILTERED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR_FILTERED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_FONT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_FONT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LETTER_SPACE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LETTER_SPACE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LINE_SPACE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LINE_SPACE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_DECOR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_DECOR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_ALIGN)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_ALIGN);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_RADIUS)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_RADIUS);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_CLIP_CORNER)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_CLIP_CORNER);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_DSC)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_DSC);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_OPA)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_OPA);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_TIME)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_TIME);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_SPEED)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_SPEED);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSITION)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSITION);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BLEND_MODE)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BLEND_MODE);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_LAYOUT)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_LAYOUT);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_BASE_DIR)
{
    GhostLV_Lock();
    lv_style_value_t v = ret = lv_obj_get_style_prop(obj, part, LV_STYLE_BASE_DIR);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_obj_set_style_width.
void safe_lv_obj_set_style_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_min_width.
void safe_lv_obj_set_style_min_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_min_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_max_width.
void safe_lv_obj_set_style_max_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_max_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_height.
void safe_lv_obj_set_style_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_height(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_min_height.
void safe_lv_obj_set_style_min_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_min_height(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_max_height.
void safe_lv_obj_set_style_max_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_max_height(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_x.
void safe_lv_obj_set_style_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_x(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_y.
void safe_lv_obj_set_style_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_y(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_align.
void safe_lv_obj_set_style_align(struct _lv_obj_t * obj, lv_align_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_align(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_transform_width.
void safe_lv_obj_set_style_transform_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_transform_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_transform_height.
void safe_lv_obj_set_style_transform_height(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_transform_height(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_translate_x.
void safe_lv_obj_set_style_translate_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_translate_x(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_translate_y.
void safe_lv_obj_set_style_translate_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_translate_y(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_transform_zoom.
void safe_lv_obj_set_style_transform_zoom(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_transform_zoom(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_transform_angle.
void safe_lv_obj_set_style_transform_angle(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_transform_angle(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_top.
void safe_lv_obj_set_style_pad_top(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_top(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_bottom.
void safe_lv_obj_set_style_pad_bottom(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_bottom(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_left.
void safe_lv_obj_set_style_pad_left(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_left(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_right.
void safe_lv_obj_set_style_pad_right(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_right(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_row.
void safe_lv_obj_set_style_pad_row(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_row(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_pad_column.
void safe_lv_obj_set_style_pad_column(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_pad_column(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_color.
void safe_lv_obj_set_style_bg_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_color_filtered.
void safe_lv_obj_set_style_bg_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_opa.
void safe_lv_obj_set_style_bg_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_grad_color.
void safe_lv_obj_set_style_bg_grad_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_grad_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_grad_color_filtered.
void safe_lv_obj_set_style_bg_grad_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_grad_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_grad_dir.
void safe_lv_obj_set_style_bg_grad_dir(struct _lv_obj_t * obj, lv_grad_dir_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_grad_dir(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_main_stop.
void safe_lv_obj_set_style_bg_main_stop(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_main_stop(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_grad_stop.
void safe_lv_obj_set_style_bg_grad_stop(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_grad_stop(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_grad.
void safe_lv_obj_set_style_bg_grad(struct _lv_obj_t * obj, const lv_grad_dsc_t * value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_grad(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_dither_mode.
void safe_lv_obj_set_style_bg_dither_mode(struct _lv_obj_t * obj, lv_dither_mode_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_dither_mode(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_src.
void safe_lv_obj_set_style_bg_img_src(struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_src(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_opa.
void safe_lv_obj_set_style_bg_img_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_recolor.
void safe_lv_obj_set_style_bg_img_recolor(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_recolor(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_recolor_filtered.
void safe_lv_obj_set_style_bg_img_recolor_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_recolor_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_recolor_opa.
void safe_lv_obj_set_style_bg_img_recolor_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_recolor_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_bg_img_tiled.
void safe_lv_obj_set_style_bg_img_tiled(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_bg_img_tiled(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_color.
void safe_lv_obj_set_style_border_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_color_filtered.
void safe_lv_obj_set_style_border_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_opa.
void safe_lv_obj_set_style_border_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_width.
void safe_lv_obj_set_style_border_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_side.
void safe_lv_obj_set_style_border_side(struct _lv_obj_t * obj, lv_border_side_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_side(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_border_post.
void safe_lv_obj_set_style_border_post(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_border_post(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_outline_width.
void safe_lv_obj_set_style_outline_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_outline_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_outline_color.
void safe_lv_obj_set_style_outline_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_outline_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_outline_color_filtered.
void safe_lv_obj_set_style_outline_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_outline_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_outline_opa.
void safe_lv_obj_set_style_outline_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_outline_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_outline_pad.
void safe_lv_obj_set_style_outline_pad(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_outline_pad(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_width.
void safe_lv_obj_set_style_shadow_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_ofs_x.
void safe_lv_obj_set_style_shadow_ofs_x(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_ofs_x(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_ofs_y.
void safe_lv_obj_set_style_shadow_ofs_y(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_ofs_y(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_spread.
void safe_lv_obj_set_style_shadow_spread(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_spread(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_color.
void safe_lv_obj_set_style_shadow_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_color_filtered.
void safe_lv_obj_set_style_shadow_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_shadow_opa.
void safe_lv_obj_set_style_shadow_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_shadow_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_img_opa.
void safe_lv_obj_set_style_img_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_img_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_img_recolor.
void safe_lv_obj_set_style_img_recolor(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_img_recolor(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_img_recolor_filtered.
void safe_lv_obj_set_style_img_recolor_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_img_recolor_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_img_recolor_opa.
void safe_lv_obj_set_style_img_recolor_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_img_recolor_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_width.
void safe_lv_obj_set_style_line_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_dash_width.
void safe_lv_obj_set_style_line_dash_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_dash_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_dash_gap.
void safe_lv_obj_set_style_line_dash_gap(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_dash_gap(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_rounded.
void safe_lv_obj_set_style_line_rounded(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_rounded(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_color.
void safe_lv_obj_set_style_line_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_color_filtered.
void safe_lv_obj_set_style_line_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_line_opa.
void safe_lv_obj_set_style_line_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_line_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_width.
void safe_lv_obj_set_style_arc_width(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_width(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_rounded.
void safe_lv_obj_set_style_arc_rounded(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_rounded(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_color.
void safe_lv_obj_set_style_arc_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_color_filtered.
void safe_lv_obj_set_style_arc_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_opa.
void safe_lv_obj_set_style_arc_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_arc_img_src.
void safe_lv_obj_set_style_arc_img_src(struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_arc_img_src(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_color.
void safe_lv_obj_set_style_text_color(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_color(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_color_filtered.
void safe_lv_obj_set_style_text_color_filtered(struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_color_filtered(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_opa.
void safe_lv_obj_set_style_text_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_font.
void safe_lv_obj_set_style_text_font(struct _lv_obj_t * obj, const lv_font_t * value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_font(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_letter_space.
void safe_lv_obj_set_style_text_letter_space(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_letter_space(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_line_space.
void safe_lv_obj_set_style_text_line_space(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_line_space(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_decor.
void safe_lv_obj_set_style_text_decor(struct _lv_obj_t * obj, lv_text_decor_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_decor(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_text_align.
void safe_lv_obj_set_style_text_align(struct _lv_obj_t * obj, lv_text_align_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_text_align(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_radius.
void safe_lv_obj_set_style_radius(struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_radius(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_clip_corner.
void safe_lv_obj_set_style_clip_corner(struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_clip_corner(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_opa.
void safe_lv_obj_set_style_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_color_filter_opa.
void safe_lv_obj_set_style_color_filter_opa(struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_color_filter_opa(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_anim_time.
void safe_lv_obj_set_style_anim_time(struct _lv_obj_t * obj, uint32_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_anim_time(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_anim_speed.
void safe_lv_obj_set_style_anim_speed(struct _lv_obj_t * obj, uint32_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_anim_speed(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_blend_mode.
void safe_lv_obj_set_style_blend_mode(struct _lv_obj_t * obj, lv_blend_mode_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_blend_mode(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_layout.
void safe_lv_obj_set_style_layout(struct _lv_obj_t * obj, uint16_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_layout(obj, value, selector);
    GhostLV_Unlock();
}

//The original function is: lv_obj_set_style_base_dir.
void safe_lv_obj_set_style_base_dir(struct _lv_obj_t * obj, lv_base_dir_t value, lv_style_selector_t selector)
{
    GhostLV_Lock();
    lv_obj_set_style_base_dir(obj, value, selector);
    GhostLV_Unlock();
}

