//This file is automatically generated.
//The original file is lv_obj_draw.h
#include "lvgl.h"

//The original function is: lv_obj_draw_dsc_init.
void safe_lv_obj_draw_dsc_init(lv_obj_draw_part_dsc_t * dsc, lv_draw_ctx_t * draw_ctx);

//The original function is: lv_obj_refresh_ext_draw_size.
void safe_lv_obj_refresh_ext_draw_size(struct _lv_obj_t * obj);

