//This file is automatically generated.
//The original file is lv_example_rlottie.h
#include "lv_example_rlottie.h"

//The original function is: lv_example_rlottie_1.
void safe_lv_example_rlottie_1(void);

//The original function is: lv_example_rlottie_2.
void safe_lv_example_rlottie_2(void);

