//This file is automatically generated.
//The original file is lv_dropdown.h
#include "lv_dropdown.h"

//The original function is: lv_dropdown_create.
lv_obj_t * safe_lv_dropdown_create(lv_obj_t * parent);

//The original function is: lv_dropdown_set_text.
void safe_lv_dropdown_set_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_dropdown_set_options.
void safe_lv_dropdown_set_options(lv_obj_t * obj, const char * options);

//The original function is: lv_dropdown_set_options_static.
void safe_lv_dropdown_set_options_static(lv_obj_t * obj, const char * options);

//The original function is: lv_dropdown_add_option.
void safe_lv_dropdown_add_option(lv_obj_t * obj, const char * option, uint32_t pos);

//The original function is: lv_dropdown_clear_options.
void safe_lv_dropdown_clear_options(lv_obj_t * obj);

//The original function is: lv_dropdown_set_selected.
void safe_lv_dropdown_set_selected(lv_obj_t * obj, uint16_t sel_opt);

//The original function is: lv_dropdown_set_dir.
void safe_lv_dropdown_set_dir(lv_obj_t * obj, lv_dir_t dir);

//The original function is: lv_dropdown_set_symbol.
void safe_lv_dropdown_set_symbol(lv_obj_t * obj, const void * symbol);

//The original function is: lv_dropdown_set_selected_highlight.
void safe_lv_dropdown_set_selected_highlight(lv_obj_t * obj, bool en);

//The original function is: lv_dropdown_get_list.
lv_obj_t * safe_lv_dropdown_get_list(lv_obj_t * obj);

//The original function is: lv_dropdown_get_text.
const char * safe_lv_dropdown_get_text(lv_obj_t * obj);

//The original function is: lv_dropdown_get_options.
const char * safe_lv_dropdown_get_options(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_selected.
uint16_t safe_lv_dropdown_get_selected(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_option_cnt.
uint16_t safe_lv_dropdown_get_option_cnt(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_selected_str.
void safe_lv_dropdown_get_selected_str(const lv_obj_t * obj, char * buf, uint32_t buf_size);

//The original function is: lv_dropdown_get_symbol.
const char * safe_lv_dropdown_get_symbol(lv_obj_t * obj);

//The original function is: lv_dropdown_get_selected_highlight.
bool safe_lv_dropdown_get_selected_highlight(lv_obj_t * obj);

//The original function is: lv_dropdown_get_dir.
lv_dir_t safe_lv_dropdown_get_dir(const lv_obj_t * obj);

//The original function is: lv_dropdown_open.
void safe_lv_dropdown_open(lv_obj_t * dropdown_obj);

//The original function is: lv_dropdown_close.
void safe_lv_dropdown_close(lv_obj_t * obj);

//The original function is: lv_dropdown_is_open.
bool safe_lv_dropdown_is_open(lv_obj_t * obj);

