//This file is automatically generated.
//The original file is lv_slider.h
#include "lv_slider.h"

//The original function is: lv_slider_create.
lv_obj_t * safe_lv_slider_create(lv_obj_t * parent);

//The original function is: lv_bar_get_value.
return safe_lv_bar_get_value(obj);

//The original function is: lv_bar_get_start_value.
return safe_lv_bar_get_start_value(obj);

//The original function is: lv_bar_get_min_value.
return safe_lv_bar_get_min_value(obj);

//The original function is: lv_bar_get_max_value.
return safe_lv_bar_get_max_value(obj);

//The original function is: lv_slider_is_dragged.
bool safe_lv_slider_is_dragged(const lv_obj_t * obj);

//The original function is: lv_bar_get_mode.
lv_bar_mode_t mode = safe_lv_bar_get_mode(slider);

