//This file is automatically generated.
//The original file is lv_btnmatrix.h
#include "GhostSafeLVGL.h"
#include "safe_lv_btnmatrix.h"

//The original function is: lv_btnmatrix_create.
lv_obj_t * safe_lv_btnmatrix_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_btnmatrix_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_btnmatrix_set_btn_ctrl_all.
void safe_lv_btnmatrix_set_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl)
{
    GhostLV_Lock();
    lv_btnmatrix_set_btn_ctrl_all(obj, ctrl);
    GhostLV_Unlock();
}

//The original function is: lv_btnmatrix_clear_btn_ctrl_all.
void safe_lv_btnmatrix_clear_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl)
{
    GhostLV_Lock();
    lv_btnmatrix_clear_btn_ctrl_all(obj, ctrl);
    GhostLV_Unlock();
}

//The original function is: lv_btnmatrix_set_one_checked.
void safe_lv_btnmatrix_set_one_checked(lv_obj_t * obj, bool en)
{
    GhostLV_Lock();
    lv_btnmatrix_set_one_checked(obj, en);
    GhostLV_Unlock();
}

//The original function is: lv_btnmatrix_get_map.
const char ** safe_lv_btnmatrix_get_map(const lv_obj_t * obj)
{
    GhostLV_Lock();
    const char ** ret = lv_btnmatrix_get_map(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_btnmatrix_get_selected_btn.
uint16_t safe_lv_btnmatrix_get_selected_btn(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_btnmatrix_get_selected_btn(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_btnmatrix_get_one_checked.
bool safe_lv_btnmatrix_get_one_checked(const lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_btnmatrix_get_one_checked(obj);
    GhostLV_Unlock();
    return ret;
}

