//This file is automatically generated.
//The original file is lv_textarea.h
#include "lv_textarea.h"

//The original function is: lv_textarea_create.
lv_obj_t * safe_lv_textarea_create(lv_obj_t * parent);

//The original function is: lv_textarea_add_char.
void safe_lv_textarea_add_char(lv_obj_t * obj, uint32_t c);

//The original function is: lv_textarea_add_text.
void safe_lv_textarea_add_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_textarea_del_char.
void safe_lv_textarea_del_char(lv_obj_t * obj);

//The original function is: lv_textarea_del_char_forward.
void safe_lv_textarea_del_char_forward(lv_obj_t * obj);

//The original function is: lv_textarea_set_text.
void safe_lv_textarea_set_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_textarea_set_placeholder_text.
void safe_lv_textarea_set_placeholder_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_textarea_set_cursor_pos.
void safe_lv_textarea_set_cursor_pos(lv_obj_t * obj, int32_t pos);

//The original function is: lv_textarea_set_cursor_click_pos.
void safe_lv_textarea_set_cursor_click_pos(lv_obj_t * obj, bool en);

//The original function is: lv_textarea_set_password_mode.
void safe_lv_textarea_set_password_mode(lv_obj_t * obj, bool en);

//The original function is: lv_textarea_set_one_line.
void safe_lv_textarea_set_one_line(lv_obj_t * obj, bool en);

//The original function is: lv_textarea_set_accepted_chars.
void safe_lv_textarea_set_accepted_chars(lv_obj_t * obj, const char * list);

//The original function is: lv_textarea_set_max_length.
void safe_lv_textarea_set_max_length(lv_obj_t * obj, uint32_t num);

//The original function is: lv_textarea_set_insert_replace.
void safe_lv_textarea_set_insert_replace(lv_obj_t * obj, const char * txt);

//The original function is: lv_textarea_set_text_selection.
void safe_lv_textarea_set_text_selection(lv_obj_t * obj, bool en);

//The original function is: lv_textarea_set_password_show_time.
void safe_lv_textarea_set_password_show_time(lv_obj_t * obj, uint16_t time);

//The original function is: lv_textarea_set_align.
void safe_lv_textarea_set_align(lv_obj_t * obj, lv_text_align_t align);

//The original function is: lv_textarea_get_text.
const char * safe_lv_textarea_get_text(const lv_obj_t * obj);

//The original function is: lv_textarea_get_placeholder_text.
const char * safe_lv_textarea_get_placeholder_text(lv_obj_t * obj);

//The original function is: lv_textarea_get_label.
lv_obj_t * safe_lv_textarea_get_label(const lv_obj_t * obj);

//The original function is: lv_textarea_get_cursor_pos.
uint32_t safe_lv_textarea_get_cursor_pos(const lv_obj_t * obj);

//The original function is: lv_textarea_get_cursor_click_pos.
bool safe_lv_textarea_get_cursor_click_pos(lv_obj_t * obj);

//The original function is: lv_textarea_get_password_mode.
bool safe_lv_textarea_get_password_mode(const lv_obj_t * obj);

//The original function is: lv_textarea_get_one_line.
bool safe_lv_textarea_get_one_line(const lv_obj_t * obj);

//The original function is: lv_textarea_get_accepted_chars.
const char * safe_lv_textarea_get_accepted_chars(lv_obj_t * obj);

//The original function is: lv_textarea_get_max_length.
uint32_t safe_lv_textarea_get_max_length(lv_obj_t * obj);

//The original function is: lv_textarea_text_is_selected.
bool safe_lv_textarea_text_is_selected(const lv_obj_t * obj);

//The original function is: lv_textarea_get_text_selection.
bool safe_lv_textarea_get_text_selection(lv_obj_t * obj);

//The original function is: lv_textarea_get_password_show_time.
uint16_t safe_lv_textarea_get_password_show_time(lv_obj_t * obj);

//The original function is: lv_textarea_clear_selection.
void safe_lv_textarea_clear_selection(lv_obj_t * obj);

//The original function is: lv_textarea_cursor_right.
void safe_lv_textarea_cursor_right(lv_obj_t * obj);

//The original function is: lv_textarea_cursor_left.
void safe_lv_textarea_cursor_left(lv_obj_t * obj);

//The original function is: lv_textarea_cursor_down.
void safe_lv_textarea_cursor_down(lv_obj_t * obj);

//The original function is: lv_textarea_cursor_up.
void safe_lv_textarea_cursor_up(lv_obj_t * obj);

