//This file is automatically generated.
//The original file is lv_img.h
#include "lvgl.h"

//The original function is: lv_img_create.
lv_obj_t * safe_lv_img_create(lv_obj_t * parent);

//The original function is: lv_img_set_src.
void safe_lv_img_set_src(lv_obj_t * obj, const void * src);

//The original function is: lv_img_set_offset_x.
void safe_lv_img_set_offset_x(lv_obj_t * obj, lv_coord_t x);

//The original function is: lv_img_set_offset_y.
void safe_lv_img_set_offset_y(lv_obj_t * obj, lv_coord_t y);

//The original function is: lv_img_set_pivot.
void safe_lv_img_set_pivot(lv_obj_t * obj, lv_coord_t x, lv_coord_t y);

//The original function is: lv_img_set_antialias.
void safe_lv_img_set_antialias(lv_obj_t * obj, bool antialias);

//The original function is: lv_img_set_size_mode.
void safe_lv_img_set_size_mode(lv_obj_t * obj, lv_img_size_mode_t mode);

//The original function is: lv_img_get_src.
const void * safe_lv_img_get_src(lv_obj_t * obj);

//The original function is: lv_img_get_offset_x.
lv_coord_t safe_lv_img_get_offset_x(lv_obj_t * obj);

//The original function is: lv_img_get_offset_y.
lv_coord_t safe_lv_img_get_offset_y(lv_obj_t * obj);

//The original function is: lv_img_get_angle.
uint16_t safe_lv_img_get_angle(lv_obj_t * obj);

//The original function is: lv_img_get_pivot.
void safe_lv_img_get_pivot(lv_obj_t * obj, lv_point_t * pivot);

//The original function is: lv_img_get_zoom.
uint16_t safe_lv_img_get_zoom(lv_obj_t * obj);

//The original function is: lv_img_get_antialias.
bool safe_lv_img_get_antialias(lv_obj_t * obj);

//The original function is: lv_img_get_size_mode.
lv_img_size_mode_t safe_lv_img_get_size_mode(lv_obj_t * obj);

