//This file is automatically generated.
//The original file is lv_switch.h
#include "GhostSafeLVGL.h"
#include "safe_lv_switch.h"

//The original function is: lv_switch_create.
lv_obj_t * safe_lv_switch_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_switch_create(parent);
    GhostLV_Unlock();
    return ret;
}

