//This file is automatically generated.
//The original file is lv_arc.h
#include "lvgl.h"

//The original function is: lv_arc_create.
lv_obj_t * safe_lv_arc_create(lv_obj_t * parent);

//The original function is: lv_arc_set_mode.
void safe_lv_arc_set_mode(lv_obj_t * arc, lv_arc_mode_t type);

//The original function is: lv_arc_get_angle_start.
uint16_t safe_lv_arc_get_angle_start(lv_obj_t * obj);

//The original function is: lv_arc_get_angle_end.
uint16_t safe_lv_arc_get_angle_end(lv_obj_t * obj);

//The original function is: lv_arc_get_bg_angle_start.
uint16_t safe_lv_arc_get_bg_angle_start(lv_obj_t * obj);

//The original function is: lv_arc_get_bg_angle_end.
uint16_t safe_lv_arc_get_bg_angle_end(lv_obj_t * obj);

//The original function is: lv_arc_get_value.
int16_t safe_lv_arc_get_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_min_value.
int16_t safe_lv_arc_get_min_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_max_value.
int16_t safe_lv_arc_get_max_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_mode.
lv_arc_mode_t safe_lv_arc_get_mode(const lv_obj_t * obj);

