//This file is automatically generated.
//The original file is lv_canvas.h
#include "GhostSafeLVGL.h"
#include "safe_lv_canvas.h"

//The original function is: lv_canvas_create.
lv_obj_t * safe_lv_canvas_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_canvas_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_canvas_set_buffer.
void safe_lv_canvas_set_buffer(lv_obj_t * canvas, void * buf, lv_coord_t w, lv_coord_t h, lv_img_cf_t cf)
{
    GhostLV_Lock();
    lv_canvas_set_buffer(canvas, buf, w, h, cf);
    GhostLV_Unlock();
}

//The original function is: lv_canvas_set_px_color.
void safe_lv_canvas_set_px_color(lv_obj_t * canvas, lv_coord_t x, lv_coord_t y, lv_color_t c)
{
    GhostLV_Lock();
    lv_canvas_set_px_color(canvas, x, y, c);
    GhostLV_Unlock();
}

//The original function is: lv_canvas_set_px_opa.
void safe_lv_canvas_set_px_opa(lv_obj_t * canvas, lv_coord_t x, lv_coord_t y, lv_opa_t opa)
{
    GhostLV_Lock();
    lv_canvas_set_px_opa(canvas, x, y, opa);
    GhostLV_Unlock();
}

//The original function is: lv_canvas_get_px.
lv_color_t safe_lv_canvas_get_px(lv_obj_t * canvas, lv_coord_t x, lv_coord_t y)
{
    GhostLV_Lock();
    lv_color_t ret = lv_canvas_get_px(canvas, x, y);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_canvas_get_img.
lv_img_dsc_t * safe_lv_canvas_get_img(lv_obj_t * canvas)
{
    GhostLV_Lock();
    lv_img_dsc_t * ret = lv_canvas_get_img(canvas);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_canvas_fill_bg.
void safe_lv_canvas_fill_bg(lv_obj_t * canvas, lv_color_t color, lv_opa_t opa)
{
    GhostLV_Lock();
    lv_canvas_fill_bg(canvas, color, opa);
    GhostLV_Unlock();
}

