//This file is automatically generated.
//The original file is lv_btnmatrix.h
#include "lvgl.h"

//The original function is: lv_btnmatrix_create.
lv_obj_t * safe_lv_btnmatrix_create(lv_obj_t * parent);

//The original function is: lv_btnmatrix_set_btn_ctrl_all.
void safe_lv_btnmatrix_set_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl);

//The original function is: lv_btnmatrix_clear_btn_ctrl_all.
void safe_lv_btnmatrix_clear_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl);

//The original function is: lv_btnmatrix_set_one_checked.
void safe_lv_btnmatrix_set_one_checked(lv_obj_t * obj, bool en);

//The original function is: lv_btnmatrix_get_map.
const char ** safe_lv_btnmatrix_get_map(const lv_obj_t * obj);

//The original function is: lv_btnmatrix_get_selected_btn.
uint16_t safe_lv_btnmatrix_get_selected_btn(const lv_obj_t * obj);

//The original function is: lv_btnmatrix_get_one_checked.
bool safe_lv_btnmatrix_get_one_checked(const lv_obj_t * obj);

