//This file is automatically generated.
//The original file is lv_table.h
#include "lvgl.h"

//The original function is: lv_table_create.
lv_obj_t * safe_lv_table_create(lv_obj_t * parent);

//The original function is: lv_table_get_row_cnt.
uint16_t safe_lv_table_get_row_cnt(lv_obj_t * obj);

//The original function is: lv_table_get_col_cnt.
uint16_t safe_lv_table_get_col_cnt(lv_obj_t * obj);

