//This file is automatically generated.
//The original file is lv_btn.h
#include "GhostSafeLVGL.h"
#include "safe_lv_btn.h"

//The original function is: lv_btn_create.
lv_obj_t * safe_lv_btn_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_btn_create(parent);
    GhostLV_Unlock();
    return ret;
}

