//This file is automatically generated.
//The original file is lv_arc.h
#include "lv_arc.h"

//The original function is: lv_arc_create.
lv_obj_t * safe_lv_arc_create(lv_obj_t * parent);

//The original function is: lv_arc_set_start_angle.
void safe_lv_arc_set_start_angle(lv_obj_t * arc, uint16_t start);

//The original function is: lv_arc_set_end_angle.
void safe_lv_arc_set_end_angle(lv_obj_t * arc, uint16_t end);

//The original function is: lv_arc_set_angles.
void safe_lv_arc_set_angles(lv_obj_t * arc, uint16_t start, uint16_t end);

//The original function is: lv_arc_set_bg_start_angle.
void safe_lv_arc_set_bg_start_angle(lv_obj_t * arc, uint16_t start);

//The original function is: lv_arc_set_bg_end_angle.
void safe_lv_arc_set_bg_end_angle(lv_obj_t * arc, uint16_t end);

//The original function is: lv_arc_set_bg_angles.
void safe_lv_arc_set_bg_angles(lv_obj_t * arc, uint16_t start, uint16_t end);

//The original function is: lv_arc_set_rotation.
void safe_lv_arc_set_rotation(lv_obj_t * arc, uint16_t rotation);

//The original function is: lv_arc_set_mode.
void safe_lv_arc_set_mode(lv_obj_t * arc, lv_arc_mode_t type);

//The original function is: lv_arc_set_value.
void safe_lv_arc_set_value(lv_obj_t * arc, int16_t value);

//The original function is: lv_arc_set_range.
void safe_lv_arc_set_range(lv_obj_t * arc, int16_t min, int16_t max);

//The original function is: lv_arc_set_change_rate.
void safe_lv_arc_set_change_rate(lv_obj_t * arc, uint16_t rate);

//The original function is: lv_arc_get_angle_start.
uint16_t safe_lv_arc_get_angle_start(lv_obj_t * obj);

//The original function is: lv_arc_get_angle_end.
uint16_t safe_lv_arc_get_angle_end(lv_obj_t * obj);

//The original function is: lv_arc_get_bg_angle_start.
uint16_t safe_lv_arc_get_bg_angle_start(lv_obj_t * obj);

//The original function is: lv_arc_get_bg_angle_end.
uint16_t safe_lv_arc_get_bg_angle_end(lv_obj_t * obj);

//The original function is: lv_arc_get_value.
int16_t safe_lv_arc_get_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_min_value.
int16_t safe_lv_arc_get_min_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_max_value.
int16_t safe_lv_arc_get_max_value(const lv_obj_t * obj);

//The original function is: lv_arc_get_mode.
lv_arc_mode_t safe_lv_arc_get_mode(const lv_obj_t * obj);

