//This file is automatically generated.
//The original file is lv_roller.h
#include "lvgl.h"

//The original function is: lv_roller_create.
lv_obj_t * safe_lv_roller_create(lv_obj_t * parent);

//The original function is: lv_roller_set_options.
void safe_lv_roller_set_options(lv_obj_t * obj, const char * options, lv_roller_mode_t mode);

//The original function is: lv_roller_get_selected.
uint16_t safe_lv_roller_get_selected(const lv_obj_t * obj);

//The original function is: lv_roller_get_options.
const char * safe_lv_roller_get_options(const lv_obj_t * obj);

//The original function is: lv_roller_get_option_cnt.
uint16_t safe_lv_roller_get_option_cnt(const lv_obj_t * obj);

