//This file is automatically generated.
//The original file is lv_checkbox.h
#include "lv_checkbox.h"

//The original function is: lv_checkbox_create.
lv_obj_t * safe_lv_checkbox_create(lv_obj_t * parent);

//The original function is: lv_checkbox_set_text.
void safe_lv_checkbox_set_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_checkbox_set_text_static.
void safe_lv_checkbox_set_text_static(lv_obj_t * obj, const char * txt);

//The original function is: lv_checkbox_get_text.
const char * safe_lv_checkbox_get_text(const lv_obj_t * obj);

