//This file is automatically generated.
//The original file is lv_dropdown.h
#include "lvgl.h"

//The original function is: lv_dropdown_create.
lv_obj_t * safe_lv_dropdown_create(lv_obj_t * parent);

//The original function is: lv_dropdown_set_text.
void safe_lv_dropdown_set_text(lv_obj_t * obj, const char * txt);

//The original function is: lv_dropdown_set_options.
void safe_lv_dropdown_set_options(lv_obj_t * obj, const char * options);

//The original function is: lv_dropdown_clear_options.
void safe_lv_dropdown_clear_options(lv_obj_t * obj);

//The original function is: lv_dropdown_set_dir.
void safe_lv_dropdown_set_dir(lv_obj_t * obj, lv_dir_t dir);

//The original function is: lv_dropdown_set_symbol.
void safe_lv_dropdown_set_symbol(lv_obj_t * obj, const void * symbol);

//The original function is: lv_dropdown_set_selected_highlight.
void safe_lv_dropdown_set_selected_highlight(lv_obj_t * obj, bool en);

//The original function is: lv_dropdown_get_list.
lv_obj_t * safe_lv_dropdown_get_list(lv_obj_t * obj);

//The original function is: lv_dropdown_get_text.
const char * safe_lv_dropdown_get_text(lv_obj_t * obj);

//The original function is: lv_dropdown_get_options.
const char * safe_lv_dropdown_get_options(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_selected.
uint16_t safe_lv_dropdown_get_selected(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_option_cnt.
uint16_t safe_lv_dropdown_get_option_cnt(const lv_obj_t * obj);

//The original function is: lv_dropdown_get_option_index.
int32_t safe_lv_dropdown_get_option_index(lv_obj_t * obj, const char * option);

//The original function is: lv_dropdown_get_symbol.
const char * safe_lv_dropdown_get_symbol(lv_obj_t * obj);

//The original function is: lv_dropdown_get_selected_highlight.
bool safe_lv_dropdown_get_selected_highlight(lv_obj_t * obj);

//The original function is: lv_dropdown_get_dir.
lv_dir_t safe_lv_dropdown_get_dir(const lv_obj_t * obj);

//The original function is: lv_dropdown_open.
void safe_lv_dropdown_open(lv_obj_t * dropdown_obj);

//The original function is: lv_dropdown_close.
void safe_lv_dropdown_close(lv_obj_t * obj);

//The original function is: lv_dropdown_is_open.
bool safe_lv_dropdown_is_open(lv_obj_t * obj);

