//This file is automatically generated.
//The original file is lv_roller.h
#include "lv_roller.h"

//The original function is: lv_roller_create.
lv_obj_t * safe_lv_roller_create(lv_obj_t * parent);

//The original function is: lv_roller_set_options.
void safe_lv_roller_set_options(lv_obj_t * obj, const char * options, lv_roller_mode_t mode);

//The original function is: lv_roller_set_selected.
void safe_lv_roller_set_selected(lv_obj_t * obj, uint16_t sel_opt, lv_anim_enable_t anim);

//The original function is: lv_roller_set_visible_row_count.
void safe_lv_roller_set_visible_row_count(lv_obj_t * obj, uint8_t row_cnt);

//The original function is: lv_roller_get_selected.
uint16_t safe_lv_roller_get_selected(const lv_obj_t * obj);

//The original function is: lv_roller_get_selected_str.
void safe_lv_roller_get_selected_str(const lv_obj_t * obj, char * buf, uint32_t buf_size);

//The original function is: lv_roller_get_options.
const char * safe_lv_roller_get_options(const lv_obj_t * obj);

//The original function is: lv_roller_get_option_cnt.
uint16_t safe_lv_roller_get_option_cnt(const lv_obj_t * obj);

