//This file is automatically generated.
//The original file is lv_bar.h
#include "GhostSafeLVGL.h"
#include "safe_lv_bar.h"

//The original function is: lv_bar_create.
lv_obj_t * safe_lv_bar_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_bar_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_bar_set_value.
void safe_lv_bar_set_value(lv_obj_t * obj, int32_t value, lv_anim_enable_t anim)
{
    GhostLV_Lock();
    lv_bar_set_value(obj, value, anim);
    GhostLV_Unlock();
}

//The original function is: lv_bar_set_start_value.
void safe_lv_bar_set_start_value(lv_obj_t * obj, int32_t start_value, lv_anim_enable_t anim)
{
    GhostLV_Lock();
    lv_bar_set_start_value(obj, start_value, anim);
    GhostLV_Unlock();
}

//The original function is: lv_bar_set_range.
void safe_lv_bar_set_range(lv_obj_t * obj, int32_t min, int32_t max)
{
    GhostLV_Lock();
    lv_bar_set_range(obj, min, max);
    GhostLV_Unlock();
}

//The original function is: lv_bar_set_mode.
void safe_lv_bar_set_mode(lv_obj_t * obj, lv_bar_mode_t mode)
{
    GhostLV_Lock();
    lv_bar_set_mode(obj, mode);
    GhostLV_Unlock();
}

//The original function is: lv_bar_get_value.
int32_t safe_lv_bar_get_value(const lv_obj_t * obj)
{
    GhostLV_Lock();
    int32_t ret = lv_bar_get_value(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_bar_get_start_value.
int32_t safe_lv_bar_get_start_value(const lv_obj_t * obj)
{
    GhostLV_Lock();
    int32_t ret = lv_bar_get_start_value(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_bar_get_min_value.
int32_t safe_lv_bar_get_min_value(const lv_obj_t * obj)
{
    GhostLV_Lock();
    int32_t ret = lv_bar_get_min_value(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_bar_get_max_value.
int32_t safe_lv_bar_get_max_value(const lv_obj_t * obj)
{
    GhostLV_Lock();
    int32_t ret = lv_bar_get_max_value(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_bar_get_mode.
lv_bar_mode_t safe_lv_bar_get_mode(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_bar_mode_t ret = lv_bar_get_mode(obj);
    GhostLV_Unlock();
    return ret;
}

