//This file is automatically generated.
//The original file is lv_dropdown.h
#include "GhostSafeLVGL.h"
#include "safe_lv_dropdown.h"

//The original function is: lv_dropdown_create.
lv_obj_t * safe_lv_dropdown_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_dropdown_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_set_text.
void safe_lv_dropdown_set_text(lv_obj_t * obj, const char * txt)
{
    GhostLV_Lock();
    lv_dropdown_set_text(obj, txt);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_set_options.
void safe_lv_dropdown_set_options(lv_obj_t * obj, const char * options)
{
    GhostLV_Lock();
    lv_dropdown_set_options(obj, options);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_clear_options.
void safe_lv_dropdown_clear_options(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_dropdown_clear_options(obj);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_set_dir.
void safe_lv_dropdown_set_dir(lv_obj_t * obj, lv_dir_t dir)
{
    GhostLV_Lock();
    lv_dropdown_set_dir(obj, dir);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_set_symbol.
void safe_lv_dropdown_set_symbol(lv_obj_t * obj, const void * symbol)
{
    GhostLV_Lock();
    lv_dropdown_set_symbol(obj, symbol);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_set_selected_highlight.
void safe_lv_dropdown_set_selected_highlight(lv_obj_t * obj, bool en)
{
    GhostLV_Lock();
    lv_dropdown_set_selected_highlight(obj, en);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_get_list.
lv_obj_t * safe_lv_dropdown_get_list(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_dropdown_get_list(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_text.
const char * safe_lv_dropdown_get_text(lv_obj_t * obj)
{
    GhostLV_Lock();
    const char * ret = lv_dropdown_get_text(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_options.
const char * safe_lv_dropdown_get_options(const lv_obj_t * obj)
{
    GhostLV_Lock();
    const char * ret = lv_dropdown_get_options(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_selected.
uint16_t safe_lv_dropdown_get_selected(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_dropdown_get_selected(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_option_cnt.
uint16_t safe_lv_dropdown_get_option_cnt(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_dropdown_get_option_cnt(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_option_index.
int32_t safe_lv_dropdown_get_option_index(lv_obj_t * obj, const char * option)
{
    GhostLV_Lock();
    int32_t ret = lv_dropdown_get_option_index(obj, option);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_symbol.
const char * safe_lv_dropdown_get_symbol(lv_obj_t * obj)
{
    GhostLV_Lock();
    const char * ret = lv_dropdown_get_symbol(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_selected_highlight.
bool safe_lv_dropdown_get_selected_highlight(lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_dropdown_get_selected_highlight(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_get_dir.
lv_dir_t safe_lv_dropdown_get_dir(const lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_dir_t ret = lv_dropdown_get_dir(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_dropdown_open.
void safe_lv_dropdown_open(lv_obj_t * dropdown_obj)
{
    GhostLV_Lock();
    lv_dropdown_open(dropdown_obj);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_close.
void safe_lv_dropdown_close(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_dropdown_close(obj);
    GhostLV_Unlock();
}

//The original function is: lv_dropdown_is_open.
bool safe_lv_dropdown_is_open(lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_dropdown_is_open(obj);
    GhostLV_Unlock();
    return ret;
}

