//This file is automatically generated.
//The original file is lv_line.h
#include "GhostSafeLVGL.h"
#include "safe_lv_line.h"

//The original function is: lv_line_create.
lv_obj_t * safe_lv_line_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_line_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_line_set_points.
void safe_lv_line_set_points(lv_obj_t * obj, const lv_point_t points[], uint16_t point_num)
{
    GhostLV_Lock();
    lv_line_set_points(obj, points[], point_num);
    GhostLV_Unlock();
}

//The original function is: lv_line_set_y_invert.
void safe_lv_line_set_y_invert(lv_obj_t * obj, bool en)
{
    GhostLV_Lock();
    lv_line_set_y_invert(obj, en);
    GhostLV_Unlock();
}

//The original function is: lv_line_get_y_invert.
bool safe_lv_line_get_y_invert(const lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_line_get_y_invert(obj);
    GhostLV_Unlock();
    return ret;
}

