//This file is automatically generated.
//The original file is lv_label.h
#include "lv_label.h"

//The original function is: lv_label_create.
lv_obj_t * safe_lv_label_create(lv_obj_t * parent);

//The original function is: lv_label_set_text.
void safe_lv_label_set_text(lv_obj_t * obj, const char * text);

//The original function is: lv_label_set_text_fmt(lv_obj_t * obj, const char * fmt, ...) LV_FORMAT_ATTRIBUTE.
void safe_lv_label_set_text_fmt(lv_obj_t * obj, const char * fmt, ...) LV_FORMAT_ATTRIBUTE(2, 3);

//The original function is: lv_label_set_text_static.
void safe_lv_label_set_text_static(lv_obj_t * obj, const char * text);

//The original function is: lv_label_set_long_mode.
void safe_lv_label_set_long_mode(lv_obj_t * obj, lv_label_long_mode_t long_mode);

//The original function is: lv_label_set_recolor.
void safe_lv_label_set_recolor(lv_obj_t * obj, bool en);

//The original function is: lv_label_set_text_sel_start.
void safe_lv_label_set_text_sel_start(lv_obj_t * obj, uint32_t index);

//The original function is: lv_label_set_text_sel_end.
void safe_lv_label_set_text_sel_end(lv_obj_t * obj, uint32_t index);

//The original function is: lv_label_get_text.
char * safe_lv_label_get_text(const lv_obj_t * obj);

//The original function is: lv_label_get_long_mode.
lv_label_long_mode_t safe_lv_label_get_long_mode(const lv_obj_t * obj);

//The original function is: lv_label_get_recolor.
bool safe_lv_label_get_recolor(const lv_obj_t * obj);

//The original function is: lv_label_get_letter_pos.
void safe_lv_label_get_letter_pos(const lv_obj_t * obj, uint32_t char_id, lv_point_t * pos);

//The original function is: lv_label_get_letter_on.
uint32_t safe_lv_label_get_letter_on(const lv_obj_t * obj, lv_point_t * pos_in);

//The original function is: lv_label_is_char_under_pos.
bool safe_lv_label_is_char_under_pos(const lv_obj_t * obj, lv_point_t * pos);

//The original function is: lv_label_get_text_selection_start.
uint32_t safe_lv_label_get_text_selection_start(const lv_obj_t * obj);

//The original function is: lv_label_get_text_selection_end.
uint32_t safe_lv_label_get_text_selection_end(const lv_obj_t * obj);

//The original function is: lv_label_ins_text.
void safe_lv_label_ins_text(lv_obj_t * obj, uint32_t pos, const char * txt);

//The original function is: lv_label_cut_text.
void safe_lv_label_cut_text(lv_obj_t * obj, uint32_t pos, uint32_t cnt);

