//This file is automatically generated.
//The original file is lv_table.h
#include "GhostSafeLVGL.h"
#include "safe_lv_table.h"

//The original function is: lv_table_create.
lv_obj_t * safe_lv_table_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_table_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_set_cell_value.
void safe_lv_table_set_cell_value(lv_obj_t * obj, uint16_t row, uint16_t col, const char * txt)
{
    GhostLV_Lock();
    lv_table_set_cell_value(obj, row, col, txt);
    GhostLV_Unlock();
}

//The original function is: lv_table_set_cell_value_fmt.
void safe_lv_table_set_cell_value_fmt(lv_obj_t * obj, uint16_t row, uint16_t col, const char * fmt, ...)
{
    GhostLV_Lock();
    lv_table_set_cell_value_fmt(obj, row, col, fmt, ##__VAR__ARGS__##);
    GhostLV_Unlock();
}

//The original function is: lv_table_set_row_cnt.
void safe_lv_table_set_row_cnt(lv_obj_t * obj, uint16_t row_cnt)
{
    GhostLV_Lock();
    lv_table_set_row_cnt(obj, row_cnt);
    GhostLV_Unlock();
}

//The original function is: lv_table_set_col_cnt.
void safe_lv_table_set_col_cnt(lv_obj_t * obj, uint16_t col_cnt)
{
    GhostLV_Lock();
    lv_table_set_col_cnt(obj, col_cnt);
    GhostLV_Unlock();
}

//The original function is: lv_table_set_col_width.
void safe_lv_table_set_col_width(lv_obj_t * obj, uint16_t col_id, lv_coord_t w)
{
    GhostLV_Lock();
    lv_table_set_col_width(obj, col_id, w);
    GhostLV_Unlock();
}

//The original function is: lv_table_add_cell_ctrl.
void safe_lv_table_add_cell_ctrl(lv_obj_t * obj, uint16_t row, uint16_t col, lv_table_cell_ctrl_t ctrl)
{
    GhostLV_Lock();
    lv_table_add_cell_ctrl(obj, row, col, ctrl);
    GhostLV_Unlock();
}

//The original function is: lv_table_clear_cell_ctrl.
void safe_lv_table_clear_cell_ctrl(lv_obj_t * obj, uint16_t row, uint16_t col, lv_table_cell_ctrl_t ctrl)
{
    GhostLV_Lock();
    lv_table_clear_cell_ctrl(obj, row, col, ctrl);
    GhostLV_Unlock();
}

//The original function is: lv_table_get_cell_value.
const char * safe_lv_table_get_cell_value(lv_obj_t * obj, uint16_t row, uint16_t col)
{
    GhostLV_Lock();
    const char * ret = lv_table_get_cell_value(obj, row, col);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_get_row_cnt.
uint16_t safe_lv_table_get_row_cnt(lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_table_get_row_cnt(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_get_col_cnt.
uint16_t safe_lv_table_get_col_cnt(lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_table_get_col_cnt(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_get_col_width.
lv_coord_t safe_lv_table_get_col_width(lv_obj_t * obj, uint16_t col)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_table_get_col_width(obj, col);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_has_cell_ctrl.
bool safe_lv_table_has_cell_ctrl(lv_obj_t * obj, uint16_t row, uint16_t col, lv_table_cell_ctrl_t ctrl)
{
    GhostLV_Lock();
    bool ret = lv_table_has_cell_ctrl(obj, row, col, ctrl);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_table_get_selected_cell.
void safe_lv_table_get_selected_cell(lv_obj_t * obj, uint16_t * row, uint16_t * col)
{
    GhostLV_Lock();
    lv_table_get_selected_cell(obj, row, col);
    GhostLV_Unlock();
}

