//This file is automatically generated.
//The original file is lv_line.h
#include "lv_line.h"

//The original function is: lv_line_create.
lv_obj_t * safe_lv_line_create(lv_obj_t * parent);

//The original function is: lv_line_set_points.
void safe_lv_line_set_points(lv_obj_t * obj, const lv_point_t points[], uint16_t point_num);

//The original function is: lv_line_set_y_invert.
void safe_lv_line_set_y_invert(lv_obj_t * obj, bool en);

//The original function is: lv_line_get_y_invert.
bool safe_lv_line_get_y_invert(const lv_obj_t * obj);

