//This file is automatically generated.
//The original file is lv_snapshot.h
#include "lv_snapshot.h"

//The original function is: lv_snapshot_take.
lv_img_dsc_t * safe_lv_snapshot_take(lv_obj_t * obj, lv_img_cf_t cf);

//The original function is: lv_snapshot_free.
void safe_lv_snapshot_free(lv_img_dsc_t * dsc);

//The original function is: lv_snapshot_buf_size_needed.
uint32_t safe_lv_snapshot_buf_size_needed(lv_obj_t * obj, lv_img_cf_t cf);

//The original function is: lv_snapshot_take_to_buf.
lv_res_t safe_lv_snapshot_take_to_buf(lv_obj_t * obj, lv_img_cf_t cf, lv_img_dsc_t * dsc, void * buf, uint32_t buff_size);

