//This file is automatically generated.
//The original file is lv_gpu_nxp_vglite.h
#include "lv_gpu_nxp_vglite.h"

//The original function is: lv_gpu_nxp_vglite_blit.
lv_res_t safe_lv_gpu_nxp_vglite_blit(lv_gpu_nxp_vglite_blit_info_t * blit);

