//This file is automatically generated.
//The original file is lv_monkey.h
#include "GhostSafeLVGL.h"
#include "safe_lv_monkey.h"

//The original function is: lv_monkey_config_init.
void safe_lv_monkey_config_init(lv_monkey_config_t * config)
{
    GhostLV_Lock();
    lv_monkey_config_init(config);
    GhostLV_Unlock();
}

//The original function is: lv_monkey_create.
lv_monkey_t * safe_lv_monkey_create(const lv_monkey_config_t * config)
{
    GhostLV_Lock();
    lv_monkey_t * ret = lv_monkey_create(config);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_monkey_get_indev.
lv_indev_t * safe_lv_monkey_get_indev(lv_monkey_t * monkey)
{
    GhostLV_Lock();
    lv_indev_t * ret = lv_monkey_get_indev(monkey);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_monkey_set_enable.
void safe_lv_monkey_set_enable(lv_monkey_t * monkey, bool en)
{
    GhostLV_Lock();
    lv_monkey_set_enable(monkey, en);
    GhostLV_Unlock();
}

//The original function is: lv_monkey_get_enable.
bool safe_lv_monkey_get_enable(lv_monkey_t * monkey)
{
    GhostLV_Lock();
    bool ret = lv_monkey_get_enable(monkey);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_monkey_set_user_data.
void safe_lv_monkey_set_user_data(lv_monkey_t * monkey, void * user_data)
{
    GhostLV_Lock();
    lv_monkey_set_user_data(monkey, user_data);
    GhostLV_Unlock();
}

//The original function is: lv_monkey_get_user_data.
void * safe_lv_monkey_get_user_data(lv_monkey_t * monkey)
{
    GhostLV_Lock();
    void * ret = lv_monkey_get_user_data(monkey);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_monkey_del.
void safe_lv_monkey_del(lv_monkey_t * monkey)
{
    GhostLV_Lock();
    lv_monkey_del(monkey);
    GhostLV_Unlock();
}

