//This file is automatically generated.
//The original file is lv_theme_default.h
#include "GhostSafeLVGL.h"
#include "safe_lv_theme_default.h"

//The original function is: lv_theme_default_get.
lv_theme_t * safe_lv_theme_default_get(void)
{
    GhostLV_Lock();
    lv_theme_t * ret = lv_theme_default_get();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_theme_default_is_inited.
bool safe_lv_theme_default_is_inited(void)
{
    GhostLV_Lock();
    bool ret = lv_theme_default_is_inited();
    GhostLV_Unlock();
    return ret;
}

