//This file is automatically generated.
//The original file is lv_theme_default.h
#include "lvgl.h"

//The original function is: lv_theme_default_get.
lv_theme_t * safe_lv_theme_default_get(void);

//The original function is: lv_theme_default_is_inited.
bool safe_lv_theme_default_is_inited(void);

