//This file is automatically generated.
//The original file is lv_example_style.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_style.h"

//The original function is: lv_example_style_1.
void safe_lv_example_style_1(void)
{
    GhostLV_Lock();
    lv_example_style_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_2.
void safe_lv_example_style_2(void)
{
    GhostLV_Lock();
    lv_example_style_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_3.
void safe_lv_example_style_3(void)
{
    GhostLV_Lock();
    lv_example_style_3();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_4.
void safe_lv_example_style_4(void)
{
    GhostLV_Lock();
    lv_example_style_4();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_5.
void safe_lv_example_style_5(void)
{
    GhostLV_Lock();
    lv_example_style_5();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_6.
void safe_lv_example_style_6(void)
{
    GhostLV_Lock();
    lv_example_style_6();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_7.
void safe_lv_example_style_7(void)
{
    GhostLV_Lock();
    lv_example_style_7();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_8.
void safe_lv_example_style_8(void)
{
    GhostLV_Lock();
    lv_example_style_8();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_9.
void safe_lv_example_style_9(void)
{
    GhostLV_Lock();
    lv_example_style_9();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_10.
void safe_lv_example_style_10(void)
{
    GhostLV_Lock();
    lv_example_style_10();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_11.
void safe_lv_example_style_11(void)
{
    GhostLV_Lock();
    lv_example_style_11();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_12.
void safe_lv_example_style_12(void)
{
    GhostLV_Lock();
    lv_example_style_12();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_13.
void safe_lv_example_style_13(void)
{
    GhostLV_Lock();
    lv_example_style_13();
    GhostLV_Unlock();
}

//The original function is: lv_example_style_14.
void safe_lv_example_style_14(void)
{
    GhostLV_Lock();
    lv_example_style_14();
    GhostLV_Unlock();
}

