//This file is automatically generated.
//The original file is lv_example_style.h
#include "lv_example_style.h"

//The original function is: lv_example_style_1.
void safe_lv_example_style_1(void);

//The original function is: lv_example_style_2.
void safe_lv_example_style_2(void);

//The original function is: lv_example_style_3.
void safe_lv_example_style_3(void);

//The original function is: lv_example_style_4.
void safe_lv_example_style_4(void);

//The original function is: lv_example_style_5.
void safe_lv_example_style_5(void);

//The original function is: lv_example_style_6.
void safe_lv_example_style_6(void);

//The original function is: lv_example_style_7.
void safe_lv_example_style_7(void);

//The original function is: lv_example_style_8.
void safe_lv_example_style_8(void);

//The original function is: lv_example_style_9.
void safe_lv_example_style_9(void);

//The original function is: lv_example_style_10.
void safe_lv_example_style_10(void);

//The original function is: lv_example_style_11.
void safe_lv_example_style_11(void);

//The original function is: lv_example_style_12.
void safe_lv_example_style_12(void);

//The original function is: lv_example_style_13.
void safe_lv_example_style_13(void);

//The original function is: lv_example_style_14.
void safe_lv_example_style_14(void);

