//This file is automatically generated.
//The original file is lv_gridnav.h
#include "lv_gridnav.h"

//The original function is: lv_gridnav_add.
void safe_lv_gridnav_add(lv_obj_t * obj, lv_gridnav_ctrl_t ctrl);

//The original function is: lv_gridnav_remove.
void safe_lv_gridnav_remove(lv_obj_t * obj);

