//This file is automatically generated.
//The original file is lv_imgfont.h
#include "GhostSafeLVGL.h"
#include "safe_lv_imgfont.h"

//The original function is: lv_imgfont_destroy.
void safe_lv_imgfont_destroy(lv_font_t * font)
{
    GhostLV_Lock();
    lv_imgfont_destroy(font);
    GhostLV_Unlock();
}

