//This file is automatically generated.
//The original file is lv_fsdrv.h
#include "GhostSafeLVGL.h"
#include "safe_lv_fsdrv.h"

//The original function is: lv_fs_fatfs_init.
void safe_lv_fs_fatfs_init(void)
{
    GhostLV_Lock();
    lv_fs_fatfs_init();
    GhostLV_Unlock();
}

//The original function is: lv_fs_stdio_init.
void safe_lv_fs_stdio_init(void)
{
    GhostLV_Lock();
    lv_fs_stdio_init();
    GhostLV_Unlock();
}

//The original function is: lv_fs_posix_init.
void safe_lv_fs_posix_init(void)
{
    GhostLV_Lock();
    lv_fs_posix_init();
    GhostLV_Unlock();
}

//The original function is: lv_fs_win32_init.
void safe_lv_fs_win32_init(void)
{
    GhostLV_Lock();
    lv_fs_win32_init();
    GhostLV_Unlock();
}

