//This file is automatically generated.
//The original file is lv_example_snapshot.h
#include "lv_example_snapshot.h"

//The original function is: lv_example_snapshot_1.
void safe_lv_example_snapshot_1(void);

