//This file is automatically generated.
//The original file is lv_flex.h
#include "lv_flex.h"

//The original function is: lv_flex_init.
void safe_lv_flex_init(void);

//The original function is: lv_obj_set_flex_flow.
void safe_lv_obj_set_flex_flow(lv_obj_t * obj, lv_flex_flow_t flow);

//The original function is: lv_obj_set_flex_grow.
void safe_lv_obj_set_flex_grow(lv_obj_t * obj, uint8_t grow);

//The original function is: lv_style_set_flex_flow.
void safe_lv_style_set_flex_flow(lv_style_t * style, lv_flex_flow_t value);

//The original function is: lv_style_set_flex_main_place.
void safe_lv_style_set_flex_main_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_style_set_flex_cross_place.
void safe_lv_style_set_flex_cross_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_style_set_flex_track_place.
void safe_lv_style_set_flex_track_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_style_set_flex_grow.
void safe_lv_style_set_flex_grow(lv_style_t * style, uint8_t value);

//The original function is: lv_obj_set_style_flex_flow.
void safe_lv_obj_set_style_flex_flow(lv_obj_t * obj, lv_flex_flow_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_main_place.
void safe_lv_obj_set_style_flex_main_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_cross_place.
void safe_lv_obj_set_style_flex_cross_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_track_place.
void safe_lv_obj_set_style_flex_track_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_grow.
void safe_lv_obj_set_style_flex_grow(lv_obj_t * obj, uint8_t value, lv_style_selector_t selector);

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_FLEX_FLOW);

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_FLEX_MAIN_PLACE);

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_FLEX_CROSS_PLACE);

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_FLEX_TRACK_PLACE);

//The original function is: lv_obj_get_style_prop.
lv_style_value_t v = safe_lv_obj_get_style_prop(obj, part, LV_STYLE_FLEX_GROW);

