//This file is automatically generated.
//The original file is lv_flex.h
#include "lvgl.h"

//The original function is: lv_flex_init.
void safe_lv_flex_init(void);

//The original function is: lv_obj_set_flex_flow.
void safe_lv_obj_set_flex_flow(lv_obj_t * obj, lv_flex_flow_t flow);

//The original function is: lv_style_set_flex_flow.
void safe_lv_style_set_flex_flow(lv_style_t * style, lv_flex_flow_t value);

//The original function is: lv_style_set_flex_main_place.
void safe_lv_style_set_flex_main_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_style_set_flex_cross_place.
void safe_lv_style_set_flex_cross_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_style_set_flex_track_place.
void safe_lv_style_set_flex_track_place(lv_style_t * style, lv_flex_align_t value);

//The original function is: lv_obj_set_style_flex_flow.
void safe_lv_obj_set_style_flex_flow(lv_obj_t * obj, lv_flex_flow_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_main_place.
void safe_lv_obj_set_style_flex_main_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_cross_place.
void safe_lv_obj_set_style_flex_cross_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

//The original function is: lv_obj_set_style_flex_track_place.
void safe_lv_obj_set_style_flex_track_place(lv_obj_t * obj, lv_flex_align_t value, lv_style_selector_t selector);

