//This file is automatically generated.
//The original file is lv_example_event.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_event.h"

//The original function is: lv_example_event_1.
void safe_lv_example_event_1(void)
{
    GhostLV_Lock();
    lv_example_event_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_event_2.
void safe_lv_example_event_2(void)
{
    GhostLV_Lock();
    lv_example_event_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_event_3.
void safe_lv_example_event_3(void)
{
    GhostLV_Lock();
    lv_example_event_3();
    GhostLV_Unlock();
}

//The original function is: lv_example_event_4.
void safe_lv_example_event_4(void)
{
    GhostLV_Lock();
    lv_example_event_4();
    GhostLV_Unlock();
}

