//This file is automatically generated.
//The original file is unity_support.h
#include "GhostSafeLVGL.h"
#include "safe_unity_support.h"

//The original function is: lv_test_assert_img_eq.
bool safe_lv_test_assert_img_eq(const char * fn_ref)
{
    GhostLV_Lock();
    bool ret = lv_test_assert_img_eq(fn_ref);
    GhostLV_Unlock();
    return ret;
}

