//This file is automatically generated.
//The original file is lv_chart.h
#include "lv_chart.h"

//The original function is: lv_chart_create.
lv_obj_t * safe_lv_chart_create(lv_obj_t * parent);

//The original function is: lv_chart_set_type.
void safe_lv_chart_set_type(lv_obj_t * obj, lv_chart_type_t type);

//The original function is: lv_chart_set_point_count.
void safe_lv_chart_set_point_count(lv_obj_t * obj, uint16_t cnt);

//The original function is: lv_chart_set_range.
void safe_lv_chart_set_range(lv_obj_t * obj, lv_chart_axis_t axis, lv_coord_t min, lv_coord_t max);

//The original function is: lv_chart_set_update_mode.
void safe_lv_chart_set_update_mode(lv_obj_t * obj, lv_chart_update_mode_t update_mode);

//The original function is: lv_chart_set_div_line_count.
void safe_lv_chart_set_div_line_count(lv_obj_t * obj, uint8_t hdiv, uint8_t vdiv);

//The original function is: lv_chart_set_zoom_x.
void safe_lv_chart_set_zoom_x(lv_obj_t * obj, uint16_t zoom_x);

//The original function is: lv_chart_set_zoom_y.
void safe_lv_chart_set_zoom_y(lv_obj_t * obj, uint16_t zoom_y);

//The original function is: lv_chart_get_zoom_x.
uint16_t safe_lv_chart_get_zoom_x(const lv_obj_t * obj);

//The original function is: lv_chart_get_zoom_y.
uint16_t safe_lv_chart_get_zoom_y(const lv_obj_t * obj);

//The original function is: lv_chart_get_type.
lv_chart_type_t safe_lv_chart_get_type(const lv_obj_t * obj);

//The original function is: lv_chart_get_point_count.
uint16_t safe_lv_chart_get_point_count(const lv_obj_t * obj);

//The original function is: lv_chart_get_x_start_point.
uint16_t safe_lv_chart_get_x_start_point(const lv_obj_t * obj, lv_chart_series_t * ser);

//The original function is: lv_chart_get_point_pos_by_id.
void safe_lv_chart_get_point_pos_by_id(lv_obj_t * obj, lv_chart_series_t * ser, uint16_t id, lv_point_t * p_out);

//The original function is: lv_chart_refresh.
void safe_lv_chart_refresh(lv_obj_t * obj);

//The original function is: lv_chart_add_series.
lv_chart_series_t * safe_lv_chart_add_series(lv_obj_t * obj, lv_color_t color, lv_chart_axis_t axis);

//The original function is: lv_chart_remove_series.
void safe_lv_chart_remove_series(lv_obj_t * obj, lv_chart_series_t * series);

//The original function is: lv_chart_hide_series.
void safe_lv_chart_hide_series(lv_obj_t * chart, lv_chart_series_t * series, bool hide);

//The original function is: lv_chart_set_series_color.
void safe_lv_chart_set_series_color(lv_obj_t * chart, lv_chart_series_t * series, lv_color_t color);

//The original function is: lv_chart_set_x_start_point.
void safe_lv_chart_set_x_start_point(lv_obj_t * obj, lv_chart_series_t * ser, uint16_t id);

//The original function is: lv_chart_get_series_next.
lv_chart_series_t * safe_lv_chart_get_series_next(const lv_obj_t * chart, const lv_chart_series_t * ser);

//The original function is: lv_chart_add_cursor.
lv_chart_cursor_t  * safe_lv_chart_add_cursor(lv_obj_t * obj, lv_color_t color, lv_dir_t dir);

//The original function is: lv_chart_set_cursor_pos.
void safe_lv_chart_set_cursor_pos(lv_obj_t * chart, lv_chart_cursor_t * cursor, lv_point_t * pos);

//The original function is: lv_chart_get_cursor_point.
lv_point_t safe_lv_chart_get_cursor_point(lv_obj_t * chart, lv_chart_cursor_t * cursor);

//The original function is: lv_chart_set_all_value.
void safe_lv_chart_set_all_value(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t value);

//The original function is: lv_chart_set_next_value.
void safe_lv_chart_set_next_value(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t value);

//The original function is: lv_chart_set_next_value2.
void safe_lv_chart_set_next_value2(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t x_value, lv_coord_t y_value);

//The original function is: lv_chart_set_value_by_id.
void safe_lv_chart_set_value_by_id(lv_obj_t * obj, lv_chart_series_t * ser, uint16_t id, lv_coord_t value);

//The original function is: lv_chart_set_ext_y_array.
void safe_lv_chart_set_ext_y_array(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t array[]);

//The original function is: lv_chart_set_ext_x_array.
void safe_lv_chart_set_ext_x_array(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t array[]);

//The original function is: lv_chart_get_y_array.
lv_coord_t * safe_lv_chart_get_y_array(const lv_obj_t * obj, lv_chart_series_t * ser);

//The original function is: lv_chart_get_x_array.
lv_coord_t * safe_lv_chart_get_x_array(const lv_obj_t * obj, lv_chart_series_t * ser);

//The original function is: lv_chart_get_pressed_point.
uint32_t safe_lv_chart_get_pressed_point(const lv_obj_t * obj);

