//This file is automatically generated.
//The original file is lv_chart.h
#include "GhostSafeLVGL.h"
#include "safe_lv_chart.h"

//The original function is: lv_chart_create.
lv_obj_t * safe_lv_chart_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_chart_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_set_type.
void safe_lv_chart_set_type(lv_obj_t * obj, lv_chart_type_t type)
{
    GhostLV_Lock();
    lv_chart_set_type(obj, type);
    GhostLV_Unlock();
}

//The original function is: lv_chart_set_range.
void safe_lv_chart_set_range(lv_obj_t * obj, lv_chart_axis_t axis, lv_coord_t min, lv_coord_t max)
{
    GhostLV_Lock();
    lv_chart_set_range(obj, axis, min, max);
    GhostLV_Unlock();
}

//The original function is: lv_chart_set_update_mode.
void safe_lv_chart_set_update_mode(lv_obj_t * obj, lv_chart_update_mode_t update_mode)
{
    GhostLV_Lock();
    lv_chart_set_update_mode(obj, update_mode);
    GhostLV_Unlock();
}

//The original function is: lv_chart_get_zoom_x.
uint16_t safe_lv_chart_get_zoom_x(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_chart_get_zoom_x(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_zoom_y.
uint16_t safe_lv_chart_get_zoom_y(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_chart_get_zoom_y(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_type.
lv_chart_type_t safe_lv_chart_get_type(const lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_chart_type_t ret = lv_chart_get_type(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_point_count.
uint16_t safe_lv_chart_get_point_count(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint16_t ret = lv_chart_get_point_count(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_x_start_point.
uint16_t safe_lv_chart_get_x_start_point(const lv_obj_t * obj, lv_chart_series_t * ser)
{
    GhostLV_Lock();
    uint16_t ret = lv_chart_get_x_start_point(obj, ser);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_refresh.
void safe_lv_chart_refresh(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_chart_refresh(obj);
    GhostLV_Unlock();
}

//The original function is: lv_chart_add_series.
lv_chart_series_t * safe_lv_chart_add_series(lv_obj_t * obj, lv_color_t color, lv_chart_axis_t axis)
{
    GhostLV_Lock();
    lv_chart_series_t * ret = lv_chart_add_series(obj, color, axis);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_remove_series.
void safe_lv_chart_remove_series(lv_obj_t * obj, lv_chart_series_t * series)
{
    GhostLV_Lock();
    lv_chart_remove_series(obj, series);
    GhostLV_Unlock();
}

//The original function is: lv_chart_hide_series.
void safe_lv_chart_hide_series(lv_obj_t * chart, lv_chart_series_t * series, bool hide)
{
    GhostLV_Lock();
    lv_chart_hide_series(chart, series, hide);
    GhostLV_Unlock();
}

//The original function is: lv_chart_set_series_color.
void safe_lv_chart_set_series_color(lv_obj_t * chart, lv_chart_series_t * series, lv_color_t color)
{
    GhostLV_Lock();
    lv_chart_set_series_color(chart, series, color);
    GhostLV_Unlock();
}

//The original function is: lv_chart_get_series_next.
lv_chart_series_t * safe_lv_chart_get_series_next(const lv_obj_t * chart, const lv_chart_series_t * ser)
{
    GhostLV_Lock();
    lv_chart_series_t * ret = lv_chart_get_series_next(chart, ser);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_add_cursor.
lv_chart_cursor_t  * safe_lv_chart_add_cursor(lv_obj_t * obj, lv_color_t color, lv_dir_t dir)
{
    GhostLV_Lock();
    lv_chart_cursor_t  * ret = lv_chart_add_cursor(obj, color, dir);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_set_cursor_pos.
void safe_lv_chart_set_cursor_pos(lv_obj_t * chart, lv_chart_cursor_t * cursor, lv_point_t * pos)
{
    GhostLV_Lock();
    lv_chart_set_cursor_pos(chart, cursor, pos);
    GhostLV_Unlock();
}

//The original function is: lv_chart_get_cursor_point.
lv_point_t safe_lv_chart_get_cursor_point(lv_obj_t * chart, lv_chart_cursor_t * cursor)
{
    GhostLV_Lock();
    lv_point_t ret = lv_chart_get_cursor_point(chart, cursor);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_set_all_value.
void safe_lv_chart_set_all_value(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t value)
{
    GhostLV_Lock();
    lv_chart_set_all_value(obj, ser, value);
    GhostLV_Unlock();
}

//The original function is: lv_chart_set_next_value.
void safe_lv_chart_set_next_value(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t value)
{
    GhostLV_Lock();
    lv_chart_set_next_value(obj, ser, value);
    GhostLV_Unlock();
}

//The original function is: lv_chart_set_next_value2.
void safe_lv_chart_set_next_value2(lv_obj_t * obj, lv_chart_series_t * ser, lv_coord_t x_value, lv_coord_t y_value)
{
    GhostLV_Lock();
    lv_chart_set_next_value2(obj, ser, x_value, y_value);
    GhostLV_Unlock();
}

//The original function is: lv_chart_get_y_array.
lv_coord_t * safe_lv_chart_get_y_array(const lv_obj_t * obj, lv_chart_series_t * ser)
{
    GhostLV_Lock();
    lv_coord_t * ret = lv_chart_get_y_array(obj, ser);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_x_array.
lv_coord_t * safe_lv_chart_get_x_array(const lv_obj_t * obj, lv_chart_series_t * ser)
{
    GhostLV_Lock();
    lv_coord_t * ret = lv_chart_get_x_array(obj, ser);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_chart_get_pressed_point.
uint32_t safe_lv_chart_get_pressed_point(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint32_t ret = lv_chart_get_pressed_point(obj);
    GhostLV_Unlock();
    return ret;
}

