//This file is automatically generated.
//The original file is lv_keyboard.h
#include "lvgl.h"

//The original function is: lv_keyboard_create.
lv_obj_t * safe_lv_keyboard_create(lv_obj_t * parent);

//The original function is: lv_keyboard_set_textarea.
void safe_lv_keyboard_set_textarea(lv_obj_t * kb, lv_obj_t * ta);

//The original function is: lv_keyboard_set_mode.
void safe_lv_keyboard_set_mode(lv_obj_t * kb, lv_keyboard_mode_t mode);

//The original function is: lv_keyboard_set_popovers.
void safe_lv_keyboard_set_popovers(lv_obj_t * kb, bool en);

//The original function is: lv_keyboard_get_textarea.
lv_obj_t * safe_lv_keyboard_get_textarea(const lv_obj_t * kb);

//The original function is: lv_keyboard_get_mode.
lv_keyboard_mode_t safe_lv_keyboard_get_mode(const lv_obj_t * kb);

//The original function is: lv_btnmatrix_get_popovers.
bool safe_lv_btnmatrix_get_popovers(const lv_obj_t * obj);

//The original function is: lv_keyboard_def_event_cb.
void safe_lv_keyboard_def_event_cb(lv_event_t * e);

