//This file is automatically generated.
//The original file is lv_style.h
#include "lvgl.h"

//The original function is: lv_style_init.
void safe_lv_style_init(lv_style_t * style);

//The original function is: lv_style_reset.
void safe_lv_style_reset(lv_style_t * style);

//The original function is: lv_style_get_num_custom_props.
lv_style_prop_t safe_lv_style_get_num_custom_props(void);

//The original function is: lv_style_remove_prop.
bool safe_lv_style_remove_prop(lv_style_t * style, lv_style_prop_t prop);

//The original function is: lv_style_set_prop.
void safe_lv_style_set_prop(lv_style_t * style, lv_style_prop_t prop, lv_style_value_t value);

//The original function is: lv_style_get_prop.
lv_style_res_t safe_lv_style_get_prop(const lv_style_t * style, lv_style_prop_t prop, lv_style_value_t * value);

//The original function is: lv_style_prop_get_default.
lv_style_value_t safe_lv_style_prop_get_default(lv_style_prop_t prop);

//The original function is: lv_style_is_empty.
bool safe_lv_style_is_empty(const lv_style_t * style);

