//This file is automatically generated.
//The original file is lv_color.h
#include "lvgl.h"

//The original function is: lv_color_lighten.
lv_color_t safe_lv_color_lighten(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_darken.
lv_color_t safe_lv_color_darken(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_change_lightness.
lv_color_t safe_lv_color_change_lightness(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_to_hsv.
lv_color_hsv_t safe_lv_color_to_hsv(lv_color_t color);

//The original function is: lv_palette_main.
lv_color_t safe_lv_palette_main(lv_palette_t p);

