//This file is automatically generated.
//The original file is lv_style_gen.h
#include "GhostSafeLVGL.h"
#include "safe_lv_style_gen.h"

//The original function is: lv_style_set_width.
void safe_lv_style_set_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_min_width.
void safe_lv_style_set_min_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_min_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_max_width.
void safe_lv_style_set_max_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_max_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_height.
void safe_lv_style_set_height(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_height(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_min_height.
void safe_lv_style_set_min_height(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_min_height(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_max_height.
void safe_lv_style_set_max_height(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_max_height(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_x.
void safe_lv_style_set_x(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_x(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_y.
void safe_lv_style_set_y(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_y(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_align.
void safe_lv_style_set_align(lv_style_t * style, lv_align_t value)
{
    GhostLV_Lock();
    lv_style_set_align(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_transform_width.
void safe_lv_style_set_transform_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_transform_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_transform_height.
void safe_lv_style_set_transform_height(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_transform_height(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_translate_x.
void safe_lv_style_set_translate_x(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_translate_x(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_translate_y.
void safe_lv_style_set_translate_y(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_translate_y(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_transform_zoom.
void safe_lv_style_set_transform_zoom(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_transform_zoom(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_transform_angle.
void safe_lv_style_set_transform_angle(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_transform_angle(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_top.
void safe_lv_style_set_pad_top(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_top(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_bottom.
void safe_lv_style_set_pad_bottom(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_bottom(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_left.
void safe_lv_style_set_pad_left(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_left(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_right.
void safe_lv_style_set_pad_right(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_right(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_row.
void safe_lv_style_set_pad_row(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_row(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_pad_column.
void safe_lv_style_set_pad_column(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_pad_column(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_color.
void safe_lv_style_set_bg_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_color_filtered.
void safe_lv_style_set_bg_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_opa.
void safe_lv_style_set_bg_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_grad_color.
void safe_lv_style_set_bg_grad_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_grad_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_grad_color_filtered.
void safe_lv_style_set_bg_grad_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_grad_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_grad_dir.
void safe_lv_style_set_bg_grad_dir(lv_style_t * style, lv_grad_dir_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_grad_dir(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_main_stop.
void safe_lv_style_set_bg_main_stop(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_main_stop(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_grad_stop.
void safe_lv_style_set_bg_grad_stop(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_grad_stop(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_grad.
void safe_lv_style_set_bg_grad(lv_style_t * style, const lv_grad_dsc_t * value)
{
    GhostLV_Lock();
    lv_style_set_bg_grad(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_dither_mode.
void safe_lv_style_set_bg_dither_mode(lv_style_t * style, lv_dither_mode_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_dither_mode(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_src.
void safe_lv_style_set_bg_img_src(lv_style_t * style, const void * value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_src(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_opa.
void safe_lv_style_set_bg_img_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_recolor.
void safe_lv_style_set_bg_img_recolor(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_recolor(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_recolor_filtered.
void safe_lv_style_set_bg_img_recolor_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_recolor_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_recolor_opa.
void safe_lv_style_set_bg_img_recolor_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_recolor_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_bg_img_tiled.
void safe_lv_style_set_bg_img_tiled(lv_style_t * style, bool value)
{
    GhostLV_Lock();
    lv_style_set_bg_img_tiled(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_color.
void safe_lv_style_set_border_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_border_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_color_filtered.
void safe_lv_style_set_border_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_border_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_opa.
void safe_lv_style_set_border_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_border_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_width.
void safe_lv_style_set_border_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_border_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_side.
void safe_lv_style_set_border_side(lv_style_t * style, lv_border_side_t value)
{
    GhostLV_Lock();
    lv_style_set_border_side(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_border_post.
void safe_lv_style_set_border_post(lv_style_t * style, bool value)
{
    GhostLV_Lock();
    lv_style_set_border_post(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_outline_width.
void safe_lv_style_set_outline_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_outline_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_outline_color.
void safe_lv_style_set_outline_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_outline_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_outline_color_filtered.
void safe_lv_style_set_outline_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_outline_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_outline_opa.
void safe_lv_style_set_outline_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_outline_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_outline_pad.
void safe_lv_style_set_outline_pad(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_outline_pad(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_width.
void safe_lv_style_set_shadow_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_ofs_x.
void safe_lv_style_set_shadow_ofs_x(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_ofs_x(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_ofs_y.
void safe_lv_style_set_shadow_ofs_y(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_ofs_y(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_spread.
void safe_lv_style_set_shadow_spread(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_spread(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_color.
void safe_lv_style_set_shadow_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_color_filtered.
void safe_lv_style_set_shadow_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_shadow_opa.
void safe_lv_style_set_shadow_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_shadow_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_img_opa.
void safe_lv_style_set_img_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_img_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_img_recolor.
void safe_lv_style_set_img_recolor(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_img_recolor(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_img_recolor_filtered.
void safe_lv_style_set_img_recolor_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_img_recolor_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_img_recolor_opa.
void safe_lv_style_set_img_recolor_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_img_recolor_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_width.
void safe_lv_style_set_line_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_line_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_dash_width.
void safe_lv_style_set_line_dash_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_line_dash_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_dash_gap.
void safe_lv_style_set_line_dash_gap(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_line_dash_gap(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_rounded.
void safe_lv_style_set_line_rounded(lv_style_t * style, bool value)
{
    GhostLV_Lock();
    lv_style_set_line_rounded(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_color.
void safe_lv_style_set_line_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_line_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_color_filtered.
void safe_lv_style_set_line_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_line_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_line_opa.
void safe_lv_style_set_line_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_line_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_width.
void safe_lv_style_set_arc_width(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_arc_width(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_rounded.
void safe_lv_style_set_arc_rounded(lv_style_t * style, bool value)
{
    GhostLV_Lock();
    lv_style_set_arc_rounded(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_color.
void safe_lv_style_set_arc_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_arc_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_color_filtered.
void safe_lv_style_set_arc_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_arc_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_opa.
void safe_lv_style_set_arc_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_arc_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_arc_img_src.
void safe_lv_style_set_arc_img_src(lv_style_t * style, const void * value)
{
    GhostLV_Lock();
    lv_style_set_arc_img_src(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_color.
void safe_lv_style_set_text_color(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_text_color(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_color_filtered.
void safe_lv_style_set_text_color_filtered(lv_style_t * style, lv_color_t value)
{
    GhostLV_Lock();
    lv_style_set_text_color_filtered(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_opa.
void safe_lv_style_set_text_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_text_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_font.
void safe_lv_style_set_text_font(lv_style_t * style, const lv_font_t * value)
{
    GhostLV_Lock();
    lv_style_set_text_font(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_letter_space.
void safe_lv_style_set_text_letter_space(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_text_letter_space(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_line_space.
void safe_lv_style_set_text_line_space(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_text_line_space(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_decor.
void safe_lv_style_set_text_decor(lv_style_t * style, lv_text_decor_t value)
{
    GhostLV_Lock();
    lv_style_set_text_decor(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_text_align.
void safe_lv_style_set_text_align(lv_style_t * style, lv_text_align_t value)
{
    GhostLV_Lock();
    lv_style_set_text_align(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_radius.
void safe_lv_style_set_radius(lv_style_t * style, lv_coord_t value)
{
    GhostLV_Lock();
    lv_style_set_radius(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_clip_corner.
void safe_lv_style_set_clip_corner(lv_style_t * style, bool value)
{
    GhostLV_Lock();
    lv_style_set_clip_corner(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_opa.
void safe_lv_style_set_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_color_filter_dsc.
void safe_lv_style_set_color_filter_dsc(lv_style_t * style, const lv_color_filter_dsc_t * value)
{
    GhostLV_Lock();
    lv_style_set_color_filter_dsc(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_color_filter_opa.
void safe_lv_style_set_color_filter_opa(lv_style_t * style, lv_opa_t value)
{
    GhostLV_Lock();
    lv_style_set_color_filter_opa(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_transition.
void safe_lv_style_set_transition(lv_style_t * style, const lv_style_transition_dsc_t * value)
{
    GhostLV_Lock();
    lv_style_set_transition(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_blend_mode.
void safe_lv_style_set_blend_mode(lv_style_t * style, lv_blend_mode_t value)
{
    GhostLV_Lock();
    lv_style_set_blend_mode(style, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_set_base_dir.
void safe_lv_style_set_base_dir(lv_style_t * style, lv_base_dir_t value)
{
    GhostLV_Lock();
    lv_style_set_base_dir(style, value);
    GhostLV_Unlock();
}

