//This file is automatically generated.
//The original file is lv_tlsf.h
#include "GhostSafeLVGL.h"
#include "safe_lv_tlsf.h"

//The original function is: lv_tlsf_create.
lv_tlsf_t safe_lv_tlsf_create(void * mem)
{
    GhostLV_Lock();
    lv_tlsf_t ret = lv_tlsf_create(mem);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_create_with_pool.
lv_tlsf_t safe_lv_tlsf_create_with_pool(void * mem, size_t bytes)
{
    GhostLV_Lock();
    lv_tlsf_t ret = lv_tlsf_create_with_pool(mem, bytes);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_destroy.
void safe_lv_tlsf_destroy(lv_tlsf_t tlsf)
{
    GhostLV_Lock();
    lv_tlsf_destroy(tlsf);
    GhostLV_Unlock();
}

//The original function is: lv_tlsf_get_pool.
lv_pool_t safe_lv_tlsf_get_pool(lv_tlsf_t tlsf)
{
    GhostLV_Lock();
    lv_pool_t ret = lv_tlsf_get_pool(tlsf);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_add_pool.
lv_pool_t safe_lv_tlsf_add_pool(lv_tlsf_t tlsf, void * mem, size_t bytes)
{
    GhostLV_Lock();
    lv_pool_t ret = lv_tlsf_add_pool(tlsf, mem, bytes);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_remove_pool.
void safe_lv_tlsf_remove_pool(lv_tlsf_t tlsf, lv_pool_t pool)
{
    GhostLV_Lock();
    lv_tlsf_remove_pool(tlsf, pool);
    GhostLV_Unlock();
}

//The original function is: lv_tlsf_malloc.
void * safe_lv_tlsf_malloc(lv_tlsf_t tlsf, size_t bytes)
{
    GhostLV_Lock();
    void * ret = lv_tlsf_malloc(tlsf, bytes);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_memalign.
void * safe_lv_tlsf_memalign(lv_tlsf_t tlsf, size_t align, size_t bytes)
{
    GhostLV_Lock();
    void * ret = lv_tlsf_memalign(tlsf, align, bytes);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_realloc.
void * safe_lv_tlsf_realloc(lv_tlsf_t tlsf, void * ptr, size_t size)
{
    GhostLV_Lock();
    void * ret = lv_tlsf_realloc(tlsf, ptr, size);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_free.
void safe_lv_tlsf_free(lv_tlsf_t tlsf, const void * ptr)
{
    GhostLV_Lock();
    lv_tlsf_free(tlsf, ptr);
    GhostLV_Unlock();
}

//The original function is: lv_tlsf_block_size.
size_t safe_lv_tlsf_block_size(void * ptr)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_block_size(ptr);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_size.
size_t safe_lv_tlsf_size(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_size();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_align_size.
size_t safe_lv_tlsf_align_size(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_align_size();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_block_size_min.
size_t safe_lv_tlsf_block_size_min(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_block_size_min();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_block_size_max.
size_t safe_lv_tlsf_block_size_max(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_block_size_max();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_pool_overhead.
size_t safe_lv_tlsf_pool_overhead(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_pool_overhead();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_alloc_overhead.
size_t safe_lv_tlsf_alloc_overhead(void)
{
    GhostLV_Lock();
    size_t ret = lv_tlsf_alloc_overhead();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_walk_pool.
void safe_lv_tlsf_walk_pool(lv_pool_t pool, lv_tlsf_walker walker, void * user)
{
    GhostLV_Lock();
    lv_tlsf_walk_pool(pool, walker, user);
    GhostLV_Unlock();
}

//The original function is: lv_tlsf_check.
int safe_lv_tlsf_check(lv_tlsf_t tlsf)
{
    GhostLV_Lock();
    int ret = lv_tlsf_check(tlsf);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_tlsf_check_pool.
int safe_lv_tlsf_check_pool(lv_pool_t pool)
{
    GhostLV_Lock();
    int ret = lv_tlsf_check_pool(pool);
    GhostLV_Unlock();
    return ret;
}

