//This file is automatically generated.
//The original file is lv_style.h
#include "GhostSafeLVGL.h"
#include "safe_lv_style.h"

//The original function is: lv_style_init.
void safe_lv_style_init(lv_style_t * style)
{
    GhostLV_Lock();
    lv_style_init(style);
    GhostLV_Unlock();
}

//The original function is: lv_style_reset.
void safe_lv_style_reset(lv_style_t * style)
{
    GhostLV_Lock();
    lv_style_reset(style);
    GhostLV_Unlock();
}

//The original function is: lv_style_get_num_custom_props.
lv_style_prop_t safe_lv_style_get_num_custom_props(void)
{
    GhostLV_Lock();
    lv_style_prop_t ret = lv_style_get_num_custom_props();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_style_remove_prop.
bool safe_lv_style_remove_prop(lv_style_t * style, lv_style_prop_t prop)
{
    GhostLV_Lock();
    bool ret = lv_style_remove_prop(style, prop);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_style_set_prop.
void safe_lv_style_set_prop(lv_style_t * style, lv_style_prop_t prop, lv_style_value_t value)
{
    GhostLV_Lock();
    lv_style_set_prop(style, prop, value);
    GhostLV_Unlock();
}

//The original function is: lv_style_get_prop.
lv_style_res_t safe_lv_style_get_prop(const lv_style_t * style, lv_style_prop_t prop, lv_style_value_t * value)
{
    GhostLV_Lock();
    lv_style_res_t ret = lv_style_get_prop(style, prop, value);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_style_prop_get_default.
lv_style_value_t safe_lv_style_prop_get_default(lv_style_prop_t prop)
{
    GhostLV_Lock();
    lv_style_value_t ret = lv_style_prop_get_default(prop);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_style_is_empty.
bool safe_lv_style_is_empty(const lv_style_t * style)
{
    GhostLV_Lock();
    bool ret = lv_style_is_empty(style);
    GhostLV_Unlock();
    return ret;
}

