//This file is automatically generated.
//The original file is lv_lru.h
#include "lv_lru.h"

//The original function is: lv_lru_del.
void safe_lv_lru_del(lv_lru_t * cache);

//The original function is: lv_lru_set.
lv_lru_res_t safe_lv_lru_set(lv_lru_t * cache, const void * key, size_t key_length, void * value, size_t value_length);

//The original function is: lv_lru_get.
lv_lru_res_t safe_lv_lru_get(lv_lru_t * cache, const void * key, size_t key_size, void ** value);

//The original function is: lv_lru_remove.
lv_lru_res_t safe_lv_lru_remove(lv_lru_t * cache, const void * key, size_t key_size);

