//This file is automatically generated.
//The original file is lv_anim.h
#include "lvgl.h"

//The original function is: lv_anim_init.
void safe_lv_anim_init(lv_anim_t * a);

//The original function is: lv_anim_start.
lv_anim_t * safe_lv_anim_start(const lv_anim_t * a);

//The original function is: lv_anim_get_playtime.
uint32_t safe_lv_anim_get_playtime(lv_anim_t * a);

//The original function is: lv_anim_del.
bool safe_lv_anim_del(void * var, lv_anim_exec_xcb_t exec_cb);

//The original function is: lv_anim_del_all.
void safe_lv_anim_del_all(void);

//The original function is: lv_anim_get.
lv_anim_t * safe_lv_anim_get(void * var, lv_anim_exec_xcb_t exec_cb);

//The original function is: lv_anim_count_running.
uint16_t safe_lv_anim_count_running(void);

//The original function is: lv_anim_refr_now.
void safe_lv_anim_refr_now(void);

//The original function is: lv_anim_path_linear.
int32_t safe_lv_anim_path_linear(const lv_anim_t * a);

//The original function is: lv_anim_path_ease_in.
int32_t safe_lv_anim_path_ease_in(const lv_anim_t * a);

//The original function is: lv_anim_path_ease_out.
int32_t safe_lv_anim_path_ease_out(const lv_anim_t * a);

//The original function is: lv_anim_path_ease_in_out.
int32_t safe_lv_anim_path_ease_in_out(const lv_anim_t * a);

//The original function is: lv_anim_path_overshoot.
int32_t safe_lv_anim_path_overshoot(const lv_anim_t * a);

//The original function is: lv_anim_path_bounce.
int32_t safe_lv_anim_path_bounce(const lv_anim_t * a);

//The original function is: lv_anim_path_step.
int32_t safe_lv_anim_path_step(const lv_anim_t * a);

