//This file is automatically generated.
//The original file is lv_anim_timeline.h
#include "lv_anim_timeline.h"

//The original function is: lv_anim_timeline_create.
lv_anim_timeline_t * safe_lv_anim_timeline_create(void);

//The original function is: lv_anim_timeline_del.
void safe_lv_anim_timeline_del(lv_anim_timeline_t * at);

//The original function is: lv_anim_timeline_add.
void safe_lv_anim_timeline_add(lv_anim_timeline_t * at, uint32_t start_time, lv_anim_t * a);

//The original function is: lv_anim_timeline_start.
uint32_t safe_lv_anim_timeline_start(lv_anim_timeline_t * at);

//The original function is: lv_anim_timeline_stop.
void safe_lv_anim_timeline_stop(lv_anim_timeline_t * at);

//The original function is: lv_anim_timeline_set_reverse.
void safe_lv_anim_timeline_set_reverse(lv_anim_timeline_t * at, bool reverse);

//The original function is: lv_anim_timeline_set_progress.
void safe_lv_anim_timeline_set_progress(lv_anim_timeline_t * at, uint16_t progress);

//The original function is: lv_anim_timeline_get_playtime.
uint32_t safe_lv_anim_timeline_get_playtime(lv_anim_timeline_t * at);

//The original function is: lv_anim_timeline_get_reverse.
bool safe_lv_anim_timeline_get_reverse(lv_anim_timeline_t * at);

