//This file is automatically generated.
//The original file is lv_fs.h
#include "GhostSafeLVGL.h"
#include "safe_lv_fs.h"

//The original function is: lv_fs_drv_init.
void safe_lv_fs_drv_init(lv_fs_drv_t * drv)
{
    GhostLV_Lock();
    lv_fs_drv_init(drv);
    GhostLV_Unlock();
}

//The original function is: lv_fs_drv_register.
void safe_lv_fs_drv_register(lv_fs_drv_t * drv)
{
    GhostLV_Lock();
    lv_fs_drv_register(drv);
    GhostLV_Unlock();
}

//The original function is: lv_fs_get_drv.
lv_fs_drv_t * safe_lv_fs_get_drv(char letter)
{
    GhostLV_Lock();
    lv_fs_drv_t * ret = lv_fs_get_drv(letter);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_is_ready.
bool safe_lv_fs_is_ready(char letter)
{
    GhostLV_Lock();
    bool ret = lv_fs_is_ready(letter);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_open.
lv_fs_res_t safe_lv_fs_open(lv_fs_file_t * file_p, const char * path, lv_fs_mode_t mode)
{
    GhostLV_Lock();
    lv_fs_res_t ret = lv_fs_open(file_p, path, mode);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_close.
lv_fs_res_t safe_lv_fs_close(lv_fs_file_t * file_p)
{
    GhostLV_Lock();
    lv_fs_res_t ret = lv_fs_close(file_p);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_dir_open.
lv_fs_res_t safe_lv_fs_dir_open(lv_fs_dir_t * rddir_p, const char * path)
{
    GhostLV_Lock();
    lv_fs_res_t ret = lv_fs_dir_open(rddir_p, path);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_dir_read.
lv_fs_res_t safe_lv_fs_dir_read(lv_fs_dir_t * rddir_p, char * fn)
{
    GhostLV_Lock();
    lv_fs_res_t ret = lv_fs_dir_read(rddir_p, fn);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_dir_close.
lv_fs_res_t safe_lv_fs_dir_close(lv_fs_dir_t * rddir_p)
{
    GhostLV_Lock();
    lv_fs_res_t ret = lv_fs_dir_close(rddir_p);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_get_letters.
char * safe_lv_fs_get_letters(char * buf)
{
    GhostLV_Lock();
    char * ret = lv_fs_get_letters(buf);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_get_ext.
const char * safe_lv_fs_get_ext(const char * fn)
{
    GhostLV_Lock();
    const char * ret = lv_fs_get_ext(fn);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_up.
char * safe_lv_fs_up(char * path)
{
    GhostLV_Lock();
    char * ret = lv_fs_up(path);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_fs_get_last.
const char * safe_lv_fs_get_last(const char * path)
{
    GhostLV_Lock();
    const char * ret = lv_fs_get_last(path);
    GhostLV_Unlock();
    return ret;
}

