//This file is automatically generated.
//The original file is lv_mem.h
#include "lvgl.h"

//The original function is: lv_mem_init.
void safe_lv_mem_init(void);

//The original function is: lv_mem_deinit.
void safe_lv_mem_deinit(void);

//The original function is: lv_mem_alloc.
void * safe_lv_mem_alloc(size_t size);

//The original function is: lv_mem_free.
void safe_lv_mem_free(void * data);

//The original function is: lv_mem_realloc.
void * safe_lv_mem_realloc(void * data_p, size_t new_size);

//The original function is: lv_mem_test.
lv_res_t safe_lv_mem_test(void);

//The original function is: lv_mem_monitor.
void safe_lv_mem_monitor(lv_mem_monitor_t * mon_p);

//The original function is: lv_mem_buf_release.
void safe_lv_mem_buf_release(void * p);

//The original function is: lv_mem_buf_free_all.
void safe_lv_mem_buf_free_all(void);

//The original function is: lv_memcpy.
LV_ATTRIBUTE_FAST_MEM void * safe_lv_memcpy(void * dst, const void * src, size_t len);

//The original function is: lv_memset_00.
void safe_lv_memset_00(void * dst, size_t len);

//The original function is: lv_memset_ff.
void safe_lv_memset_ff(void * dst, size_t len);

