//This file is automatically generated.
//The original file is lv_timer.h
#include "lvgl.h"

//The original function is: lv_timer_handler.
LV_ATTRIBUTE_TIMER_HANDLER uint32_t safe_lv_timer_handler(void);

//The original function is: lv_timer_create_basic.
lv_timer_t * safe_lv_timer_create_basic(void);

//The original function is: lv_timer_del.
void safe_lv_timer_del(lv_timer_t * timer);

//The original function is: lv_timer_pause.
void safe_lv_timer_pause(lv_timer_t * timer);

//The original function is: lv_timer_resume.
void safe_lv_timer_resume(lv_timer_t * timer);

//The original function is: lv_timer_set_cb.
void safe_lv_timer_set_cb(lv_timer_t * timer, lv_timer_cb_t timer_cb);

//The original function is: lv_timer_ready.
void safe_lv_timer_ready(lv_timer_t * timer);

//The original function is: lv_timer_reset.
void safe_lv_timer_reset(lv_timer_t * timer);

//The original function is: lv_timer_enable.
void safe_lv_timer_enable(bool en);

//The original function is: lv_timer_get_idle.
uint8_t safe_lv_timer_get_idle(void);

//The original function is: lv_timer_get_next.
lv_timer_t * safe_lv_timer_get_next(lv_timer_t * timer);

