//This file is automatically generated.
//The original file is lv_mem.h
#include "GhostSafeLVGL.h"
#include "safe_lv_mem.h"

//The original function is: lv_mem_init.
void safe_lv_mem_init(void)
{
    GhostLV_Lock();
    lv_mem_init();
    GhostLV_Unlock();
}

//The original function is: lv_mem_deinit.
void safe_lv_mem_deinit(void)
{
    GhostLV_Lock();
    lv_mem_deinit();
    GhostLV_Unlock();
}

//The original function is: lv_mem_alloc.
void * safe_lv_mem_alloc(size_t size)
{
    GhostLV_Lock();
    void * ret = lv_mem_alloc(size);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_mem_free.
void safe_lv_mem_free(void * data)
{
    GhostLV_Lock();
    lv_mem_free(data);
    GhostLV_Unlock();
}

//The original function is: lv_mem_realloc.
void * safe_lv_mem_realloc(void * data_p, size_t new_size)
{
    GhostLV_Lock();
    void * ret = lv_mem_realloc(data_p, new_size);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_mem_test.
lv_res_t safe_lv_mem_test(void)
{
    GhostLV_Lock();
    lv_res_t ret = lv_mem_test();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_mem_monitor.
void safe_lv_mem_monitor(lv_mem_monitor_t * mon_p)
{
    GhostLV_Lock();
    lv_mem_monitor(mon_p);
    GhostLV_Unlock();
}

//The original function is: lv_mem_buf_release.
void safe_lv_mem_buf_release(void * p)
{
    GhostLV_Lock();
    lv_mem_buf_release(p);
    GhostLV_Unlock();
}

//The original function is: lv_mem_buf_free_all.
void safe_lv_mem_buf_free_all(void)
{
    GhostLV_Lock();
    lv_mem_buf_free_all();
    GhostLV_Unlock();
}

//The original function is: lv_memcpy.
LV_ATTRIBUTE_FAST_MEM void * safe_lv_memcpy(void * dst, const void * src, size_t len)
{
    GhostLV_Lock();
    LV_ATTRIBUTE_FAST_MEM void * ret = lv_memcpy(dst, src, len);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_memset_00.
void safe_lv_memset_00(void * dst, size_t len)
{
    GhostLV_Lock();
    lv_memset_00(dst, len);
    GhostLV_Unlock();
}

//The original function is: lv_memset_ff.
void safe_lv_memset_ff(void * dst, size_t len)
{
    GhostLV_Lock();
    lv_memset_ff(dst, len);
    GhostLV_Unlock();
}

