//This file is automatically generated.
//The original file is lv_log.h
#include "lv_log.h"

//The original function is: lv_log_register_print_cb.
void safe_lv_log_register_print_cb(lv_log_print_g_cb_t print_cb);

//The original function is: lv_log.
void safe_lv_log(const char * buf);

