//This file is automatically generated.
//The original file is lv_math.h
#include "GhostSafeLVGL.h"
#include "safe_lv_math.h"

//The original function is: lv_atan2.
uint16_t safe_lv_atan2(int x, int y)
{
    GhostLV_Lock();
    uint16_t ret = lv_atan2(x, y);
    GhostLV_Unlock();
    return ret;
}

