//This file is automatically generated.
//The original file is lv_lru.h
#include "GhostSafeLVGL.h"
#include "safe_lv_lru.h"

//The original function is: lv_lru_del.
void safe_lv_lru_del(lv_lru_t * cache)
{
    GhostLV_Lock();
    lv_lru_del(cache);
    GhostLV_Unlock();
}

//The original function is: lv_lru_set.
lv_lru_res_t safe_lv_lru_set(lv_lru_t * cache, const void * key, size_t key_length, void * value, size_t value_length)
{
    GhostLV_Lock();
    lv_lru_res_t ret = lv_lru_set(cache, key, key_length, value, value_length);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_lru_get.
lv_lru_res_t safe_lv_lru_get(lv_lru_t * cache, const void * key, size_t key_size, void ** value)
{
    GhostLV_Lock();
    lv_lru_res_t ret = lv_lru_get(cache, key, key_size, value);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_lru_remove.
lv_lru_res_t safe_lv_lru_remove(lv_lru_t * cache, const void * key, size_t key_size)
{
    GhostLV_Lock();
    lv_lru_res_t ret = lv_lru_remove(cache, key, key_size);
    GhostLV_Unlock();
    return ret;
}

