//This file is automatically generated.
//The original file is lv_color.h
#include "GhostSafeLVGL.h"
#include "safe_lv_color.h"

//The original function is: lv_color_lighten.
lv_color_t safe_lv_color_lighten(lv_color_t c, lv_opa_t lvl)
{
    GhostLV_Lock();
    lv_color_t ret = lv_color_lighten(c, lvl);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_color_darken.
lv_color_t safe_lv_color_darken(lv_color_t c, lv_opa_t lvl)
{
    GhostLV_Lock();
    lv_color_t ret = lv_color_darken(c, lvl);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_color_change_lightness.
lv_color_t safe_lv_color_change_lightness(lv_color_t c, lv_opa_t lvl)
{
    GhostLV_Lock();
    lv_color_t ret = lv_color_change_lightness(c, lvl);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_color_to_hsv.
lv_color_hsv_t safe_lv_color_to_hsv(lv_color_t color)
{
    GhostLV_Lock();
    lv_color_hsv_t ret = lv_color_to_hsv(color);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_palette_main.
lv_color_t safe_lv_palette_main(lv_palette_t p)
{
    GhostLV_Lock();
    lv_color_t ret = lv_palette_main(p);
    GhostLV_Unlock();
    return ret;
}

