//This file is automatically generated.
//The original file is lv_anim_timeline.h
#include "GhostSafeLVGL.h"
#include "safe_lv_anim_timeline.h"

//The original function is: lv_anim_timeline_create.
lv_anim_timeline_t * safe_lv_anim_timeline_create(void)
{
    GhostLV_Lock();
    lv_anim_timeline_t * ret = lv_anim_timeline_create();
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_anim_timeline_del.
void safe_lv_anim_timeline_del(lv_anim_timeline_t * at)
{
    GhostLV_Lock();
    lv_anim_timeline_del(at);
    GhostLV_Unlock();
}

//The original function is: lv_anim_timeline_add.
void safe_lv_anim_timeline_add(lv_anim_timeline_t * at, uint32_t start_time, lv_anim_t * a)
{
    GhostLV_Lock();
    lv_anim_timeline_add(at, start_time, a);
    GhostLV_Unlock();
}

//The original function is: lv_anim_timeline_start.
uint32_t safe_lv_anim_timeline_start(lv_anim_timeline_t * at)
{
    GhostLV_Lock();
    uint32_t ret = lv_anim_timeline_start(at);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_anim_timeline_stop.
void safe_lv_anim_timeline_stop(lv_anim_timeline_t * at)
{
    GhostLV_Lock();
    lv_anim_timeline_stop(at);
    GhostLV_Unlock();
}

//The original function is: lv_anim_timeline_set_reverse.
void safe_lv_anim_timeline_set_reverse(lv_anim_timeline_t * at, bool reverse)
{
    GhostLV_Lock();
    lv_anim_timeline_set_reverse(at, reverse);
    GhostLV_Unlock();
}

//The original function is: lv_anim_timeline_set_progress.
void safe_lv_anim_timeline_set_progress(lv_anim_timeline_t * at, uint16_t progress)
{
    GhostLV_Lock();
    lv_anim_timeline_set_progress(at, progress);
    GhostLV_Unlock();
}

//The original function is: lv_anim_timeline_get_playtime.
uint32_t safe_lv_anim_timeline_get_playtime(lv_anim_timeline_t * at)
{
    GhostLV_Lock();
    uint32_t ret = lv_anim_timeline_get_playtime(at);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_anim_timeline_get_reverse.
bool safe_lv_anim_timeline_get_reverse(lv_anim_timeline_t * at)
{
    GhostLV_Lock();
    bool ret = lv_anim_timeline_get_reverse(at);
    GhostLV_Unlock();
    return ret;
}

