//This file is automatically generated.
//The original file is lv_log.h
#include "GhostSafeLVGL.h"
#include "safe_lv_log.h"

//The original function is: lv_log_register_print_cb.
void safe_lv_log_register_print_cb(lv_log_print_g_cb_t print_cb)
{
    GhostLV_Lock();
    lv_log_register_print_cb(print_cb);
    GhostLV_Unlock();
}

//The original function is: lv_log.
void safe_lv_log(const char * buf)
{
    GhostLV_Lock();
    lv_log(buf);
    GhostLV_Unlock();
}

