//This file is automatically generated.
//The original file is lv_math.h
#include "lv_math.h"

//The original function is: lv_trigo_sin.
LV_ATTRIBUTE_FAST_MEM int16_t safe_lv_trigo_sin(int16_t angle);

//The original function is: lv_trigo_sin.
return safe_lv_trigo_sin(angle + 90);

//The original function is: lv_bezier3.
uint32_t safe_lv_bezier3(uint32_t t, uint32_t u0, uint32_t u1, uint32_t u2, uint32_t u3);

//The original function is: lv_atan2.
uint16_t safe_lv_atan2(int x, int y);

//The original function is: lv_sqrt.
LV_ATTRIBUTE_FAST_MEM void safe_lv_sqrt(uint32_t x, lv_sqrt_res_t * q, uint32_t mask);

//The original function is: lv_pow.
int64_t safe_lv_pow(int64_t base, int8_t exp);

//The original function is: lv_map.
int32_t safe_lv_map(int32_t x, int32_t min_in, int32_t max_in, int32_t min_out, int32_t max_out);

//The original function is: lv_rand.
uint32_t safe_lv_rand(uint32_t min, uint32_t max);

