//This file is automatically generated.
//The original file is lv_area.h
#include "lvgl.h"

//The original function is: lv_area_set_width.
void safe_lv_area_set_width(lv_area_t * area_p, lv_coord_t w);

//The original function is: lv_area_set_height.
void safe_lv_area_set_height(lv_area_t * area_p, lv_coord_t h);

//The original function is: lv_area_get_size.
uint32_t safe_lv_area_get_size(const lv_area_t * area_p);

//The original function is: lv_area_increase.
void safe_lv_area_increase(lv_area_t * area, lv_coord_t w_extra, lv_coord_t h_extra);

//The original function is: lv_area_move.
void safe_lv_area_move(lv_area_t * area, lv_coord_t x_ofs, lv_coord_t y_ofs);

//The original function is: lv_area_align.
void safe_lv_area_align(const lv_area_t * base, lv_area_t * to_align, lv_align_t align, lv_coord_t ofs_x, lv_coord_t ofs_y);

