//This file is automatically generated.
//The original file is lv_async.h
#include "lv_async.h"

//The original function is: lv_async_call.
lv_res_t safe_lv_async_call(lv_async_cb_t async_xcb, void * user_data);

