//This file is automatically generated.
//The original file is lv_color.h
#include "lv_color.h"

//The original function is: lv_color_t (*lv_color_filter_cb_t).
typedef safe_lv_color_t (*lv_color_filter_cb_t)(const struct _lv_color_filter_dsc_t *, lv_color_t, lv_opa_t);

//The original function is: lv_color_mix.
res_color_saved = safe_lv_color_mix(fg_color, bg_color, ratio);

//The original function is: lv_color_to32.
c32.full        = safe_lv_color_to32(color);

//The original function is: lv_color_make((uint8_t)((c >> 16) & 0xFF), (uint8_t)((c >> 8) & 0xFF), (uint8_t).
return safe_lv_color_make((uint8_t)((c >> 16) & 0xFF), (uint8_t)((c >> 8) & 0xFF), (uint8_t)(c & 0xFF));

//The original function is: lv_color_fill.
LV_ATTRIBUTE_FAST_MEM void safe_lv_color_fill(lv_color_t * buf, lv_color_t color, uint32_t px_num);

//The original function is: lv_color_lighten.
lv_color_t safe_lv_color_lighten(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_darken.
lv_color_t safe_lv_color_darken(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_change_lightness.
lv_color_t safe_lv_color_change_lightness(lv_color_t c, lv_opa_t lvl);

//The original function is: lv_color_hsv_to_rgb.
lv_color_t safe_lv_color_hsv_to_rgb(uint16_t h, uint8_t s, uint8_t v);

//The original function is: lv_color_rgb_to_hsv.
lv_color_hsv_t safe_lv_color_rgb_to_hsv(uint8_t r8, uint8_t g8, uint8_t b8);

//The original function is: lv_color_to_hsv.
lv_color_hsv_t safe_lv_color_to_hsv(lv_color_t color);

//The original function is: lv_palette_main.
lv_color_t safe_lv_palette_main(lv_palette_t p);

//The original function is: lv_color_make.
return safe_lv_color_make(0xff, 0xff, 0xff);

//The original function is: lv_color_make.
return safe_lv_color_make(0x00, 0x0, 0x00);

//The original function is: lv_palette_lighten.
lv_color_t safe_lv_palette_lighten(lv_palette_t p, uint8_t lvl);

//The original function is: lv_palette_darken.
lv_color_t safe_lv_palette_darken(lv_palette_t p, uint8_t lvl);

