//This file is automatically generated.
//The original file is lv_demo_keypad_encoder.h
#include "GhostSafeLVGL.h"
#include "safe_lv_demo_keypad_encoder.h"

//The original function is: lv_demo_keypad_encoder.
void safe_lv_demo_keypad_encoder(void)
{
    GhostLV_Lock();
    lv_demo_keypad_encoder();
    GhostLV_Unlock();
}

