//This file is automatically generated.
//The original file is lv_menu.h
#include "GhostSafeLVGL.h"
#include "safe_lv_menu.h"

//The original function is: lv_menu_create.
lv_obj_t * safe_lv_menu_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_page_create.
lv_obj_t * safe_lv_menu_page_create(lv_obj_t * parent, char * title)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_page_create(parent, title);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_cont_create.
lv_obj_t * safe_lv_menu_cont_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_cont_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_section_create.
lv_obj_t * safe_lv_menu_section_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_section_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_separator_create.
lv_obj_t * safe_lv_menu_separator_create(lv_obj_t * parent)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_separator_create(parent);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_set_page.
void safe_lv_menu_set_page(lv_obj_t * obj, lv_obj_t * page)
{
    GhostLV_Lock();
    lv_menu_set_page(obj, page);
    GhostLV_Unlock();
}

//The original function is: lv_menu_set_sidebar_page.
void safe_lv_menu_set_sidebar_page(lv_obj_t * obj, lv_obj_t * page)
{
    GhostLV_Lock();
    lv_menu_set_sidebar_page(obj, page);
    GhostLV_Unlock();
}

//The original function is: lv_menu_set_mode_header.
void safe_lv_menu_set_mode_header(lv_obj_t * obj, lv_menu_mode_header_t mode_header)
{
    GhostLV_Lock();
    lv_menu_set_mode_header(obj, mode_header);
    GhostLV_Unlock();
}

//The original function is: lv_menu_set_mode_root_back_btn.
void safe_lv_menu_set_mode_root_back_btn(lv_obj_t * obj, lv_menu_mode_root_back_btn_t mode_root_back_btn)
{
    GhostLV_Lock();
    lv_menu_set_mode_root_back_btn(obj, mode_root_back_btn);
    GhostLV_Unlock();
}

//The original function is: lv_menu_set_load_page_event.
void safe_lv_menu_set_load_page_event(lv_obj_t * menu, lv_obj_t * obj, lv_obj_t * page)
{
    GhostLV_Lock();
    lv_menu_set_load_page_event(menu, obj, page);
    GhostLV_Unlock();
}

//The original function is: lv_menu_get_cur_main_page.
lv_obj_t * safe_lv_menu_get_cur_main_page(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_cur_main_page(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_get_cur_sidebar_page.
lv_obj_t * safe_lv_menu_get_cur_sidebar_page(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_cur_sidebar_page(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_get_main_header.
lv_obj_t * safe_lv_menu_get_main_header(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_main_header(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_get_main_header_back_btn.
lv_obj_t * safe_lv_menu_get_main_header_back_btn(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_main_header_back_btn(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_get_sidebar_header.
lv_obj_t * safe_lv_menu_get_sidebar_header(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_sidebar_header(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_get_sidebar_header_back_btn.
lv_obj_t * safe_lv_menu_get_sidebar_header_back_btn(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_menu_get_sidebar_header_back_btn(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_back_btn_is_root.
bool safe_lv_menu_back_btn_is_root(lv_obj_t * menu, lv_obj_t * obj)
{
    GhostLV_Lock();
    bool ret = lv_menu_back_btn_is_root(menu, obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_menu_clear_history.
void safe_lv_menu_clear_history(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_menu_clear_history(obj);
    GhostLV_Unlock();
}

