//This file is automatically generated.
//The original file is lv_menu.h
#include "lvgl.h"

//The original function is: lv_menu_create.
lv_obj_t * safe_lv_menu_create(lv_obj_t * parent);

//The original function is: lv_menu_page_create.
lv_obj_t * safe_lv_menu_page_create(lv_obj_t * parent, char * title);

//The original function is: lv_menu_cont_create.
lv_obj_t * safe_lv_menu_cont_create(lv_obj_t * parent);

//The original function is: lv_menu_section_create.
lv_obj_t * safe_lv_menu_section_create(lv_obj_t * parent);

//The original function is: lv_menu_separator_create.
lv_obj_t * safe_lv_menu_separator_create(lv_obj_t * parent);

//The original function is: lv_menu_set_page.
void safe_lv_menu_set_page(lv_obj_t * obj, lv_obj_t * page);

//The original function is: lv_menu_set_sidebar_page.
void safe_lv_menu_set_sidebar_page(lv_obj_t * obj, lv_obj_t * page);

//The original function is: lv_menu_set_mode_header.
void safe_lv_menu_set_mode_header(lv_obj_t * obj, lv_menu_mode_header_t mode_header);

//The original function is: lv_menu_set_mode_root_back_btn.
void safe_lv_menu_set_mode_root_back_btn(lv_obj_t * obj, lv_menu_mode_root_back_btn_t mode_root_back_btn);

//The original function is: lv_menu_set_load_page_event.
void safe_lv_menu_set_load_page_event(lv_obj_t * menu, lv_obj_t * obj, lv_obj_t * page);

//The original function is: lv_menu_get_cur_main_page.
lv_obj_t * safe_lv_menu_get_cur_main_page(lv_obj_t * obj);

//The original function is: lv_menu_get_cur_sidebar_page.
lv_obj_t * safe_lv_menu_get_cur_sidebar_page(lv_obj_t * obj);

//The original function is: lv_menu_get_main_header.
lv_obj_t * safe_lv_menu_get_main_header(lv_obj_t * obj);

//The original function is: lv_menu_get_main_header_back_btn.
lv_obj_t * safe_lv_menu_get_main_header_back_btn(lv_obj_t * obj);

//The original function is: lv_menu_get_sidebar_header.
lv_obj_t * safe_lv_menu_get_sidebar_header(lv_obj_t * obj);

//The original function is: lv_menu_get_sidebar_header_back_btn.
lv_obj_t * safe_lv_menu_get_sidebar_header_back_btn(lv_obj_t * obj);

//The original function is: lv_menu_back_btn_is_root.
bool safe_lv_menu_back_btn_is_root(lv_obj_t * menu, lv_obj_t * obj);

//The original function is: lv_menu_clear_history.
void safe_lv_menu_clear_history(lv_obj_t * obj);

