//This file is automatically generated.
//The original file is lv_gpu_nxp_pxp.h
#include "lv_gpu_nxp_pxp.h"

//The original function is: lv_gpu_nxp_pxp_init.
lv_res_t safe_lv_gpu_nxp_pxp_init(lv_nxp_pxp_cfg_t * cfg);

//The original function is: lv_gpu_nxp_pxp_deinit.
void safe_lv_gpu_nxp_pxp_deinit(void);

//The original function is: lv_gpu_nxp_pxp_enable_color_key.
void safe_lv_gpu_nxp_pxp_enable_color_key(void);

//The original function is: lv_gpu_nxp_pxp_disable_color_key.
void safe_lv_gpu_nxp_pxp_disable_color_key(void);

//The original function is: lv_gpu_nxp_pxp_enable_recolor.
void safe_lv_gpu_nxp_pxp_enable_recolor(lv_color_t color, lv_opa_t opa);

//The original function is: lv_gpu_nxp_pxp_disable_recolor.
void safe_lv_gpu_nxp_pxp_disable_recolor(void);

