//This file is automatically generated.
//The original file is lv_example_scroll.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_scroll.h"

//The original function is: lv_example_scroll_1.
void safe_lv_example_scroll_1(void)
{
    GhostLV_Lock();
    lv_example_scroll_1();
    GhostLV_Unlock();
}

//The original function is: lv_example_scroll_2.
void safe_lv_example_scroll_2(void)
{
    GhostLV_Lock();
    lv_example_scroll_2();
    GhostLV_Unlock();
}

//The original function is: lv_example_scroll_3.
void safe_lv_example_scroll_3(void)
{
    GhostLV_Lock();
    lv_example_scroll_3();
    GhostLV_Unlock();
}

//The original function is: lv_example_scroll_4.
void safe_lv_example_scroll_4(void)
{
    GhostLV_Lock();
    lv_example_scroll_4();
    GhostLV_Unlock();
}

//The original function is: lv_example_scroll_5.
void safe_lv_example_scroll_5(void)
{
    GhostLV_Lock();
    lv_example_scroll_5();
    GhostLV_Unlock();
}

//The original function is: lv_example_scroll_6.
void safe_lv_example_scroll_6(void)
{
    GhostLV_Lock();
    lv_example_scroll_6();
    GhostLV_Unlock();
}

