//This file is automatically generated.
//The original file is lv_example_scroll.h
#include "lv_example_scroll.h"

//The original function is: lv_example_scroll_1.
void safe_lv_example_scroll_1(void);

//The original function is: lv_example_scroll_2.
void safe_lv_example_scroll_2(void);

//The original function is: lv_example_scroll_3.
void safe_lv_example_scroll_3(void);

//The original function is: lv_example_scroll_4.
void safe_lv_example_scroll_4(void);

//The original function is: lv_example_scroll_5.
void safe_lv_example_scroll_5(void);

//The original function is: lv_example_scroll_6.
void safe_lv_example_scroll_6(void);

