//This file is automatically generated.
//The original file is lv_span.h
#include "GhostSafeLVGL.h"
#include "safe_lv_span.h"

//The original function is: lv_spangroup_create.
lv_obj_t * safe_lv_spangroup_create(lv_obj_t * par)
{
    GhostLV_Lock();
    lv_obj_t * ret = lv_spangroup_create(par);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_new_span.
lv_span_t * safe_lv_spangroup_new_span(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_span_t * ret = lv_spangroup_new_span(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_del_span.
void safe_lv_spangroup_del_span(lv_obj_t * obj, lv_span_t * span)
{
    GhostLV_Lock();
    lv_spangroup_del_span(obj, span);
    GhostLV_Unlock();
}

//The original function is: lv_span_set_text.
void safe_lv_span_set_text(lv_span_t * span, const char * text)
{
    GhostLV_Lock();
    lv_span_set_text(span, text);
    GhostLV_Unlock();
}

//The original function is: lv_span_set_text_static.
void safe_lv_span_set_text_static(lv_span_t * span, const char * text)
{
    GhostLV_Lock();
    lv_span_set_text_static(span, text);
    GhostLV_Unlock();
}

//The original function is: lv_spangroup_set_align.
void safe_lv_spangroup_set_align(lv_obj_t * obj, lv_text_align_t align)
{
    GhostLV_Lock();
    lv_spangroup_set_align(obj, align);
    GhostLV_Unlock();
}

//The original function is: lv_spangroup_set_overflow.
void safe_lv_spangroup_set_overflow(lv_obj_t * obj, lv_span_overflow_t overflow)
{
    GhostLV_Lock();
    lv_spangroup_set_overflow(obj, overflow);
    GhostLV_Unlock();
}

//The original function is: lv_spangroup_set_indent.
void safe_lv_spangroup_set_indent(lv_obj_t * obj, lv_coord_t indent)
{
    GhostLV_Lock();
    lv_spangroup_set_indent(obj, indent);
    GhostLV_Unlock();
}

//The original function is: lv_spangroup_set_mode.
void safe_lv_spangroup_set_mode(lv_obj_t * obj, lv_span_mode_t mode)
{
    GhostLV_Lock();
    lv_spangroup_set_mode(obj, mode);
    GhostLV_Unlock();
}

//The original function is: lv_spangroup_get_child.
lv_span_t * safe_lv_spangroup_get_child(const lv_obj_t * obj, int32_t id)
{
    GhostLV_Lock();
    lv_span_t * ret = lv_spangroup_get_child(obj, id);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_child_cnt.
uint32_t safe_lv_spangroup_get_child_cnt(const lv_obj_t * obj)
{
    GhostLV_Lock();
    uint32_t ret = lv_spangroup_get_child_cnt(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_align.
lv_text_align_t safe_lv_spangroup_get_align(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_text_align_t ret = lv_spangroup_get_align(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_overflow.
lv_span_overflow_t safe_lv_spangroup_get_overflow(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_span_overflow_t ret = lv_spangroup_get_overflow(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_indent.
lv_coord_t safe_lv_spangroup_get_indent(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_spangroup_get_indent(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_mode.
lv_span_mode_t safe_lv_spangroup_get_mode(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_span_mode_t ret = lv_spangroup_get_mode(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_max_line_h.
lv_coord_t safe_lv_spangroup_get_max_line_h(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_spangroup_get_max_line_h(obj);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_expand_width.
uint32_t safe_lv_spangroup_get_expand_width(lv_obj_t * obj, uint32_t max_width)
{
    GhostLV_Lock();
    uint32_t ret = lv_spangroup_get_expand_width(obj, max_width);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_get_expand_height.
lv_coord_t safe_lv_spangroup_get_expand_height(lv_obj_t * obj, lv_coord_t width)
{
    GhostLV_Lock();
    lv_coord_t ret = lv_spangroup_get_expand_height(obj, width);
    GhostLV_Unlock();
    return ret;
}

//The original function is: lv_spangroup_refr_mode.
void safe_lv_spangroup_refr_mode(lv_obj_t * obj)
{
    GhostLV_Lock();
    lv_spangroup_refr_mode(obj);
    GhostLV_Unlock();
}

