//This file is automatically generated.
//The original file is lv_span.h
#include "lvgl.h"

//The original function is: lv_spangroup_create.
lv_obj_t * safe_lv_spangroup_create(lv_obj_t * par);

//The original function is: lv_spangroup_new_span.
lv_span_t * safe_lv_spangroup_new_span(lv_obj_t * obj);

//The original function is: lv_spangroup_del_span.
void safe_lv_spangroup_del_span(lv_obj_t * obj, lv_span_t * span);

//The original function is: lv_span_set_text.
void safe_lv_span_set_text(lv_span_t * span, const char * text);

//The original function is: lv_spangroup_set_align.
void safe_lv_spangroup_set_align(lv_obj_t * obj, lv_text_align_t align);

//The original function is: lv_spangroup_set_overflow.
void safe_lv_spangroup_set_overflow(lv_obj_t * obj, lv_span_overflow_t overflow);

//The original function is: lv_spangroup_set_indent.
void safe_lv_spangroup_set_indent(lv_obj_t * obj, lv_coord_t indent);

//The original function is: lv_spangroup_set_mode.
void safe_lv_spangroup_set_mode(lv_obj_t * obj, lv_span_mode_t mode);

//The original function is: lv_spangroup_get_child_cnt.
uint32_t safe_lv_spangroup_get_child_cnt(const lv_obj_t * obj);

//The original function is: lv_spangroup_get_align.
lv_text_align_t safe_lv_spangroup_get_align(lv_obj_t * obj);

//The original function is: lv_spangroup_get_overflow.
lv_span_overflow_t safe_lv_spangroup_get_overflow(lv_obj_t * obj);

//The original function is: lv_spangroup_get_indent.
lv_coord_t safe_lv_spangroup_get_indent(lv_obj_t * obj);

//The original function is: lv_spangroup_get_mode.
lv_span_mode_t safe_lv_spangroup_get_mode(lv_obj_t * obj);

//The original function is: lv_spangroup_get_max_line_h.
lv_coord_t safe_lv_spangroup_get_max_line_h(lv_obj_t * obj);

//The original function is: lv_spangroup_get_expand_height.
lv_coord_t safe_lv_spangroup_get_expand_height(lv_obj_t * obj, lv_coord_t width);

//The original function is: lv_spangroup_refr_mode.
void safe_lv_spangroup_refr_mode(lv_obj_t * obj);

