//This file is automatically generated.
//The original file is lv_example_bmp.h
#include "GhostSafeLVGL.h"
#include "safe_lv_example_bmp.h"

//The original function is: lv_example_bmp_1.
void safe_lv_example_bmp_1(void)
{
    GhostLV_Lock();
    lv_example_bmp_1();
    GhostLV_Unlock();
}

