//This file is automatically generated.
//The original file is lv_demo_widgets.h
#include "GhostSafeLVGL.h"
#include "safe_lv_demo_widgets.h"

//The original function is: lv_demo_widgets.
void safe_lv_demo_widgets(void)
{
    GhostLV_Lock();
    lv_demo_widgets();
    GhostLV_Unlock();
}

