//This file is automatically generated.
//The original file is lv_png.h
#include "GhostSafeLVGL.h"
#include "safe_lv_png.h"

//The original function is: lv_png_init.
void safe_lv_png_init(void)
{
    GhostLV_Lock();
    lv_png_init();
    GhostLV_Unlock();
}

