//This file is automatically generated.
//The original file is lv_spinbox.h
#include "lv_spinbox.h"

//The original function is: lv_spinbox_create.
lv_obj_t * safe_lv_spinbox_create(lv_obj_t * parent);

//The original function is: lv_spinbox_set_value.
void safe_lv_spinbox_set_value(lv_obj_t * obj, int32_t i);

//The original function is: lv_spinbox_set_rollover.
void safe_lv_spinbox_set_rollover(lv_obj_t * obj, bool b);

//The original function is: lv_spinbox_set_digit_format.
void safe_lv_spinbox_set_digit_format(lv_obj_t * obj, uint8_t digit_count, uint8_t separator_position);

//The original function is: lv_spinbox_set_step.
void safe_lv_spinbox_set_step(lv_obj_t * obj, uint32_t step);

//The original function is: lv_spinbox_set_range.
void safe_lv_spinbox_set_range(lv_obj_t * obj, int32_t range_min, int32_t range_max);

//The original function is: lv_spinbox_set_pos.
void safe_lv_spinbox_set_pos(lv_obj_t * obj, uint8_t pos);

//The original function is: lv_spinbox_set_digit_step_direction.
void safe_lv_spinbox_set_digit_step_direction(lv_obj_t * obj, lv_dir_t direction);

//The original function is: lv_spinbox_get_rollover.
bool safe_lv_spinbox_get_rollover(lv_obj_t * obj);

//The original function is: lv_spinbox_get_value.
int32_t safe_lv_spinbox_get_value(lv_obj_t * obj);

//The original function is: lv_spinbox_get_step.
int32_t safe_lv_spinbox_get_step(lv_obj_t * obj);

//The original function is: lv_spinbox_step_next.
void safe_lv_spinbox_step_next(lv_obj_t * obj);

//The original function is: lv_spinbox_step_prev.
void safe_lv_spinbox_step_prev(lv_obj_t * obj);

//The original function is: lv_spinbox_increment.
void safe_lv_spinbox_increment(lv_obj_t * obj);

//The original function is: lv_spinbox_decrement.
void safe_lv_spinbox_decrement(lv_obj_t * obj);

