//This file is automatically generated.
//The original file is lv_spinbox.h
#include "lvgl.h"

//The original function is: lv_spinbox_create.
lv_obj_t * safe_lv_spinbox_create(lv_obj_t * parent);

//The original function is: lv_spinbox_set_rollover.
void safe_lv_spinbox_set_rollover(lv_obj_t * obj, bool b);

//The original function is: lv_spinbox_set_digit_step_direction.
void safe_lv_spinbox_set_digit_step_direction(lv_obj_t * obj, lv_dir_t direction);

//The original function is: lv_spinbox_get_rollover.
bool safe_lv_spinbox_get_rollover(lv_obj_t * obj);

//The original function is: lv_spinbox_get_value.
int32_t safe_lv_spinbox_get_value(lv_obj_t * obj);

//The original function is: lv_spinbox_get_step.
int32_t safe_lv_spinbox_get_step(lv_obj_t * obj);

//The original function is: lv_spinbox_step_next.
void safe_lv_spinbox_step_next(lv_obj_t * obj);

//The original function is: lv_spinbox_step_prev.
void safe_lv_spinbox_step_prev(lv_obj_t * obj);

//The original function is: lv_spinbox_increment.
void safe_lv_spinbox_increment(lv_obj_t * obj);

//The original function is: lv_spinbox_decrement.
void safe_lv_spinbox_decrement(lv_obj_t * obj);

